const u8 g_abEffect63Script[] = {
    BS_GotoIfLocalANotEqual(0, 38),
    BS_TeleportToSlotPosition(0),
    BS_MoveBy(0, -54),
  BS_Label(38),
    BS_SetObjectAnim(63, 0),
    BS_SetOamPriority(2),
    BS_GotoIfLocalAGreater(18, 2),
    BS_GotoIfLocalAOutOfRange(7, 14, 3),
  BS_Label(2),
    BS_SetOamPriority(1),
    BS_SetDepthBiasZero(),
  BS_Label(3),
    BS_StartOrbitMotion(1, 25),
    BS_WaitFrames(1),
    BS_ShowObject(),
    BS_WaitFrames(1),
    BS_GotoIfLocalAEqual(20, 4),
    BS_SpawnEffectOffset(63, 0, 0, 1, 3),
    BS_WaitFrames(18),
    BS_End(),
  BS_Label(4),
    BS_WaitFrames(18),
    BS_SpawnEffect(9),
    BS_End(),
};
