// Flobberworm's special attack animation; no status effect.
const u8 g_abSpecialMonsterFlobberwormAttackScript[] = {
    BS_Unk35(1, 1, 4),
    BS_Unk35(1, 2, 5),
    BS_Unk35(1, 3, 6),
    BS_Unk35(1, 4, 7),
    BS_SnapToCaster(3),
    BS_SetObjectAnim(13, 0),
    BS_SetOamPriority(0),
    BS_ShowObject(),
    BS_PlaySound(11),
    BS_MoveTo(0, 0, 10, 0, 2),
    BS_SetOamPriority(2),
    BS_StatusEffect(BSSTATUS_SpawnEffectA, 1, 1),
    BS_WaitForFieldClear(),
    BS_HideObject(),
    BS_SetOamPriority(0),
    BS_StatusEffect(BSSTATUS_SpawnEffectB, 1, 1),
    BS_StatusEffect(BSSTATUS_SpawnEffectB, 1, 2),
    BS_StatusEffect(BSSTATUS_SpawnEffectB, 1, 3),
    BS_StatusEffect(BSSTATUS_SpawnEffectB, 1, 4),
    BS_WaitFrames(10),
    BS_ReleaseKind2Emitters(),
    BS_Unk36(1, 4),
    BS_Unk36(1, 3),
    BS_Unk36(1, 2),
    BS_Unk36(1, 1),
    BS_End(),
};
