// Removes poison from one party member.
const u8 g_abSpecialHarryPoisonAntidoteScript[] = {
    BS_GotoIfLocalAEqual(1, 50),
    BS_GotoIfLocalAEqual(2, 51),
    BS_GotoIfLocalAGreater(2, 52),
    BS_WaitFrames(2),
    BS_DarkenScreenPalette(),
    BS_WaitFrames(2),
    BS_SpawnEffect(42),
    BS_IncrementLocal(0),
    BS_SpawnEffect(42),
    BS_WaitFrames(1),
    BS_TeleportToSlotPosition(0),
    BS_MoveBy(0, -70),
    BS_SetOamPriority(1),
    BS_SetDepthBiasZero(),
    BS_SetObjectAnimAndPalette(42, 0),
    BS_WaitFrames(1),
    BS_ShowObject(),
    BS_WaitFrames(15),
    BS_IncrementLocal(0),
    BS_SpawnEffect(42),
    BS_WaitFrames(100),
    BS_StatusEffect(BSSTATUS_CurePoison, 0, 0),
    BS_RestoreScreenPalette(),
    BS_AdvanceAttackOutcome(),
    BS_End(),
  BS_Label(50),
    BS_SetOamPriority(0),
    BS_SetDepthBias(2),
    BS_TeleportToSlotPosition(0),
    BS_MoveBy(0, -70),
    BS_SetObjectAnimFromTable2AndPalette(30, 0),
    BS_EnableSemiTransparency(),
    BS_SetAlphaBlend(5, 11),
    BS_WaitFrames(1),
    BS_ShowObject(),
    BS_WaitFrames(114),
    BS_End(),
  BS_Label(51),
    BS_SetOamPriority(1),
    BS_SetDepthBiasMax(),
    BS_TeleportToSlotPosition(0),
    BS_SetObjectAnimFromTable2AndPalette(28, 0),
    BS_WaitFrames(1),
    BS_ShowObject(),
    BS_WaitFrames(114),
    BS_End(),
  BS_Label(52),
    BS_SetOamPriority(1),
    BS_TeleportToSlotPosition(0),
    BS_MoveBy(0, -8),
    BS_JitterPosition(36, 8),
    BS_SetObjectAnimFromTable2AndPalette(29, 0),
    BS_WaitFrames(1),
    BS_ShowObject(),
    BS_GotoIfLocalAEqual(21, 38),
    BS_SpawnEffect(42),
  BS_Label(38),
    BS_MoveTo(0, -70, 32, 0, 0),
    BS_WaitFrames(32),
    BS_End(),
};
