// Boosts the party's spell power.
const u8 g_abSpecialHermioneProperWandTechniqueScript[] = {
    BS_GotoIfLocalAEqual(0, 39),
    BS_TeleportToSlotPosition(1),
    BS_MoveBy(0, 252),
    BS_SetObjectAnim(51, 0),
    BS_SetAlphaBlend(0, 16),
    BS_EnableSemiTransparency(),
    BS_StartFadeCounter(1, 0),
    BS_PlaySound(127),
    BS_WaitFrames(1),
    BS_ShowObject(),
    BS_WaitFrames(16),
    BS_DisableBlendMode(),
    BS_WaitFrames(60),
    BS_SetAlphaBlend(16, 0),
    BS_EnableSemiTransparency(),
    BS_StartAlphaFade(15),
    BS_WaitFrames(16),
    BS_End(),
  BS_Label(39),
    BS_SetEffectTimers(0, 0, 0, 0, 0, 63, 0, 0, 0, 0),
    BS_QueueScanlineEffect(0),
    BS_SelectFirstAlly(),
    BS_SpawnEffect(51),
    BS_WaitFrames(20),
    BS_SelectNextAlly(),
    BS_GotoIfLocalBEqual(1, 38),
    BS_SpawnEffect(51),
    BS_WaitFrames(20),
    BS_SelectNextAlly(),
    BS_GotoIfLocalBEqual(1, 38),
    BS_SpawnEffect(51),
  BS_Label(38),
    BS_WaitFrames(77),
    BS_StatusEffect(BSSTATUS_GrantExtraXp, 0, 0),
    BS_AdvanceAttackOutcome(),
    BS_End(),
};
