// Restores one party member's Magic Points to maximum.
const u8 g_abSpecialHarryReplenishMpScript[] = {
    BS_GotoIfLocalAEqual(0, 39),
    BS_TeleportTo(120, 64),
    BS_SetObjectAnim(48, 0),
    BS_StartOrbitMotionRandom(14),
    BS_StartDelayedChain(1, 1, 1),
    BS_WaitFrames(1),
    BS_ShowObject(),
    BS_WaitFrames(60),
    BS_PlaySound(145),
    BS_WaitFrames(20),
    BS_End(),
  BS_Label(39),
    BS_MoveFighterTo(120, 80, 20),
    BS_WaitFrames(25),
    BS_SetTargetOamPriority(0),
    BS_SetAlphaBlend(0, 16),
    BS_SetEffectTimers(1, 0, 0, 0, 0, 63, 0, 0, 0, 0),
    BS_QueueScanlineEffect(0),
    BS_WaitFrames(1),
    BS_PlaySound(144),
    BS_LoadBgEffect(0, 6, 15),
    BS_SetBgPaletteColorsAdjust(6, 0, 15, 1, 9),
    BS_StartFadeCounter(2, 0),
    BS_WaitFrames(20),
    BS_SpawnEffect(48),
    BS_WaitFrames(1),
    BS_SpawnEffect(48),
    BS_WaitFrames(1),
    BS_SpawnEffect(48),
    BS_WaitFrames(1),
    BS_SpawnEffect(48),
    BS_WaitFrames(1),
    BS_SpawnEffect(48),
    BS_WaitFrames(1),
    BS_SpawnEffect(48),
    BS_WaitFrames(1),
    BS_SpawnEffect(48),
    BS_WaitFrames(1),
    BS_SpawnEffect(48),
    BS_WaitFrames(1),
    BS_SpawnEffect(48),
    BS_WaitFrames(1),
    BS_SpawnEffect(48),
    BS_WaitFrames(1),
    BS_SpawnEffect(48),
    BS_WaitFrames(1),
    BS_SpawnEffect(48),
    BS_WaitFrames(1),
    BS_SpawnEffect(48),
    BS_WaitFrames(1),
    BS_SpawnEffect(48),
    BS_WaitFrames(1),
    BS_SpawnEffect(48),
    BS_WaitFrames(1),
    BS_SpawnEffect(48),
    BS_WaitFrames(1),
    BS_SpawnEffect(48),
    BS_WaitFrames(1),
    BS_SpawnEffect(48),
    BS_WaitFrames(1),
    BS_SpawnEffect(48),
    BS_WaitFrames(1),
    BS_SpawnEffect(48),
    BS_WaitFrames(1),
    BS_SpawnEffect(48),
    BS_WaitFrames(1),
    BS_SpawnEffect(48),
    BS_WaitFrames(1),
    BS_SpawnEffect(48),
    BS_WaitFrames(1),
    BS_SpawnEffect(48),
    BS_WaitFrames(1),
    BS_SpawnEffect(48),
    BS_WaitFrames(1),
    BS_SpawnEffect(48),
    BS_WaitFrames(1),
    BS_SpawnEffect(48),
    BS_WaitFrames(1),
    BS_SpawnEffect(48),
    BS_WaitFrames(1),
    BS_SpawnEffect(48),
    BS_WaitFrames(1),
    BS_SpawnEffect(48),
    BS_WaitFrames(1),
    BS_SpawnEffect(48),
    BS_WaitFrames(1),
    BS_SpawnEffect(48),
    BS_WaitFrames(10),
    BS_StartAlphaFade(15),
    BS_WaitFrames(20),
    BS_ResetBgState(0),
    BS_SetEffectTimers(0, 0, 0, 0, 0, 63, 0, 0, 0, 0),
    BS_WaitFrames(70),
    BS_StatusEffect(BSSTATUS_ReplenishTargetMp, 0, 0),
    BS_UnmuteMusic(),
    BS_MoveFighterToSlotPosition(20),
    BS_SetTargetOamPriority(1),
    BS_WaitFrames(25),
    BS_AdvanceAttackOutcome(),
    BS_End(),
};
