// Boosts gold earned from battle by 25%.
const u8 g_abSpecialRonWizardCrackerScript[] = {
    BS_SetOamPriority(1),
    BS_SetDepthBiasMax(),
    BS_SnapToCaster(0),
    BS_MoveBy(0, 224),
    BS_SetObjectAnim(46, 0),
    BS_StartOrbitMotion(5, 0),
    BS_PlaySound(124),
    BS_WaitFrames(1),
    BS_ShowObject(),
    BS_MoveTo(248, 224, 32, 0, 0),
    BS_WaitFrames(8),
    BS_SetDepthBiasZero(),
    BS_WaitFrames(17),
    BS_PlaySound(125),
    BS_WaitForCounter(),
    BS_HideObject(),
    BS_WaitFrames(30),
    BS_StatusEffect(BSSTATUS_ForceItemDrop, 0, 0),
    BS_AdvanceAttackOutcome(),
    BS_AdvanceAttackOutcome(),
    BS_AdvanceAttackOutcome(),
    BS_End(),
};
