// Chance to paralyze the target on a successful attack (Charmed/Jinxed Skeleton).
const u8 g_abSpecialMonsterSkeletonParalyzeScript[] = {
    BS_SnapToCaster(1),
    BS_SetObjectAnim(59, 0),
    BS_ShowObject(),
    BS_MoveTo(8, 8, 13, 0, 2),
    BS_WaitForFieldClear(),
    BS_AdvanceAttackOutcome(),
    BS_AdvanceAttackOutcome(),
    BS_GotoIfContextLow(38),
    BS_StatusEffect(BSSTATUS_ParalyzeMonsterChance, 25, 20),
  BS_Label(38),
    BS_SetVelocity(0, 0),
    BS_WaitFrames(3),
    BS_SetVelocity(-5, 5),
    BS_WaitFrames(3),
    BS_SetVelocity(0, 0),
    BS_WaitFrames(3),
    BS_MoveTo(18, 25, 8, 1, 1),
    BS_WaitForFieldClear(),
    BS_HideObject(),
    BS_WaitFrames(8),
    BS_AdvanceAttackOutcome(),
    BS_AdvanceAttackOutcome(),
    BS_AdvanceAttackOutcome(),
    BS_End(),
};
