// Grants the party poison immunity for one encounter.
const u8 g_abSpecialHarryPoisonImmunityScript[] = {
    BS_GotoIfLocalANotEqual(0, 44),
    BS_SetBgPaletteColors(15, 0, 14, 1),
    BS_PlaySound(141),
    BS_WaitFrames(1),
    BS_LoadBgEffect(0, 7, 14),
    BS_WaitFrames(1),
    BS_LoadBgEffect(0, 8, 14),
    BS_WaitFrames(1),
    BS_LoadBgEffect(0, 9, 14),
    BS_WaitFrames(1),
    BS_LoadBgEffect(0, 10, 14),
    BS_WaitFrames(1),
    BS_LoadBgEffect(0, 11, 14),
    BS_WaitFrames(1),
    BS_LoadBgEffect(0, 12, 14),
    BS_WaitFrames(1),
    BS_LoadBgEffect(0, 13, 14),
    BS_WaitFrames(1),
    BS_LoadBgEffect(0, 14, 14),
    BS_WaitFrames(1),
    BS_LoadBgEffect(0, 15, 14),
    BS_WaitFrames(1),
    BS_LoadBgEffect(0, 16, 14),
    BS_WaitFrames(1),
    BS_LoadBgEffect(0, 17, 14),
    BS_WaitFrames(1),
    BS_LoadBgEffect(0, 18, 14),
    BS_WaitFrames(1),
    BS_LoadBgEffect(0, 19, 14),
    BS_WaitFrames(1),
    BS_LoadBgEffect(0, 20, 14),
    BS_WaitFrames(1),
    BS_ResetBgState(0),
    BS_SelectFirstAlly(),
    BS_StatusEffect(BSSTATUS_PoisonImmune, 8, 0),
    BS_SpawnEffect(18),
    BS_IncrementLocal(0),
    BS_SpawnEffect(18),
    BS_WaitFrames(2),
    BS_SelectNextAlly(),
    BS_GotoIfLocalBEqual(1, 38),
    BS_SetLocal(0, 0),
    BS_StatusEffect(BSSTATUS_PoisonImmune, 8, 0),
    BS_SpawnEffect(18),
    BS_IncrementLocal(0),
    BS_SpawnEffect(18),
    BS_WaitFrames(2),
    BS_SelectNextAlly(),
    BS_GotoIfLocalBEqual(1, 38),
    BS_SetLocal(0, 0),
    BS_StatusEffect(BSSTATUS_PoisonImmune, 8, 0),
    BS_SpawnEffect(18),
    BS_IncrementLocal(0),
    BS_SpawnEffect(18),
  BS_Label(38),
    BS_WaitFrames(140),
    BS_AdvanceAttackOutcome(),
    BS_End(),
  BS_Label(44),
    BS_GotoIfLocalANotEqual(1, 43),
    BS_TeleportToSlotPosition(0),
    BS_SetOamPriority(2),
    BS_SetObjectAnimFromTable2AndPalette(10, 0),
    BS_UnmuteMusic(),
    BS_PlaySound(142),
    BS_WaitFrames(1),
    BS_ShowObject(),
    BS_WaitFrames(119),
    BS_UnmuteMusic(),
    BS_End(),
  BS_Label(43),
    BS_TeleportToSlotPosition(0),
    BS_SetOamPriority(1),
    BS_SetDepthBiasZero(),
    BS_SetObjectAnim(18, 0),
    BS_WaitFrames(1),
    BS_ShowObject(),
    BS_WaitFrames(119),
    BS_End(),
};
