// Revives an unconscious party member.
const u8 g_abSpecialHarryReviveScript[] = {
    BS_GotoIfLocalANotEqual(0, 38),
    BS_WaitFrames(2),
    BS_DarkenScreenPalette(),
    BS_WaitFrames(2),
    BS_TeleportToSlotPosition(0),
    BS_MoveBy(0, -8),
    BS_SetOamPriority(1),
    BS_SetDepthBiasMax(),
    BS_EnableSemiTransparency(),
    BS_SetAlphaBlend(0, 0),
    BS_WaitFrames(1),
    BS_SetObjectAnim(37, 0),
    BS_StartFadeCounter(2, 0),
    BS_WaitFrames(2),
    BS_ShowObject(),
    BS_SetVelocity16(0, 0x0000, 255, 0x0080),
    BS_WaitFrames(100),
    BS_StopMove(),
    BS_SpawnEffect(37),
    BS_WaitFrames(30),
    BS_SpawnEffect(37),
    BS_WaitFrames(30),
    BS_SpawnEffect(37),
    BS_WaitFrames(30),
    BS_StatusEffect(BSSTATUS_Revive, 0, 0),
    BS_SetVelocity(0, -1),
    BS_WaitFrames(5),
    BS_StartAlphaFade(15),
    BS_WaitFrames(30),
    BS_RestoreScreenPalette(),
    BS_WaitFrames(20),
    BS_AdvanceAttackOutcome(),
    BS_End(),
  BS_Label(38),
    BS_TeleportToSlotPosition(0),
    BS_MoveBy(3, -64),
    BS_JitterPosition(10, 0),
    BS_SetObjectAnimFromTable2AndPalette(22, 0),
    BS_PlaySound(149),
    BS_WaitFrames(1),
    BS_ShowObject(),
    BS_WaitFrames(5),
    BS_SetVelocity(0, 1),
    BS_WaitFrames(2),
    BS_SetVelocity(0, 2),
    BS_WaitFrames(4),
    BS_SetVelocity(0, 4),
    BS_WaitFrames(4),
    BS_End(),
};
