// Horklump spores appear and blast the opponent with pollen.
const u8 g_abSpecialHarryHorklumpSporesScript[] = {
    BS_GotoIfLocalAEqual(0, 37),
    BS_GotoIfLocalAEqual(10, 33),
    BS_GotoIfLocalAEqual(20, 34),
    BS_GotoIfLocalAEqual(21, 35),
    BS_GotoIfLocalAEqual(22, 36),
    BS_PlaySound(131),
    BS_SetObjectAnim(15, 0),
    BS_SetOamPriority(1),
    BS_ShowObject(),
    BS_WaitForCounter(),
    BS_WaitFrames(10),
    BS_SetObjectAnim(15, 11),
    BS_WaitFrames(6),
    BS_SetLocal(0, 19),
    BS_SpawnEffectOffsetDetached(15, 1, 8, -1, 32),
    BS_PlaySound(132),
    BS_WaitFrames(12),
    BS_SpawnEffectOffsetDetached(15, 1, 8, -1, 32),
    BS_PlaySound(132),
    BS_WaitFrames(12),
    BS_SpawnEffectOffsetDetached(15, 1, 8, -1, 32),
    BS_PlaySound(132),
    BS_WaitFrames(12),
    BS_SpawnEffectOffsetDetached(15, 1, 8, -1, 32),
    BS_PlaySound(132),
    BS_WaitFrames(12),
    BS_SpawnEffectOffsetDetached(15, 1, 8, -1, 32),
    BS_PlaySound(132),
    BS_WaitFrames(6),
    BS_SetObjectAnim(15, 9),
    BS_WaitFrames(20),
    BS_SetObjectAnim(15, 16),
    BS_WaitForCounter(),
    BS_End(),
  BS_Label(37),
    BS_SetLocal(0, 9),
    BS_TeleportTo(200, 70),
    BS_SpawnEffectAtSelfDetached(15),
    BS_SetLocal(0, 1),
    BS_TeleportTo(76, 112),
    BS_SpawnEffectAtSelf(15),
    BS_WaitFrames(5),
    BS_SetLocal(0, 9),
    BS_TeleportTo(175, 60),
    BS_SpawnEffectAtSelfDetached(15),
    BS_SetLocal(0, 1),
    BS_TeleportTo(46, 100),
    BS_SpawnEffectAtSelf(15),
    BS_WaitFrames(5),
    BS_SetLocal(0, 9),
    BS_TeleportTo(225, 60),
    BS_SpawnEffectAtSelfDetached(15),
    BS_TeleportTo(16, 112),
    BS_SetObjectAnim(15, 0),
    BS_SetOamPriority(1),
    BS_ShowObject(),
    BS_WaitForCounter(),
    BS_WaitFrames(10),
    BS_SetObjectAnim(15, 11),
    BS_WaitFrames(6),
    BS_QueueScanlineEffect(0),
    BS_Unk1F(0, 255, 0),
    BS_SetAlphaBlend(0, 16),
    BS_SetEffectTimers(1, 0, 0, 0, 0, 63, 0, 0, 0, 0),
    BS_LoadBgEffect(0, 4, 15),
    BS_SetBgPaletteColors(4, 0, 15, 1),
    BS_WaitFrames(1),
    BS_StartFadeCounter(2, 9),
    BS_SetLocal(0, 19),
    BS_SpawnEffectOffsetDetached(15, 1, 8, -1, 32),
    BS_PlaySound(132),
    BS_WaitFrames(12),
    BS_SpawnEffectOffsetDetached(15, 1, 8, -1, 32),
    BS_PlaySound(132),
    BS_WaitFrames(12),
    BS_SpawnEffectOffsetDetached(15, 1, 8, -1, 32),
    BS_PlaySound(132),
    BS_WaitFrames(12),
    BS_SpawnEffectOffsetDetached(15, 1, 8, -1, 32),
    BS_PlaySound(132),
    BS_WaitFrames(12),
    BS_SpawnEffectOffsetDetached(15, 1, 8, -1, 32),
    BS_PlaySound(132),
    BS_WaitFrames(6),
    BS_StartAlphaFade(8),
    BS_SetObjectAnim(15, 9),
    BS_WaitFrames(20),
    BS_SetObjectAnim(15, 16),
    BS_WaitForCounter(),
    BS_ResetBgState(0),
    BS_SetEffectTimers(0, 0, 0, 0, 0, 63, 0, 0, 0, 0),
    BS_SetAlphaBlend(0, 16),
    BS_AdvanceAttackOutcome(),
    BS_AdvanceAttackOutcome(),
    BS_AdvanceAttackOutcome(),
    BS_AdvanceAttackOutcome(),
    BS_End(),
  BS_Label(33),
    BS_SetObjectAnim(15, 0),
    BS_WaitFrames(1),
    BS_SetObjectAnimFromTable2AndPalette(8, 0),
    BS_WaitFrames(1),
    BS_SetOamPriority(1),
    BS_ShowObject(),
    BS_WaitForCounter(),
    BS_WaitFrames(10),
    BS_SetObjectAnimFromTable2(8, 11),
    BS_WaitFrames(6),
    BS_SetLocal(0, 19),
    BS_SpawnEffectOffsetDetached(15, -1, 4, -1, 16),
    BS_WaitFrames(12),
    BS_SpawnEffectOffsetDetached(15, -1, 4, -1, 16),
    BS_WaitFrames(12),
    BS_SpawnEffectOffsetDetached(15, -1, 4, -1, 16),
    BS_WaitFrames(12),
    BS_SpawnEffectOffsetDetached(15, -1, 4, -1, 16),
    BS_WaitFrames(12),
    BS_SpawnEffectOffsetDetached(15, -1, 4, -1, 16),
    BS_WaitFrames(6),
    BS_SetObjectAnimFromTable2(8, 9),
    BS_WaitFrames(20),
    BS_SetObjectAnimFromTable2(8, 16),
    BS_WaitForCounter(),
    BS_End(),
  BS_Label(34),
    BS_SpawnEffectAtSelfDetached(15),
    BS_IncrementLocal(0),
    BS_SpawnEffectAtSelfDetached(15),
    BS_SetObjectAnim(15, 0),
    BS_WaitFrames(1),
    BS_SetObjectAnimFromTable2AndPalette(9, 0),
    BS_WaitFrames(1),
    BS_SetOamPriority(1),
    BS_ShowObject(),
    BS_SetVelocity(0, -2),
    BS_WaitForCounter(),
    BS_End(),
  BS_Label(35),
    BS_SetObjectAnim(15, 0),
    BS_WaitFrames(1),
    BS_SetObjectAnimFromTable2AndPalette(9, 0),
    BS_WaitFrames(1),
    BS_SetOamPriority(1),
    BS_ShowObject(),
    BS_SetVelocity(2, -2),
    BS_WaitForCounter(),
    BS_End(),
  BS_Label(36),
    BS_SetObjectAnim(15, 0),
    BS_WaitFrames(1),
    BS_SetObjectAnimFromTable2AndPalette(9, 0),
    BS_WaitFrames(1),
    BS_SetOamPriority(1),
    BS_ShowObject(),
    BS_SetVelocity(-2, -2),
    BS_WaitForCounter(),
    BS_End(),
};
