// Distracts an opponent, causing it to lose a turn.
const u8 g_abSpecialHarrySnitchScript[] = {
    BS_TeleportTo(240, 60),
    BS_SetOamPriority(1),
    BS_SetDepthBiasZero(),
    BS_WaitFrames(2),
    BS_DarkenScreenPalette(),
    BS_WaitFrames(2),
    BS_SetObjectAnim(47, 0),
    BS_PlaySound(139),
    BS_Unk35(1, 2, 9),
    BS_CreateEmitterOnSelf(8, 1, 10, 10, 1, 246, 10, 255, 0, 2, 1, 2, 9, 180, 1, 0),
    BS_StartAffineWobble(0x0100, 0x0100, 0, 24, 24, 0),
    BS_WaitFrames(1),
    BS_ShowObject(),
    BS_MoveTo(0, -16, 10, 0, 0),
    BS_WaitForFieldClear(),
    BS_StopAffineWobble(),
    BS_PlaySound(138),
    BS_SetVelocity(0, 0),
    BS_WaitFrames(5),
    BS_SetVelocity(8, -16),
    BS_WaitFrames(2),
    BS_SetVelocity(0, 0),
    BS_WaitFrames(5),
    BS_SetVelocity(-16, 8),
    BS_WaitFrames(2),
    BS_SetVelocity(0, 0),
    BS_WaitFrames(5),
    BS_SetVelocity(12, 12),
    BS_WaitFrames(2),
    BS_SetVelocity(0, 0),
    BS_WaitFrames(5),
    BS_SetVelocity(-12, 0),
    BS_WaitFrames(2),
    BS_SetVelocity(0, 0),
    BS_WaitFrames(5),
    BS_SetVelocity(20, -16),
    BS_WaitFrames(2),
    BS_SetVelocity(0, 0),
    BS_WaitFrames(5),
    BS_SetVelocity(-18, 2),
    BS_WaitFrames(2),
    BS_UnmuteMusic(),
    BS_PlaySound(139),
    BS_StatusEffect(BSSTATUS_Paralyze80, 0, 0),
    BS_SetVelocity(0, 0),
    BS_WaitFrames(8),
    BS_StartAffineWobble(0x0080, 0x0080, 0, 232, 232, 0),
    BS_SetVelocity(15, 0),
    BS_WaitFrames(10),
    BS_StopAffineWobble(),
    BS_WaitFrames(40),
    BS_RestoreScreenPalette(),
    BS_AdvanceAttackOutcome(),
    BS_End(),
};
