// Dragonfly/Imperial Dragonfly's special attack animation; no status effect.
const u8 g_abSpecialMonsterDragonflyAttackScript[] = {
    BS_SetCasterAnim(17, 2),
    BS_NudgeCaster(64, 9),
    BS_StartCasterOrbitMotion(10, 0),
    BS_WaitFrames(12),
    BS_StartCasterOrbitMotion(8, 0),
    BS_NudgeCaster(64, 0),
    BS_SetCasterVelocityProduct(1, 48, 254, 96),
    BS_WaitFrames(1),
    BS_AdvanceAttackOutcome(),
    BS_AdvanceAttackOutcome(),
    BS_AdvanceAttackOutcome(),
    BS_AdvanceAttackOutcome(),
    BS_WaitFrames(23),
    BS_SetCasterPosition(0, 0),
    BS_MoveCasterTo(0, 0, 10, 1, 0),
    BS_SetCasterAnim(17, 17),
    BS_WaitFrames(10),
    BS_SnapCasterToSpawn(),
    BS_AdvanceAttackOutcome(),
    BS_AdvanceAttackOutcome(),
    BS_AdvanceAttackOutcome(),
    BS_End(),
};
