// Whomping Willow's special attack animation; no status effect.
const u8 g_abSpecialMonsterWhompingWillowAttackScript[] = {
    BS_TeleportToSlotPosition(0),
    BS_MoveBy(0, -120),
    BS_SetObjectAnim(61, 0),
    BS_WaitFrames(1),
    BS_ShowObject(),
    BS_SetVelocity(0, 10),
    BS_WaitFrames(2),
    BS_SetVelocity(0, 14),
    BS_WaitFrames(2),
    BS_SetVelocity(0, 16),
    BS_GotoIfContextLow(38),
    BS_StatusEffect(BSSTATUS_PaletteFlash, 0, 0),
  BS_Label(38),
    BS_WaitFrames(2),
    BS_SetVelocity(0, 0),
    BS_PlaySoundOrDefault(60),
    BS_PlaySoundOrDefault(42),
    BS_AdvanceAttackOutcome(),
    BS_AdvanceAttackOutcome(),
    BS_ScrollBgUp(1),
    BS_WaitFrames(1),
    BS_ScrollBgDown(1),
    BS_ScrollBgDown(1),
    BS_WaitFrames(1),
    BS_ScrollBgUp(1),
    BS_WaitFrames(6),
    BS_SetVelocity(0, -4),
    BS_WaitFrames(30),
    BS_GotoIfContextLow(49),
    BS_StatusEffect(BSSTATUS_PaletteFlash, 1, 0),
  BS_Label(49),
    BS_AdvanceAttackOutcome(),
    BS_AdvanceAttackOutcome(),
    BS_AdvanceAttackOutcome(),
    BS_GotoIfContextLow(50),
    BS_HideObject(),
    BS_WaitFrames(10),
    BS_StatusEffect(BSSTATUS_PaletteFlash, 2, 0),
  BS_Label(50),
    BS_End(),
};
