// Cancels any magical ailments affecting the party.
const u8 g_abSpecialHarryRepariforsScript[] = {
    BS_SetBgPriority(0, 1),
    BS_WaitFrames(2),
    BS_QueueScanlineEffect(0),
    BS_DarkenScreenPalette(),
    BS_WaitFrames(20),
    BS_PlaySound(153),
    BS_SetEffectTimers(1, 0, 0, 0, 0, 30, 0, 0, 0, 0),
    BS_SetAlphaBlend(16, 16),
    BS_SetBgPaletteColors(21, 0, 14, 1),
    BS_WaitFrames(1),
    BS_LoadBgEffect(0, 21, 14),
    BS_WaitFrames(1),
    BS_LoadBgEffect(0, 22, 14),
    BS_WaitFrames(1),
    BS_LoadBgEffect(0, 23, 14),
    BS_WaitFrames(1),
    BS_LoadBgEffect(0, 24, 14),
    BS_WaitFrames(1),
    BS_LoadBgEffect(0, 25, 14),
    BS_WaitFrames(1),
    BS_LoadBgEffect(0, 26, 14),
    BS_WaitFrames(1),
    BS_LoadBgEffect(0, 27, 14),
    BS_WaitFrames(1),
    BS_LoadBgEffect(0, 28, 14),
    BS_WaitFrames(1),
    BS_LoadBgEffect(0, 29, 14),
    BS_WaitFrames(1),
    BS_LoadBgEffect(0, 30, 14),
    BS_WaitFrames(1),
    BS_LoadBgEffect(0, 31, 14),
    BS_WaitFrames(1),
    BS_LoadBgEffect(0, 32, 14),
    BS_WaitFrames(1),
    BS_LoadBgEffect(0, 33, 14),
    BS_WaitFrames(1),
    BS_LoadBgEffect(0, 34, 14),
    BS_WaitFrames(1),
    BS_LoadBgEffect(0, 35, 14),
    BS_WaitFrames(1),
    BS_LoadBgEffect(0, 36, 14),
    BS_WaitFrames(1),
    BS_LoadBgEffect(0, 37, 14),
    BS_WaitFrames(1),
    BS_LoadBgEffect(0, 38, 14),
    BS_WaitFrames(1),
    BS_LoadBgEffect(0, 39, 14),
    BS_WaitFrames(1),
    BS_LoadBgEffect(0, 40, 14),
    BS_WaitFrames(1),
    BS_LoadBgEffect(0, 41, 14),
    BS_WaitFrames(1),
    BS_LoadBgEffect(0, 42, 14),
    BS_WaitFrames(1),
    BS_LoadBgEffect(0, 43, 14),
    BS_WaitFrames(1),
    BS_LoadBgEffect(0, 44, 14),
    BS_WaitFrames(1),
    BS_LoadBgEffect(0, 45, 14),
    BS_WaitFrames(1),
    BS_LoadBgEffect(0, 46, 14),
    BS_WaitFrames(1),
    BS_LoadBgEffect(0, 47, 14),
    BS_WaitFrames(1),
    BS_LoadBgEffect(0, 48, 14),
    BS_WaitFrames(1),
    BS_LoadBgEffect(0, 49, 14),
    BS_WaitFrames(1),
    BS_LoadBgEffect(0, 50, 14),
    BS_WaitFrames(1),
    BS_LoadBgEffect(0, 51, 14),
    BS_WaitFrames(1),
    BS_LoadBgEffect(0, 52, 14),
    BS_WaitFrames(1),
    BS_LoadBgEffect(0, 53, 14),
    BS_WaitFrames(1),
    BS_LoadBgEffect(0, 54, 14),
    BS_WaitFrames(1),
    BS_LoadBgEffect(0, 55, 14),
    BS_WaitFrames(1),
    BS_LoadBgEffect(0, 56, 14),
    BS_WaitFrames(1),
    BS_ResetBgState(0),
    BS_SetBgPriority(0, 0),
    BS_SetEffectTimers(0, 0, 0, 0, 0, 63, 0, 0, 0, 0),
    BS_SetAlphaBlend(16, 0),
    BS_SelectFirstAlly(),
    BS_StatusEffect(BSSTATUS_CureAilments, 0, 0),
    BS_SelectNextAlly(),
    BS_GotoIfLocalBEqual(1, 38),
    BS_StatusEffect(BSSTATUS_CureAilments, 0, 0),
    BS_SelectNextAlly(),
    BS_GotoIfLocalBEqual(1, 38),
    BS_StatusEffect(BSSTATUS_CureAilments, 0, 0),
  BS_Label(38),
    BS_WaitFrames(1),
    BS_RestoreScreenPalette(),
    BS_WaitFrames(10),
    BS_AdvanceAttackOutcome(),
    BS_End(),
};
