// Throws a stink pellet that paralyzes one enemy.
const u8 g_abSpecialRonStinkPelletScript[] = {
    BS_SetOamPriority(1),
    BS_SetDepthBiasMax(),
    BS_SnapToCaster(0),
    BS_MoveBy(0, -32),
    BS_SetObjectAnim(44, 0),
    BS_StartOrbitMotion(5, 0),
    BS_PlaySound(122),
    BS_WaitFrames(1),
    BS_ShowObject(),
    BS_MoveTo(-8, -16, 32, 0, 0),
    BS_WaitFrames(5),
    BS_SetDepthBiasZero(),
    BS_WaitForFieldClear(),
    BS_StartOrbitMotion(13, 0),
    BS_PlaySound(123),
    BS_SetObjectAnimFromTable2AndPalette(31, 0),
    BS_StatusEffect(BSSTATUS_Paralyze99, 0, 0),
    BS_WaitForCounter(),
    BS_HideObject(),
    BS_WaitFrames(10),
    BS_AdvanceAttackOutcome(),
    BS_AdvanceAttackOutcome(),
    BS_End(),
};
