// Grants one party member all spell abilities.
const u8 g_abSpecialHarryUltimateMpScript[] = {
    BS_SetOamPriority(1),
    BS_WaitFrames(2),
    BS_DarkenScreenPalette(),
    BS_WaitFrames(2),
    BS_SetBgPriority(1, 2),
    BS_SetEnemiesOamPriority(2),
    BS_SetAlliesOamPriority(2),
    BS_SetTargetOamPriority(1),
    BS_MoveFighterTo(120, 80, 20),
    BS_QueueScanlineEffect(0),
    BS_WaitFrames(1),
    BS_WaitFrames(20),
    BS_StatusEffect(BSSTATUS_ToggleUltimateVisual, 0, 0),
    BS_SpawnEffectDetached(36),
    BS_WaitFrames(210),
    BS_StatusEffect(BSSTATUS_ToggleUltimateVisual, 1, 0),
    BS_WaitFrames(20),
    BS_MoveFighterToSlotPosition(20),
    BS_WaitFrames(20),
    BS_RestoreScreenPalette(),
    BS_SetEnemiesOamPriority(1),
    BS_SetAlliesOamPriority(1),
    BS_AdvanceAttackOutcome(),
    BS_End(),
};
