// Increases the whole party's physical defense.
const u8 g_abSpecialHarryGirdingAllScript[] = {
    BS_ClearAnimFlag(),
    BS_WaitFrames(2),
    BS_DarkenScreenPalette(),
    BS_WaitFrames(20),
    BS_SetBgPriority(1, 2),
    BS_SetEnemiesOamPriority(2),
    BS_SetAlliesOamPriority(2),
    BS_QueueScanlineEffect(0),
    BS_WaitFrames(15),
    BS_PlaySoundEffect(35),
    BS_SpawnEffectDetached(36),
    BS_IncrementLocal(0),
    BS_WaitFrames(30),
    BS_WaitFrames(45),
    BS_WaitFrames(10),
    BS_WaitFrames(30),
    BS_WaitFrames(1),
    BS_SetOamPriority(1),
    BS_SetDepthBiasZero(),
    BS_TeleportTo(120, 80),
    BS_SetObjectAnim(35, 0),
    BS_WaitFrames(1),
    BS_SetAnimFlag(),
    BS_ShowObject(),
    BS_WaitFrames(50),
    BS_SetDepthBiasMax(),
    BS_SetLocal(0, 4),
    BS_SelectFirstAlly(),
    BS_SpawnEffectDetached(36),
    BS_WaitFrames(3),
    BS_SelectNextAlly(),
    BS_GotoIfLocalBEqual(1, 38),
    BS_SpawnEffectDetached(36),
    BS_WaitFrames(3),
    BS_SelectNextAlly(),
    BS_GotoIfLocalBEqual(1, 38),
    BS_SpawnEffectDetached(36),
  BS_Label(38),
    BS_WaitFrames(50),
    BS_EnableSemiTransparency(),
    BS_StartAlphaFade(15),
    BS_WaitFrames(50),
    BS_SetEnemiesOamPriority(1),
    BS_SetAlliesOamPriority(1),
    BS_RestoreScreenPalette(),
    BS_WaitFrames(20),
    BS_HideObject(),
    BS_AdvanceAttackOutcome(),
    BS_End(),
};
