// Bludgers rain down on all opponents for low damage.
const u8 g_abSpecialHarryBludgersScript[] = {
    BS_GotoLocalIndexedLabel(0, 49, 49, 50, 0, 0, 0, 0),
    BS_WaitFrames(1),
  BS_Label(49),
    BS_GotoIfLocalANotEqual(0, 70),
    BS_SetLocal(0, 1),
    BS_SpawnEffect(41),
    BS_WaitFrames(3),
  BS_Label(70),
    BS_TeleportTo(60, 1),
    BS_JitterPosition(60, 1),
    BS_SetDepthBias(128),
    BS_SetObjectAnim(41, 0),
    BS_WaitFrames(1),
    BS_ShowObject(),
    BS_SetVelocity(0, 8),
    BS_WaitFrames(6),
    BS_SetLocal(0, 0),
    BS_GotoIfLocalBEqual(15, 81),
    BS_SpawnEffect(41),
    BS_SetLocalRandom(0, 3),
    BS_GotoLocalIndexedLabel(0, 71, 72, 73, 74, 0, 0, 0),
  BS_Label(71),
    BS_WaitFrames(6),
    BS_Goto(38),
  BS_Label(72),
    BS_WaitFrames(5),
    BS_Goto(38),
  BS_Label(73),
    BS_WaitFrames(4),
    BS_Goto(38),
  BS_Label(74),
    BS_WaitFrames(3),
  BS_Label(38),
    BS_SetVelocity(0, 0),
    BS_PlaySound(140),
    BS_SetObjectAnimFromTable2AndPalette(26, 0),
    BS_SetDepthBias(129),
    BS_WaitForCounter(),
    BS_End(),
  BS_Label(81),
    BS_AdvanceAttackOutcome(),
    BS_AdvanceAttackOutcome(),
    BS_AdvanceAttackOutcome(),
    BS_AdvanceAttackOutcome(),
    BS_End(),
  BS_Label(50),
    BS_SetDepthBias(254),
    BS_TeleportTo(60, 1),
    BS_JitterPosition(60, 1),
    BS_SetObjectAnimFromTable2AndPalette(25, 0),
    BS_WaitFrames(1),
    BS_ShowObject(),
    BS_SetVelocity(0, 5),
    BS_WaitFrames(6),
    BS_SetLocal(0, 1),
    BS_GotoIfLocalBEqual(15, 80),
    BS_SpawnEffect(41),
    BS_SetLocalRandom(0, 3),
    BS_GotoLocalIndexedLabel(0, 75, 76, 77, 78, 0, 0, 0),
  BS_Label(75),
    BS_WaitFrames(6),
    BS_Goto(79),
  BS_Label(76),
    BS_WaitFrames(5),
    BS_Goto(79),
  BS_Label(77),
    BS_WaitFrames(4),
    BS_Goto(79),
  BS_Label(78),
    BS_WaitFrames(3),
  BS_Label(79),
    BS_SetVelocity(0, 0),
    BS_PlaySound(140),
    BS_SetObjectAnimFromTable2AndPalette(27, 0),
    BS_SetDepthBias(255),
    BS_WaitForCounter(),
    BS_End(),
  BS_Label(80),
    BS_End(),
};
