// Restores the whole party's Stamina Points to maximum.
const u8 g_abSpecialHarryReplenishSpScript[] = {
    BS_GotoIfLocalANotEqual(0, 38),
    BS_SetAlphaBlend(0, 16),
    BS_SetEffectTimers(1, 0, 0, 0, 0, 63, 0, 0, 0, 0),
    BS_QueueScanlineEffect(0),
    BS_WaitFrames(1),
    BS_LoadBgEffect(0, 5, 14),
    BS_SetBgPaletteColorsAdjust(5, 0, 14, 1, 15),
    BS_SetBgPriority(0, 1),
    BS_SetBgPriority(1, 2),
    BS_SetEnemiesOamPriority(2),
    BS_StartFadeCounter(2, 0),
    BS_PlaySound(146),
    BS_WaitFrames(30),
    BS_SpawnEffect(40),
    BS_WaitFrames(2),
    BS_SpawnEffect(40),
    BS_WaitFrames(2),
    BS_SpawnEffect(40),
    BS_WaitFrames(2),
    BS_SpawnEffect(40),
    BS_WaitFrames(2),
    BS_SpawnEffect(40),
    BS_WaitFrames(2),
    BS_SpawnEffect(40),
    BS_WaitFrames(2),
    BS_SpawnEffect(40),
    BS_WaitFrames(2),
    BS_SpawnEffect(40),
    BS_WaitFrames(2),
    BS_SpawnEffect(40),
    BS_WaitFrames(2),
    BS_SpawnEffect(40),
    BS_WaitFrames(2),
    BS_SpawnEffect(40),
    BS_WaitFrames(2),
    BS_SpawnEffect(40),
    BS_WaitFrames(2),
    BS_SpawnEffect(40),
    BS_WaitFrames(2),
    BS_SpawnEffect(40),
    BS_WaitFrames(2),
    BS_SpawnEffect(40),
    BS_WaitFrames(11),
    BS_StartAlphaFade(15),
    BS_WaitFrames(30),
    BS_UnmuteMusic(),
    BS_ResetBgState(0),
    BS_SetEnemiesOamPriority(1),
    BS_WaitFrames(2),
    BS_SetEffectTimers(0, 0, 0, 0, 0, 63, 0, 0, 0, 0),
    BS_SetBgPriority(0, 0),
    BS_SetBgPriority(1, 1),
    BS_StatusEffect(BSSTATUS_ReplenishPartySp, 0, 0),
    BS_AdvanceAttackOutcome(),
    BS_End(),
  BS_Label(38),
    BS_PlaySound(147),
    BS_TeleportTo(192, 112),
    BS_JitterPosition(70, 20),
    BS_SetObjectAnim(40, 0),
    BS_SetOamPriority(1),
    BS_SetDepthBiasZero(),
    BS_WaitFrames(1),
    BS_ShowObject(),
    BS_SetLocalRandom(0, 5),
    BS_GotoLocalIndexedLabel(0, 49, 50, 51, 52, 53, 54, 0),
  BS_Label(49),
    BS_SetVelocity(0, 254),
    BS_Goto(70),
  BS_Label(50),
    BS_SetVelocity(0, 253),
    BS_Goto(70),
  BS_Label(51),
    BS_SetVelocity(0, 252),
    BS_Goto(70),
  BS_Label(52),
    BS_SetVelocity(0, 251),
    BS_Goto(70),
  BS_Label(53),
    BS_SetVelocity(0, 250),
    BS_Goto(70),
  BS_Label(54),
    BS_SetVelocity(0, 249),
  BS_Label(70),
    BS_WaitFrames(30),
    BS_WaitFrames(30),
    BS_End(),
};
