// Boosts the party's defense.
const u8 g_abSpecialHermioneBeMoreCarefulScript[] = {
    BS_GotoIfLocalAEqual(1, 38),
    BS_SetOamPriority(1),
    BS_SetDepthBiasMax(),
    BS_TeleportToSlotPosition(0),
    BS_SetObjectAnim(49, 0),
    BS_WaitFrames(1),
    BS_ShowObject(),
    BS_WaitFrames(30),
    BS_SpawnEffect(49),
    BS_WaitFrames(60),
    BS_StatusEffect(BSSTATUS_DefenseBoost, 0, 0),
    BS_AdvanceAttackOutcome(),
    BS_End(),
  BS_Label(38),
    BS_SetAlphaBlend(0, 16),
    BS_SetEffectTimers(0, 0, 0, 0, 0, 63, 0, 0, 0, 0),
    BS_QueueScanlineEffect(0),
    BS_EnableSemiTransparency(),
    BS_TeleportToSlotPosition(2),
    BS_SetObjectAnimFromTable2AndPalette(32, 0),
    BS_StartFadeCounter(1, 0),
    BS_WaitFrames(1),
    BS_ShowObject(),
    BS_PlaySound(126),
    BS_WaitForCounter(),
    BS_StartAlphaFade(15),
    BS_WaitFrames(16),
    BS_End(),
};
