// Enhanced Stink Pellet; paralyzes multiple targets.
const u8 g_abSpecialRonStinkPellet2Script[] = {
    BS_GotoIfLocalANotEqual(0, 50),
    BS_SelectFirstLiveEnemy(),
    BS_SpawnEffect(45),
    BS_WaitFrames(55),
    BS_SelectFirstLiveEnemy(),
    BS_StatusEffect(BSSTATUS_Paralyze99, 0, 0),
    BS_SelectNextLiveEnemy(),
    BS_GotoIfLocalBEqual(1, 51),
    BS_StatusEffect(BSSTATUS_Paralyze99, 0, 0),
    BS_SelectNextLiveEnemy(),
    BS_GotoIfLocalBEqual(1, 51),
    BS_StatusEffect(BSSTATUS_Paralyze99, 0, 0),
  BS_Label(51),
    BS_AdvanceAttackOutcome(),
    BS_End(),
  BS_Label(50),
    BS_SetOamPriority(1),
    BS_SetDepthBiasMax(),
    BS_SnapToCaster(0),
    BS_MoveBy(0, -32),
    BS_MoveTo(-8, -16, 32, 0, 0),
    BS_SetObjectAnim(44, 0),
    BS_StartOrbitMotion(5, 0),
    BS_PlaySound(122),
    BS_WaitFrames(1),
    BS_SelectNextLiveEnemy(),
    BS_GotoIfLocalBEqual(1, 38),
    BS_SpawnEffect(45),
  BS_Label(38),
    BS_ShowObject(),
    BS_WaitFrames(5),
    BS_SetDepthBiasZero(),
    BS_WaitForFieldClear(),
    BS_StartOrbitMotion(13, 0),
    BS_PlaySound(123),
    BS_SetObjectAnimFromTable2AndPalette(31, 0),
    BS_WaitForCounter(),
    BS_End(),
};
