// Removes any jinx affecting one party member.
const u8 g_abSpecialHarryRemoveJinxScript[] = {
    BS_GotoIfLocalAEqual(0, 39),
    BS_SetLocalRandom(0, 3),
    BS_GotoLocalIndexedLabel(0, 49, 50, 51, 52, 0, 0, 0),
  BS_Label(49),
    BS_TeleportTo(192, 90),
    BS_JitterPosition(60, 10),
    BS_SetOamPriority(1),
    BS_SetDepthBiasMax(),
    BS_SetObjectAnimFromTable2AndPalette(36, 0),
    BS_PlaySound(150),
    BS_WaitFrames(1),
    BS_ShowObject(),
    BS_WaitFrames(20),
    BS_SetVelocity(0, 255),
    BS_Goto(70),
  BS_Label(50),
    BS_TeleportTo(192, 115),
    BS_JitterPosition(70, 5),
    BS_SetOamPriority(1),
    BS_SetDepthBiasZero(),
    BS_SetObjectAnimFromTable2AndPalette(35, 0),
    BS_PlaySound(150),
    BS_WaitFrames(1),
    BS_ShowObject(),
    BS_WaitFrames(20),
    BS_SetVelocity(0, 254),
    BS_Goto(70),
  BS_Label(51),
    BS_TeleportTo(192, 90),
    BS_JitterPosition(60, 10),
    BS_SetOamPriority(1),
    BS_SetDepthBiasMax(),
    BS_SetObjectAnimFromTable2AndPalette(34, 0),
    BS_PlaySound(150),
    BS_WaitFrames(1),
    BS_ShowObject(),
    BS_WaitFrames(20),
    BS_SetVelocity(0, 255),
    BS_Goto(70),
  BS_Label(52),
    BS_TeleportTo(192, 115),
    BS_JitterPosition(70, 5),
    BS_SetOamPriority(1),
    BS_SetDepthBiasZero(),
    BS_SetObjectAnimFromTable2AndPalette(33, 0),
    BS_PlaySound(150),
    BS_WaitFrames(1),
    BS_ShowObject(),
    BS_WaitFrames(20),
    BS_SetVelocity(0, 254),
    BS_Goto(70),
  BS_Label(70),
    BS_WaitFrames(80),
    BS_End(),
  BS_Label(39),
    BS_SpawnEffect(52),
    BS_WaitFrames(2),
    BS_SpawnEffect(52),
    BS_WaitFrames(5),
    BS_SpawnEffect(52),
    BS_WaitFrames(2),
    BS_SpawnEffect(52),
    BS_WaitFrames(5),
    BS_SpawnEffect(52),
    BS_WaitFrames(2),
    BS_SpawnEffect(52),
    BS_WaitFrames(5),
    BS_SpawnEffect(52),
    BS_WaitFrames(2),
    BS_SpawnEffect(52),
    BS_WaitFrames(5),
    BS_SpawnEffect(52),
    BS_WaitFrames(2),
    BS_SpawnEffect(52),
    BS_WaitFrames(5),
    BS_SpawnEffect(52),
    BS_WaitFrames(2),
    BS_SpawnEffect(52),
    BS_WaitFrames(5),
    BS_SpawnEffect(52),
    BS_WaitFrames(2),
    BS_SpawnEffect(52),
    BS_WaitFrames(5),
    BS_SpawnEffect(52),
    BS_WaitFrames(2),
    BS_SpawnEffect(52),
    BS_WaitFrames(5),
    BS_SpawnEffect(52),
    BS_WaitFrames(2),
    BS_SpawnEffect(52),
    BS_WaitFrames(5),
    BS_SpawnEffect(52),
    BS_WaitFrames(2),
    BS_SpawnEffect(52),
    BS_WaitFrames(5),
    BS_SpawnEffect(52),
    BS_WaitFrames(2),
    BS_SpawnEffect(52),
    BS_WaitFrames(5),
    BS_WaitFrames(60),
    BS_SelectFirstAlly(),
    BS_StatusEffect(BSSTATUS_CureAilments, 0, 0),
    BS_TeleportToSlotPosition(0),
    BS_SetObjectAnim(52, 0),
    BS_PlaySound(151),
    BS_WaitFrames(1),
    BS_ShowObject(),
    BS_WaitForCounter(),
    BS_HideObject(),
    BS_SelectNextAlly(),
    BS_GotoIfLocalBEqual(1, 38),
    BS_StatusEffect(BSSTATUS_CureAilments, 0, 0),
    BS_TeleportToSlotPosition(0),
    BS_SetObjectAnim(52, 0),
    BS_PlaySound(151),
    BS_WaitFrames(1),
    BS_ShowObject(),
    BS_WaitForCounter(),
    BS_HideObject(),
    BS_SelectNextAlly(),
    BS_GotoIfLocalBEqual(1, 38),
    BS_StatusEffect(BSSTATUS_CureAilments, 0, 0),
    BS_TeleportToSlotPosition(0),
    BS_SetObjectAnim(52, 0),
    BS_PlaySound(151),
    BS_WaitFrames(1),
    BS_ShowObject(),
    BS_WaitForCounter(),
    BS_HideObject(),
  BS_Label(38),
    BS_AdvanceAttackOutcome(),
    BS_End(),
};
