// Heavy damage to all opponents, minor damage to the party.
const u8 g_abSpecialHarryCrackerJinxScript[] = {
    BS_SetOamPriority(1),
    BS_SetDepthBias(128),
    BS_GotoIfLocalANotEqual(0, 5),
    BS_SetBgPriority(0, 1),
    BS_SetAlphaBlend(0, 16),
    BS_SetEffectTimers(1, 0, 0, 0, 0, 63, 0, 0, 0, 0),
    BS_QueueScanlineEffect(0),
    BS_WaitFrames(3),
    BS_LoadBgEffect(0, 3, 15),
    BS_SetBgPaletteColors(3, 0, 15, 1),
    BS_StartFadeCounter(2, 0),
    BS_WaitFrames(40),
    BS_SetEffectTimers(0, 0, 0, 0, 0, 63, 0, 0, 0, 0),
    BS_QueueScanlineEffect(2),
    BS_TeleportTo(106, 0),
    BS_SetObjectAnim(10, 0),
    BS_WaitFrames(1),
    BS_ShowObject(),
    BS_SetVelocity(0, 2),
    BS_WaitFrames(2),
    BS_SetVelocity(0, 4),
    BS_WaitFrames(2),
    BS_SetVelocity(0, 8),
    BS_WaitFrames(2),
    BS_SetVelocity(0, 11),
    BS_WaitFrames(4),
    BS_SetVelocity(0, 0),
    BS_PlaySound(133),
    BS_SetObjectAnim(10, 4),
    BS_WaitFrames(9),
    BS_SetObjectAnim(10, 0),
    BS_SpawnEffect(10),
    BS_WaitFrames(80),
    BS_SetObjectAnim(10, 8),
    BS_WaitFrames(19),
    BS_PlaySound(135),
    BS_HideObject(),
    BS_SetBgPaletteColors(57, 0, 14, 1),
    BS_WaitFrames(2),
    BS_SetBgPriority(1, 0),
    BS_LoadBgEffect(1, 57, 14),
    BS_WaitFrames(1),
    BS_LoadBgEffect(1, 58, 14),
    BS_WaitFrames(1),
    BS_LoadBgEffect(1, 59, 14),
    BS_WaitFrames(1),
    BS_LoadBgEffect(1, 60, 14),
    BS_WaitFrames(1),
    BS_LoadBgEffect(1, 61, 14),
    BS_WaitFrames(1),
    BS_LoadBgEffect(1, 62, 14),
    BS_WaitFrames(1),
    BS_LoadBgEffect(1, 63, 14),
    BS_WaitFrames(1),
    BS_LoadBgEffect(1, 64, 14),
    BS_WaitFrames(1),
    BS_LoadBgEffect(1, 65, 14),
    BS_WaitFrames(1),
    BS_LoadBgEffect(1, 66, 14),
    BS_WaitFrames(1),
    BS_LoadBgEffect(1, 67, 14),
    BS_WaitFrames(1),
    BS_LoadBgEffect(1, 68, 14),
    BS_WaitFrames(1),
    BS_LoadBgEffect(1, 69, 14),
    BS_WaitFrames(1),
    BS_LoadBgEffect(1, 70, 14),
    BS_WaitFrames(1),
    BS_LoadBgEffect(1, 71, 14),
    BS_WaitFrames(1),
    BS_LoadBgEffect(1, 72, 14),
    BS_WaitFrames(1),
    BS_LoadBgEffect(1, 73, 14),
    BS_WaitFrames(1),
    BS_LoadBgEffect(1, 74, 14),
    BS_WaitFrames(1),
    BS_LoadBgEffect(1, 75, 14),
    BS_WaitFrames(1),
    BS_LoadBgEffect(1, 76, 14),
    BS_WaitFrames(1),
    BS_LoadBgEffect(1, 77, 14),
    BS_WaitFrames(1),
    BS_LoadBgEffect(1, 78, 14),
    BS_WaitFrames(1),
    BS_LoadBgEffect(1, 79, 14),
    BS_WaitFrames(1),
    BS_LoadBgEffect(1, 80, 14),
    BS_WaitFrames(1),
    BS_LoadBgEffect(1, 81, 14),
    BS_WaitFrames(1),
    BS_LoadBgEffect(1, 82, 14),
    BS_WaitFrames(1),
    BS_LoadBgEffect(1, 83, 14),
    BS_WaitFrames(1),
    BS_LoadBgEffect(1, 84, 14),
    BS_WaitFrames(1),
    BS_LoadBgEffect(1, 85, 14),
    BS_WaitFrames(1),
    BS_LoadBgEffect(1, 86, 14),
    BS_WaitFrames(1),
    BS_LoadBgEffect(1, 87, 14),
    BS_WaitFrames(1),
    BS_LoadBgEffect(1, 88, 14),
    BS_WaitFrames(1),
    BS_LoadBgEffect(1, 89, 14),
    BS_WaitFrames(1),
    BS_LoadBgEffect(1, 90, 14),
    BS_WaitFrames(1),
    BS_LoadBgEffect(1, 91, 14),
    BS_WaitFrames(1),
    BS_LoadBgEffect(1, 92, 14),
    BS_WaitFrames(1),
    BS_LoadBgEffect(1, 93, 14),
    BS_WaitFrames(1),
    BS_LoadBgEffect(1, 94, 14),
    BS_WaitFrames(1),
    BS_LoadBgEffect(1, 95, 14),
    BS_WaitFrames(1),
    BS_LoadBgEffect(1, 96, 14),
    BS_WaitFrames(1),
    BS_LoadBgEffect(1, 97, 14),
    BS_WaitFrames(1),
    BS_LoadBgEffect(1, 98, 14),
    BS_WaitFrames(1),
    BS_LoadBgEffect(1, 99, 14),
    BS_WaitFrames(1),
    BS_LoadBgEffect(1, 100, 14),
    BS_WaitFrames(1),
    BS_LoadBgEffect(1, 101, 14),
    BS_WaitFrames(1),
    BS_LoadBgEffect(1, 102, 14),
    BS_WaitFrames(1),
    BS_LoadBgEffect(0, 3, 15),
    BS_SetBgPaletteColors(3, 0, 15, 1),
    BS_SetBgPriority(1, 1),
    BS_ResetBgState(1),
    BS_WaitFrames(1),
    BS_QueueScanlineEffect(0),
    BS_SetEffectTimers(1, 0, 0, 0, 0, 63, 0, 0, 0, 0),
    BS_StartAlphaFade(15),
    BS_WaitFrames(40),
    BS_SetBgPriority(0, 0),
    BS_ResetBgState(0),
    BS_SetEffectTimers(0, 0, 0, 0, 0, 63, 0, 0, 0, 0),
    BS_AdvanceAttackOutcome(),
    BS_AdvanceAttackOutcome(),
    BS_AdvanceAttackOutcome(),
    BS_AdvanceAttackOutcome(),
    BS_AdvanceAttackOutcome(),
    BS_End(),
  BS_Label(5),
    BS_TeleportTo(104, 0),
    BS_JitterPosition(40, 1),
    BS_GotoLocalIndexedLabel(0, 5, 7, 8, 9, 10, 7, 0),
  BS_Label(8),
    BS_SetEffectPalette(2),
    BS_Goto(7),
  BS_Label(9),
    BS_SetEffectPalette(3),
    BS_Goto(7),
  BS_Label(10),
    BS_SetEffectPalette(4),
    BS_Goto(7),
  BS_Label(7),
    BS_WaitFrames(6),
    BS_GotoIfLocalAEqual(5, 6),
    BS_SpawnEffect(10),
  BS_Label(6),
    BS_SetObjectAnimFromTable2(0, 0),
    BS_WaitFrames(1),
    BS_ShowObject(),
    BS_SetVelocity(0, 2),
    BS_WaitFrames(2),
    BS_SetVelocity(0, 4),
    BS_WaitFrames(2),
    BS_SetVelocity(0, 8),
    BS_WaitFrames(2),
    BS_SetVelocity(0, 11),
    BS_GotoLocalIndexedLabel(0, 0, 12, 13, 14, 15, 16, 0),
  BS_Label(12),
    BS_WaitFrames(3),
    BS_PlaySound(136),
    BS_SetVelocity(0, 0),
    BS_SetObjectAnimFromTable2(0, 4),
    BS_WaitFrames(9),
    BS_SetObjectAnimFromTable2(0, 0),
    BS_WaitFrames(25),
    BS_PlaySound(171),
    BS_Goto(11),
  BS_Label(13),
    BS_WaitFrames(2),
    BS_PlaySound(136),
    BS_SetVelocity(0, 0),
    BS_SetObjectAnimFromTable2(0, 4),
    BS_WaitFrames(9),
    BS_SetObjectAnimFromTable2(0, 0),
    BS_WaitFrames(16),
    BS_PlaySound(173),
    BS_Goto(11),
  BS_Label(14),
    BS_WaitFrames(4),
    BS_PlaySound(136),
    BS_SetVelocity(0, 0),
    BS_SetObjectAnimFromTable2(0, 4),
    BS_WaitFrames(9),
    BS_SetObjectAnimFromTable2(0, 0),
    BS_WaitFrames(8),
    BS_PlaySound(175),
    BS_Goto(11),
  BS_Label(15),
    BS_WaitFrames(2),
    BS_PlaySound(136),
    BS_SetVelocity(0, 0),
    BS_SetObjectAnimFromTable2(0, 4),
    BS_WaitFrames(9),
    BS_SetObjectAnimFromTable2(0, 0),
    BS_WaitFrames(2),
    BS_Goto(11),
  BS_Label(16),
    BS_WaitFrames(4),
    BS_PlaySound(136),
    BS_SetVelocity(0, 0),
    BS_SetObjectAnimFromTable2(0, 4),
    BS_WaitFrames(9),
    BS_SetObjectAnimFromTable2(0, 0),
  BS_Label(11),
    BS_WaitFrames(50),
    BS_End(),
};
