// Blows one opponent off-screen.
const u8 g_abSpecialHarryTempestJinxScript[] = {
    BS_GotoIfLocalAEqual(1, 1),
    BS_RampBlendUp(),
    BS_PlaySound(143),
    BS_PlaySound(68),
    BS_LoadBgEffect(1, 0, 14),
    BS_LoadBgEffect(0, 1, 14),
    BS_SetBgPaletteColors(0, 0, 14, 1),
    BS_SetBgPaletteColors(0, 1, 15, 1),
    BS_QueueScanlineEffect(1),
    BS_TeleportTo(220, 70),
    BS_RampBlendDown(),
    BS_SpawnEffectDetached(5),
    BS_SpawnEffectAtSelf(6),
    BS_WaitFrames(15),
    BS_SpawnEffectAtSelf(7),
    BS_WaitFrames(15),
    BS_SpawnEffectAtSelf(6),
    BS_WaitFrames(15),
    BS_SpawnEffectAtSelf(7),
    BS_WaitFrames(5),
    BS_PlaySound(69),
    BS_SetBgEffectId(2),
    BS_WaitFrames(5),
    BS_SetBgEffectId(0),
    BS_SpawnEffectAtSelf(6),
    BS_WaitFrames(20),
    BS_PlaySound(69),
    BS_SetBgEffectId(2),
    BS_WaitFrames(2),
    BS_SetBgEffectId(0),
    BS_WaitFrames(3),
    BS_PlaySound(69),
    BS_SetBgEffectId(2),
    BS_WaitFrames(2),
    BS_SetBgEffectId(0),
    BS_WaitFrames(40),
    BS_PlaySound(69),
    BS_SetBgEffectId(2),
    BS_WaitFrames(3),
    BS_SetBgEffectId(0),
    BS_ResetBgState(1),
    BS_ResetBgState(0),
    BS_UnmuteMusic(),
    BS_WaitFrames(1),
    BS_KillTarget(),
    BS_AdvanceAttackOutcome(),
    BS_End(),
  BS_Label(1),
    BS_WaitFrames(45),
    BS_SetTargetVelocityScaled(224, 0),
    BS_WaitFrames(1),
    BS_SetTargetVelocityScaled(32, 0),
    BS_WaitFrames(1),
    BS_SetTargetVelocityScaled(224, 0),
    BS_WaitFrames(1),
    BS_SetTargetVelocityScaled(32, 0),
    BS_WaitFrames(1),
    BS_SetTargetVelocityScaled(224, 0),
    BS_WaitFrames(1),
    BS_SetTargetVelocityScaled(32, 0),
    BS_WaitFrames(1),
    BS_SetTargetVelocityScaled(224, 0),
    BS_WaitFrames(1),
    BS_SetTargetVelocityScaled(32, 0),
    BS_WaitFrames(1),
    BS_SetTargetVelocityScaled(224, 0),
    BS_WaitFrames(1),
    BS_SetTargetVelocityScaled(32, 0),
    BS_WaitFrames(1),
    BS_SetTargetVelocityScaled(192, 0),
    BS_WaitFrames(2),
    BS_SetTargetVelocityScaled(64, 0),
    BS_WaitFrames(2),
    BS_SetTargetVelocityScaled(192, 0),
    BS_WaitFrames(2),
    BS_SetTargetVelocityScaled(64, 0),
    BS_WaitFrames(2),
    BS_SetTargetVelocityScaled(192, 0),
    BS_WaitFrames(2),
    BS_SetTargetVelocityScaled(64, 0),
    BS_WaitFrames(2),
    BS_SetTargetVelocityScaled(192, 0),
    BS_WaitFrames(2),
    BS_SetTargetVelocityScaled(64, 0),
    BS_WaitFrames(2),
    BS_SetTargetVelocityScaled(192, 0),
    BS_WaitFrames(2),
    BS_SetTargetVelocityScaled(64, 0),
    BS_WaitFrames(2),
    BS_SetTargetVelocityScaled(128, 224),
    BS_End(),
};
