// Chance to paralyze the target on a successful attack (Hinkypunk).
const u8 g_abSpecialMonsterHinkypunkParalyzeScript[] = {
    BS_Unk35(1, 1, 11),
    BS_Unk35(1, 2, 12),
    BS_Unk35(1, 3, 13),
    BS_SnapToCaster(4),
    BS_SetObjectAnim(57, 0),
    BS_SetOamPriority(0),
    BS_ShowObject(),
    BS_PlaySound(72),
    BS_MoveTo(0, 0, 10, 0, 2),
    BS_SetOamPriority(2),
    BS_StatusEffect(BSSTATUS_SpawnEffectC, 1, 1),
    BS_StatusEffect(BSSTATUS_SpawnEffectC, 1, 2),
    BS_StatusEffect(BSSTATUS_SpawnEffectC, 1, 3),
    BS_WaitForFieldClear(),
    BS_HideObject(),
    BS_SetOamPriority(0),
    BS_AdvanceAttackOutcome(),
    BS_AdvanceAttackOutcome(),
    BS_GotoIfContextLow(38),
    BS_StatusEffect(BSSTATUS_ParalyzeMonsterChance, 25, 25),
  BS_Label(38),
    BS_StatusEffect(BSSTATUS_SpawnEffectB, 1, 1),
    BS_StatusEffect(BSSTATUS_SpawnEffectB, 1, 2),
    BS_StatusEffect(BSSTATUS_SpawnEffectB, 1, 3),
    BS_WaitFrames(10),
    BS_ReleaseKind2Emitters(),
    BS_Unk36(1, 3),
    BS_Unk36(1, 2),
    BS_Unk36(1, 1),
    BS_AdvanceAttackOutcome(),
    BS_AdvanceAttackOutcome(),
    BS_AdvanceAttackOutcome(),
    BS_End(),
};
