// Plays the spell's cast animation.
const u8 g_abSpellWingardiumLeviosaScript[] = {
    BS_TeleportToSlotPosition(0),
    BS_GotoLocalIndexedLabel(0, 39, 50, 51, 52, 53, 0, 0),
  BS_Label(39),
    BS_WaitFrames(2),
    BS_DarkenScreenPalette(),
    BS_WaitFrames(20),
    BS_PlaySoundOrDefault(120),
    BS_MoveBy(0, 248),
    BS_SpawnEffect(28),
    BS_IncrementLocal(0),
    BS_SpawnEffect(28),
    BS_SetOamPriority(1),
    BS_SetDepthBiasMax(),
    BS_WaitFrames(1),
    BS_SetObjectAnim(28, 0),
    BS_WaitFrames(1),
    BS_ShowObject(),
    BS_WaitFrames(10),
    BS_GotoIfContextLow(58),
    BS_SetTargetVelocityScaled(0, 240),
    BS_WaitFrames(2),
    BS_SetTargetVelocityScaled(0, 224),
    BS_WaitFrames(2),
    BS_SetTargetVelocityScaled(0, 208),
    BS_WaitFrames(2),
    BS_SetTargetVelocityScaled(0, 192),
    BS_WaitFrames(2),
    BS_SetTargetVelocityScaled(0, 160),
    BS_WaitFrames(2),
    BS_SetTargetVelocity(0, 10),
    BS_WaitFrames(1),
    BS_PlaySoundOrDefault(121),
    BS_SetTargetVelocity(0, 12),
    BS_WaitFrames(1),
    BS_SetTargetVelocity(0, 14),
    BS_WaitFrames(1),
    BS_SetTargetVelocityScaled(0, 0),
    BS_SnapTargetToSlot(),
    BS_AdvanceAttackOutcome(),
    BS_IncrementLocal(0),
    BS_SpawnEffect(28),
    BS_IncrementLocal(0),
    BS_SpawnEffect(28),
    BS_ScrollBgUp(1),
    BS_WaitFrames(1),
    BS_AdvanceAttackOutcome(),
    BS_AdvanceAttackOutcome(),
    BS_ScrollBgDown(1),
    BS_WaitForCounter(),
    BS_End(),
  BS_Label(58),
    BS_AdvanceAttackOutcome(),
    BS_WaitFrames(1),
    BS_AdvanceAttackOutcome(),
    BS_AdvanceAttackOutcome(),
    BS_WaitFrames(1),
    BS_HideObject(),
    BS_RestoreScreenPalette(),
    BS_WaitFrames(20),
    BS_AdvanceAttackOutcome(),
    BS_AdvanceAttackOutcome(),
    BS_AdvanceAttackOutcome(),
    BS_End(),
  BS_Label(50),
    BS_MoveBy(240, 0),
    BS_SetOamPriority(0),
    BS_Goto(38),
  BS_Label(51),
    BS_MoveBy(16, 0),
    BS_SetOamPriority(0),
  BS_Label(38),
    BS_SetObjectAnim(28, 0),
    BS_WaitFrames(1),
    BS_ShowObject(),
    BS_WaitForCounter(),
    BS_End(),
  BS_Label(52),
    BS_SetObjectAnimFromTable2AndPalette(16, 0),
    BS_WaitFrames(1),
    BS_ShowObject(),
    BS_WaitForCounter(),
    BS_End(),
  BS_Label(53),
    BS_ToggleObjectFlipX(),
    BS_SetObjectAnimFromTable2AndPalette(16, 0),
    BS_WaitFrames(1),
    BS_ShowObject(),
    BS_WaitForCounter(),
    BS_HideObject(),
    BS_RestoreScreenPalette(),
    BS_WaitFrames(20),
    BS_AdvanceAttackOutcome(),
    BS_AdvanceAttackOutcome(),
    BS_AdvanceAttackOutcome(),
    BS_End(),
};
