// Plays the spell's cast animation.
const u8 g_abSpellFlipendoTriaScript[] = {
    BS_GotoIfLocalANotEqual(0, 49),
    BS_WaitFrames(2),
    BS_DarkenScreenPalette(),
    BS_WaitFrames(20),
    BS_PlaySound(95),
    BS_SetObjectAnim(21, 0),
    BS_SpawnEffect(21),
    BS_TeleportTo(80, 70),
    BS_WaitFrames(1),
    BS_ShowObject(),
    BS_WaitFrames(24),
    BS_MoveBy(0, 8),
    BS_StartOrbitMotion(9, 0),
    BS_SetVelocity(-3, 0),
    BS_WaitFrames(15),
    BS_SetVelocity(3, 0),
    BS_WaitFrames(30),
    BS_SetVelocity(-3, 0),
    BS_WaitFrames(15),
    BS_SetVelocity(0, 0),
    BS_MoveBy(0, -8),
    BS_StartOrbitMotion(8, 0),
    BS_SetObjectAnim(21, 25),
    BS_WaitForCounter(),
    BS_UnmuteMusic(),
    BS_HideObject(),
    BS_RestoreScreenPalette(),
    BS_WaitFrames(20),
    BS_AdvanceAttackOutcome(),
    BS_AdvanceAttackOutcome(),
    BS_AdvanceAttackOutcome(),
    BS_AdvanceAttackOutcome(),
    BS_End(),
  BS_Label(49),
    BS_TeleportTo(250, 60),
    BS_SetOamPriority(1),
    BS_SetDepthBiasZero(),
    BS_JitterPosition(0, 30),
    BS_StartOrbitMotion(15, 64),
    BS_SetVelocity(-4, 0),
    BS_SetObjectAnimFromTable2AndPalette(4, 0),
    BS_WaitFrames(1),
    BS_ShowObject(),
    BS_WaitFrames(7),
    BS_GotoIfLocalAGreater(7, 50),
    BS_SpawnEffect(21),
  BS_Label(50),
    BS_WaitFrames(80),
    BS_End(),
};
