// Makes a party member harder to hit.
const u8 g_abSpellFumosUnoScript[] = {
    BS_WaitFrames(1),
    BS_DarkenScreenPalette(),
    BS_WaitFrames(20),
    BS_SetOamPriority(1),
    BS_TeleportToSlotPosition(0),
    BS_MoveBy(0, 248),
    BS_SetObjectAnim(11, 0),
    BS_WaitFrames(1),
    BS_ShowObject(),
    BS_WaitFrames(4),
    BS_SpawnEffectAtSelf(12),
    BS_WaitFrames(18),
    BS_HideObject(),
    BS_WaitFrames(35),
    BS_StatusEffect(BSSTATUS_HiddenMain, 0, 0),
    BS_WaitFrames(35),
    BS_HideObject(),
    BS_RestoreScreenPalette(),
    BS_WaitFrames(20),
    BS_AdvanceAttackOutcome(),
    BS_AdvanceAttackOutcome(),
    BS_AdvanceAttackOutcome(),
    BS_AdvanceAttackOutcome(),
    BS_AdvanceAttackOutcome(),
    BS_End(),
};
