// Weakens one enemy's attacks.
const u8 g_abSpellSpongifyScript[] = {
    BS_WaitFrames(2),
    BS_DarkenScreenPalette(),
    BS_WaitFrames(20),
    BS_TeleportToSlotPosition(0),
    BS_PlaySound(112),
    BS_SetObjectAnim(29, 0),
    BS_WaitFrames(1),
    BS_ShowObject(),
    BS_WaitForCounter(),
    BS_StatusEffect(BSSTATUS_AttackWeakened, 0, 0),
    BS_CreateEmitterOnTarget(7, 10, 16, 8, 3, 0, 0, 0, 0, 254, 0, 0, 10, 0, 0, 1),
    BS_WaitFrames(10),
    BS_HideObject(),
    BS_RestoreScreenPalette(),
    BS_WaitFrames(20),
    BS_AdvanceAttackOutcome(),
    BS_AdvanceAttackOutcome(),
    BS_AdvanceAttackOutcome(),
    BS_AdvanceAttackOutcome(),
    BS_AdvanceAttackOutcome(),
    BS_End(),
};
