// Plays the spell's cast animation.
const u8 g_abSpellVerdimilliousDuoScript[] = {
    BS_TeleportToSlotPosition(0),
    BS_GotoIfLocalAEqual(1, 49),
    BS_WaitFrames(2),
    BS_DarkenScreenPalette(),
    BS_WaitFrames(20),
    BS_MoveBy(0, -16),
    BS_PlaySoundOrDefault(90),
    BS_SetObjectAnim(20, 0),
    BS_ShowObject(),
    BS_WaitFrames(20),
    BS_SpawnEffect(20),
    BS_AdvanceAttackOutcome(),
    BS_AdvanceAttackOutcome(),
    BS_WaitFrames(10),
    BS_HideObject(),
    BS_RestoreScreenPalette(),
    BS_WaitFrames(20),
    BS_AdvanceAttackOutcome(),
    BS_AdvanceAttackOutcome(),
    BS_AdvanceAttackOutcome(),
    BS_End(),
  BS_Label(49),
    BS_SetObjectAnim(26, 0),
    BS_SetOamPriority(0),
    BS_SetDepthBiasZero(),
    BS_WaitFrames(1),
    BS_ShowObject(),
    BS_WaitForCounter(),
    BS_End(),
};
