// Randomly attempts to paralyze the target.
const u8 g_abSpellPetrificusTotalusDuoScript[] = {
    BS_GotoIfLocalANotEqual(0, 38),
    BS_WaitFrames(2),
    BS_DarkenScreenPalette(),
    BS_WaitFrames(20),
    BS_SelectFirstLiveEnemy(),
  BS_Label(38),
    BS_TeleportToSlotPosition(0),
    BS_StatusEffect(BSSTATUS_Paralyze25, 0, 0),
    BS_SelectNextLiveEnemy(),
    BS_GotoIfLocalBEqual(1, 50),
    BS_SpawnEffect(34),
    BS_PlaySound(118),
    BS_SetObjectAnim(33, 0),
    BS_WaitFrames(1),
    BS_ShowObject(),
    BS_WaitForCounter(),
    BS_MoveBy(0, -12),
    BS_PlaySound(119),
    BS_SetObjectAnimFromTable2AndPalette(20, 0),
    BS_WaitForCounter(),
    BS_End(),
  BS_Label(50),
    BS_PlaySound(118),
    BS_SetObjectAnim(33, 0),
    BS_WaitFrames(1),
    BS_ShowObject(),
    BS_WaitForCounter(),
    BS_MoveBy(0, -12),
    BS_PlaySound(119),
    BS_SetObjectAnimFromTable2AndPalette(20, 0),
    BS_WaitForCounter(),
    BS_HideObject(),
    BS_RestoreScreenPalette(),
    BS_WaitFrames(20),
    BS_AdvanceAttackOutcome(),
    BS_AdvanceAttackOutcome(),
    BS_AdvanceAttackOutcome(),
    BS_AdvanceAttackOutcome(),
    BS_AdvanceAttackOutcome(),
    BS_End(),
};
