// Plays the spell's cast animation.
const u8 g_abSpellVerdimilliousTriaScript[] = {
    BS_GotoIfLocalAEqual(1, 56),
    BS_GotoIfLocalAEqual(2, 49),
    BS_GotoIfLocalAGreater(2, 50),
    BS_WaitFrames(2),
    BS_DarkenScreenPalette(),
    BS_WaitFrames(20),
    BS_PlaySound(91),
    BS_SetLocal(0, 1),
    BS_SpawnEffectDetached(26),
    BS_WaitFrames(14),
    BS_TeleportTo(68, 64),
    BS_SetOamPriority(0),
    BS_PlaySound(91),
    BS_PlaySound(91),
    BS_PlaySound(91),
    BS_PlaySound(91),
    BS_SetObjectAnim(26, 0),
    BS_EnableSemiTransparency(),
    BS_SetAlphaBlend(13, 8),
    BS_WaitFrames(1),
    BS_ShowObject(),
    BS_WaitFrames(6),
    BS_SetLocal(0, 0),
    BS_SpawnEffect(26),
    BS_WaitForCounter(),
    BS_End(),
  BS_Label(56),
    BS_PlaySound(92),
    BS_TeleportTo(0, 54),
    BS_MoveBy(-32, 0),
    BS_SetOamPriority(0),
    BS_SetObjectAnimFromTable2AndPalette(13, 0),
    BS_WaitFrames(1),
    BS_ShowObject(),
    BS_WaitForCounter(),
    BS_HideObject(),
    BS_RestoreScreenPalette(),
    BS_WaitFrames(20),
    BS_AdvanceAttackOutcome(),
    BS_AdvanceAttackOutcome(),
    BS_AdvanceAttackOutcome(),
    BS_AdvanceAttackOutcome(),
    BS_End(),
  BS_Label(49),
    BS_SelectFirstLiveEnemy(),
  BS_Label(50),
    BS_TeleportToSlotPosition(0),
    BS_SelectNextLiveEnemy(),
    BS_GotoIfLocalBEqual(1, 51),
    BS_SpawnEffect(26),
  BS_Label(51),
    BS_MoveBy(0, -16),
    BS_SetObjectAnimFromTable2AndPalette(12, 0),
    BS_WaitFrames(1),
    BS_ShowObject(),
    BS_WaitForCounter(),
    BS_HideObject(),
    BS_WaitFrames(14),
    BS_SetObjectAnimFromTable2AndPalette(14, 0),
    BS_WaitFrames(1),
    BS_ShowObject(),
    BS_WaitForCounter(),
    BS_End(),
};
