// Plays the spell's cast animation.
const u8 g_abSpellIncendioUnoScript[] = {
    BS_GotoIfLocalANotEqual(0, 49),
    BS_WaitFrames(2),
    BS_DarkenScreenPalette(),
    BS_WaitFrames(20),
    BS_TeleportToSlotPosition(0),
    BS_MoveBy(0, -5),
    BS_SpawnEffectAtSelf(23),
    BS_WaitFrames(5),
    BS_MoveBy(10, 10),
    BS_SpawnEffectAtSelf(23),
    BS_WaitFrames(5),
    BS_MoveBy(-20, 0),
    BS_SpawnEffectAtSelf(23),
    BS_WaitFrames(5),
    BS_WaitFrames(20),
    BS_AdvanceAttackOutcome(),
    BS_WaitFrames(1),
    BS_AdvanceAttackOutcome(),
    BS_AdvanceAttackOutcome(),
    BS_WaitFrames(1),
    BS_HideObject(),
    BS_RestoreScreenPalette(),
    BS_WaitFrames(20),
    BS_AdvanceAttackOutcome(),
    BS_AdvanceAttackOutcome(),
    BS_AdvanceAttackOutcome(),
    BS_End(),
  BS_Label(49),
    BS_PlaySoundOrDefault(100),
    BS_SetObjectAnim(23, 0),
    BS_ShowObject(),
    BS_WaitForCounter(),
    BS_End(),
};
