// Cast upon a creature to learn about its strengths and weaknesses.
const u8 g_abSpellInformusScript[] = {
    BS_GotoIfLocalAEqual(1, 38),
    BS_GotoIfLocalAEqual(2, 50),
    BS_WaitFrames(2),
    BS_DarkenScreenPalette(),
    BS_WaitFrames(20),
    BS_StartOrbitMotion(12, 0),
    BS_TeleportToSlotPosition(0),
    BS_MoveBy(8, 248),
    BS_PlaySound(17),
    BS_SetObjectAnim(38, 0),
    BS_StartAffineWobble(0, 64, 0, 64, 0, 224, 224, 0),
    BS_WaitFrames(1),
    BS_ShowObject(),
    BS_WaitFrames(23),
    BS_StopAffineWobble(),
    BS_SpawnEffect(38),
    BS_WaitFrames(80),
    BS_StartAffineWobble(1, 0, 1, 0, 0, 32, 32, 0),
    BS_WaitFrames(23),
    BS_HideObject(),
    BS_RestoreScreenPalette(),
    BS_WaitFrames(20),
    BS_StatusEffect(BSSTATUS_BumpMonsterDocLevel, 0, 0),
    BS_AdvanceAttackOutcome(),
    BS_AdvanceAttackOutcome(),
    BS_AdvanceAttackOutcome(),
    BS_AdvanceAttackOutcome(),
    BS_AdvanceAttackOutcome(),
    BS_End(),
  BS_Label(38),
    BS_SetOamPriority(0),
    BS_SetDepthBias(0),
    BS_StartOrbitMotion(2, 0),
    BS_TeleportTo(192, 36),
    BS_PlaySound(17),
    BS_SetObjectAnimFromTable2AndPalette(23, 0),
    BS_StartAffineWobble(0, 64, 0, 64, 0, 224, 224, 0),
    BS_WaitFrames(1),
    BS_ShowObject(),
    BS_WaitFrames(23),
    BS_StopAffineWobble(),
    BS_SpawnEffect(38),
    BS_WaitFrames(3),
    BS_SpawnEffect(38),
    BS_WaitFrames(3),
    BS_SpawnEffect(38),
    BS_WaitFrames(4),
    BS_SpawnEffect(38),
    BS_WaitFrames(2),
    BS_SpawnEffect(38),
    BS_WaitFrames(3),
    BS_SpawnEffect(38),
    BS_WaitFrames(1),
    BS_SpawnEffect(38),
    BS_WaitFrames(55),
    BS_StartAffineWobble(1, 0, 1, 0, 0, 32, 32, 0),
    BS_SetObjectAnimFromTable2AndPalette(23, 8),
    BS_WaitFrames(23),
    BS_End(),
  BS_Label(50),
    BS_TeleportToSlotPosition(0),
    BS_MoveBy(8, 248),
    BS_PlaySound(115),
    BS_SetObjectAnimFromTable2AndPalette(24, 0),
    BS_StartOrbitMotion(5, 0),
    BS_WaitFrames(1),
    BS_ShowObject(),
    BS_MoveToAbsolute(176, 48, 20),
    BS_WaitFrames(20),
    BS_End(),
};
