// Plays the spell's cast animation.
const u8 g_abSpellDiffindoScript[] = {
    BS_WaitFrames(2),
    BS_DarkenScreenPalette(),
    BS_WaitFrames(20),
    BS_TeleportToSlotPosition(0),
    BS_PlaySoundOrDefault(113),
    BS_SetObjectAnim(22, 0),
    BS_WaitFrames(1),
    BS_ShowObject(),
    BS_WaitFrames(20),
    BS_PlaySoundOrDefault(113),
    BS_WaitFrames(25),
    BS_AdvanceAttackOutcome(),
    BS_WaitForCounter(),
    BS_HideObject(),
    BS_AdvanceAttackOutcome(),
    BS_AdvanceAttackOutcome(),
    BS_WaitFrames(1),
    BS_HideObject(),
    BS_RestoreScreenPalette(),
    BS_WaitFrames(20),
    BS_AdvanceAttackOutcome(),
    BS_AdvanceAttackOutcome(),
    BS_AdvanceAttackOutcome(),
    BS_End(),
};
