// Plays the spell's cast animation.
const u8 g_abSpellFlipendoUnoScript[] = {
    BS_GotoIfLocalANotEqual(0, 49),
    BS_WaitFrames(2),
    BS_DarkenScreenPalette(),
    BS_WaitFrames(20),
    BS_AdvanceAttackOutcome(),
    BS_TeleportToSlotPosition(0),
    BS_PlaySoundOrDefault(93),
    BS_SetObjectAnim(2, 0),
    BS_SetOamPriority(0),
    BS_WaitFrames(1),
    BS_ShowObject(),
    BS_AdvanceAttackOutcome(),
    BS_AdvanceAttackOutcome(),
    BS_WaitFrames(1),
    BS_SpawnEffect(2),
    BS_GotoIfContextLow(0),
    BS_SetTargetVelocityScaled(-64, -32),
    BS_WaitFrames(1),
    BS_SetTargetVelocityScaled(-48, -24),
    BS_WaitFrames(1),
    BS_SetTargetVelocityScaled(-32, -16),
    BS_WaitFrames(1),
    BS_SetTargetVelocityScaled(-16, -8),
    BS_WaitFrames(1),
    BS_SetTargetVelocityScaled(16, 8),
    BS_WaitFrames(18),
    BS_SetTargetVelocityScaled(0, 0),
    BS_SnapTargetToSlot(),
  BS_Label(0),
    BS_WaitForCounter(),
    BS_HideObject(),
    BS_RestoreScreenPalette(),
    BS_WaitFrames(20),
    BS_AdvanceAttackOutcome(),
    BS_AdvanceAttackOutcome(),
    BS_AdvanceAttackOutcome(),
    BS_End(),
  BS_Label(49),
    BS_TeleportToSlotPosition(0),
    BS_SetOamPriority(1),
    BS_SetDepthBiasZero(),
    BS_JitterPosition(10, 0),
    BS_SetVelocity(0, -3),
    BS_SetObjectAnimFromTable2AndPalette(3, 0),
    BS_WaitFrames(1),
    BS_ShowObject(),
    BS_WaitFrames(1),
    BS_GotoIfLocalAGreater(4, 50),
    BS_SpawnEffect(2),
  BS_Label(50),
    BS_WaitFrames(40),
    BS_End(),
};
