// Plays the spell's cast animation.
const u8 g_abSpellVerdimilliousUnoScript[] = {
    BS_GotoIfLocalAEqual(1, 45),
    BS_GotoIfLocalAEqual(2, 46),
    BS_GotoIfLocalAEqual(3, 47),
    BS_GotoIfLocalAEqual(4, 48),
    BS_GotoIfLocalAEqual(5, 45),
    BS_GotoIfLocalAEqual(6, 46),
    BS_GotoIfLocalAEqual(7, 47),
    BS_GotoIfLocalAEqual(8, 48),
    BS_GotoIfLocalAEqual(9, 45),
    BS_GotoIfLocalAEqual(10, 46),
    BS_WaitFrames(2),
    BS_DarkenScreenPalette(),
    BS_WaitFrames(20),
    BS_TeleportToSlotPosition(1),
    BS_MoveBy(248, 254),
    BS_SpawnEffectAtSelf(19),
    BS_WaitFrames(5),
    BS_MoveBy(16, 8),
    BS_IncrementLocal(0),
    BS_IncrementLocal(0),
    BS_SpawnEffectAtSelf(19),
    BS_WaitFrames(5),
    BS_MoveBy(240, 8),
    BS_IncrementLocal(0),
    BS_IncrementLocal(0),
    BS_SpawnEffectAtSelf(19),
    BS_GotoIfFighterRosterMatches(38),
    BS_WaitFrames(19),
    BS_AdvanceAttackOutcome(),
    BS_AdvanceAttackOutcome(),
    BS_WaitFrames(31),
    BS_HideObject(),
    BS_RestoreScreenPalette(),
    BS_WaitFrames(20),
    BS_AdvanceAttackOutcome(),
    BS_AdvanceAttackOutcome(),
    BS_AdvanceAttackOutcome(),
    BS_End(),
  BS_Label(38),
    BS_WaitForCounter(),
    BS_WaitFrames(5),
    BS_MoveBy(32, 8),
    BS_IncrementLocal(0),
    BS_IncrementLocal(0),
    BS_SpawnEffectAtSelf(19),
    BS_WaitFrames(5),
    BS_MoveBy(224, 8),
    BS_IncrementLocal(0),
    BS_IncrementLocal(0),
    BS_SpawnEffectAtSelf(19),
    BS_WaitFrames(19),
    BS_AdvanceAttackOutcome(),
    BS_AdvanceAttackOutcome(),
    BS_WaitFrames(31),
    BS_HideObject(),
    BS_RestoreScreenPalette(),
    BS_WaitFrames(20),
    BS_AdvanceAttackOutcome(),
    BS_AdvanceAttackOutcome(),
    BS_AdvanceAttackOutcome(),
    BS_End(),
  BS_Label(47),
    BS_ToggleObjectFlipX(),
  BS_Label(45),
    BS_PlaySoundOrDefault(90),
    BS_SetObjectAnimFromTable2AndPalette(11, 0),
    BS_ShowObject(),
    BS_WaitFrames(5),
    BS_SpawnEffectAtSelf(19),
    BS_WaitForCounter(),
    BS_End(),
  BS_Label(48),
    BS_ToggleObjectFlipX(),
  BS_Label(46),
    BS_PlaySoundOrDefault(90),
    BS_SetObjectAnim(19, 0),
    BS_ShowObject(),
    BS_WaitForCounter(),
    BS_End(),
};
