// Randomly attempts to paralyze the target.
const u8 g_abSpellPetrificusTotalusUnoScript[] = {
    BS_WaitFrames(2),
    BS_DarkenScreenPalette(),
    BS_WaitFrames(20),
    BS_TeleportToSlotPosition(0),
    BS_PlaySound(116),
    BS_SetObjectAnim(33, 0),
    BS_WaitFrames(1),
    BS_ShowObject(),
    BS_WaitForCounter(),
    BS_MoveBy(0, 244),
    BS_PlaySound(117),
    BS_SetObjectAnimFromTable2AndPalette(19, 0),
    BS_WaitForCounter(),
    BS_StatusEffect(BSSTATUS_Paralyze25, 0, 0),
    BS_HideObject(),
    BS_RestoreScreenPalette(),
    BS_WaitFrames(20),
    BS_AdvanceAttackOutcome(),
    BS_AdvanceAttackOutcome(),
    BS_AdvanceAttackOutcome(),
    BS_AdvanceAttackOutcome(),
    BS_AdvanceAttackOutcome(),
    BS_End(),
};
