// Makes the whole party harder to hit.
const u8 g_abSpellFumosDuoScript[] = {
    BS_SetOamPriority(1),
    BS_GotoIfLocalANotEqual(0, 49),
    BS_WaitFrames(2),
    BS_DarkenScreenPalette(),
    BS_WaitFrames(20),
    BS_SelectFirstAlly(),
    BS_StatusEffect(BSSTATUS_HiddenMain, 0, 0),
    BS_Goto(38),
  BS_Label(49),
    BS_StatusEffect(BSSTATUS_HiddenSecondary, 0, 0),
  BS_Label(38),
    BS_SetLocal(0, 0),
    BS_TeleportToSlotPosition(0),
    BS_MoveBy(0, -8),
    BS_SetObjectAnim(11, 0),
    BS_WaitFrames(1),
    BS_ShowObject(),
    BS_WaitFrames(4),
    BS_SpawnEffectAtSelf(12),
    BS_WaitFrames(1),
    BS_SelectNextAlly(),
    BS_GotoIfLocalBEqual(1, 50),
    BS_SpawnEffect(32),
    BS_WaitFrames(17),
    BS_End(),
  BS_Label(50),
    BS_WaitFrames(18),
    BS_HideObject(),
    BS_WaitFrames(70),
    BS_HideObject(),
    BS_RestoreScreenPalette(),
    BS_WaitFrames(20),
    BS_AdvanceAttackOutcome(),
    BS_AdvanceAttackOutcome(),
    BS_AdvanceAttackOutcome(),
    BS_AdvanceAttackOutcome(),
    BS_AdvanceAttackOutcome(),
    BS_End(),
};
