// Plays the spell's cast animation.
const u8 g_abSpellFlipendoDuoScript[] = {
    BS_GotoIfLocalANotEqual(0, 24),
    BS_WaitFrames(2),
    BS_DarkenScreenPalette(),
    BS_WaitFrames(20),
    BS_TeleportToSlotPosition(0),
    BS_SpawnEffectAtSelf(3),
    BS_WaitFrames(5),
    BS_FlipTargetFacing(),
    BS_PlaySoundOrDefault(94),
    BS_SpawnEffectOffset(3, 0, 0, 255, 4),
    BS_WaitFrames(5),
    BS_FlipTargetFacing(),
    BS_PlaySoundOrDefault(94),
    BS_SpawnEffectOffset(3, 0, 0, 255, 8),
    BS_WaitFrames(5),
    BS_FlipTargetFacing(),
    BS_PlaySoundOrDefault(94),
    BS_SpawnEffectOffset(3, 0, 0, 255, 12),
    BS_WaitFrames(4),
    BS_FlipTargetFacing(),
    BS_PlaySoundOrDefault(94),
    BS_WaitFrames(1),
    BS_SpawnEffectOffset(3, 0, 0, 255, 16),
    BS_WaitFrames(3),
    BS_FlipTargetFacing(),
    BS_PlaySoundOrDefault(94),
    BS_WaitFrames(2),
    BS_SpawnEffectOffset(3, 0, 0, 255, 20),
    BS_WaitFrames(2),
    BS_FlipTargetFacing(),
    BS_PlaySoundOrDefault(94),
    BS_WaitFrames(1),
    BS_FlipTargetFacing(),
    BS_PlaySoundOrDefault(94),
    BS_WaitFrames(1),
    BS_FlipTargetFacing(),
    BS_PlaySoundOrDefault(94),
    BS_AdvanceAttackOutcome(),
    BS_WaitFrames(1),
    BS_AdvanceAttackOutcome(),
    BS_AdvanceAttackOutcome(),
    BS_FlipTargetFacing(),
    BS_PlaySoundOrDefault(94),
    BS_WaitFrames(1),
    BS_FlipTargetFacing(),
    BS_PlaySoundOrDefault(94),
    BS_WaitFrames(1),
    BS_FlipTargetFacing(),
    BS_PlaySoundOrDefault(94),
    BS_WaitFrames(2),
    BS_FlipTargetFacing(),
    BS_PlaySoundOrDefault(94),
    BS_WaitFrames(3),
    BS_FlipTargetFacing(),
    BS_PlaySoundOrDefault(94),
    BS_WaitFrames(4),
    BS_FlipTargetFacing(),
    BS_PlaySoundOrDefault(94),
    BS_WaitFrames(5),
    BS_FlipTargetFacing(),
    BS_PlaySoundOrDefault(94),
    BS_WaitFrames(5),
    BS_FlipTargetFacing(),
    BS_PlaySoundOrDefault(94),
    BS_WaitFrames(5),
    BS_FlipTargetFacing(),
    BS_PlaySoundOrDefault(94),
    BS_WaitFrames(5),
    BS_FlipTargetFacing(),
    BS_PlaySoundOrDefault(94),
    BS_HideObject(),
    BS_RestoreScreenPalette(),
    BS_WaitFrames(20),
    BS_AdvanceAttackOutcome(),
    BS_AdvanceAttackOutcome(),
    BS_AdvanceAttackOutcome(),
    BS_End(),
  BS_Label(24),
    BS_GotoIfLocalBEqual(4, 28),
    BS_SetLocalRandomRange(0, 1, 4),
    BS_GotoLocalIndexedLabel(0, 0, 25, 26, 27, 0, 0, 0),
  BS_Label(25),
    BS_SetObjectAnim(3, 0),
    BS_SetOamPriority(0),
    BS_WaitFrames(1),
    BS_ShowObject(),
    BS_WaitForCounter(),
    BS_IncrementLocal(1),
    BS_Goto_2(24),
  BS_Label(26),
    BS_SetObjectAnim(3, 14),
    BS_SetOamPriority(0),
    BS_WaitFrames(1),
    BS_ShowObject(),
    BS_WaitForCounter(),
    BS_IncrementLocal(1),
    BS_Goto_2(24),
  BS_Label(27),
    BS_SetObjectAnim(3, 28),
    BS_SetOamPriority(0),
    BS_WaitFrames(1),
    BS_ShowObject(),
    BS_WaitForCounter(),
    BS_IncrementLocal(1),
    BS_Goto_2(24),
  BS_Label(28),
    BS_End(),
};
