// Plays the spell's cast animation.
const u8 g_abSpellGlaciusUnoScript[] = {
    BS_TeleportToSlotPosition(0),
    BS_GotoLocalIndexedLabel(0, 39, 49, 50, 58, 59, 60, 61),
  BS_Label(39),
    BS_WaitFrames(2),
    BS_DarkenScreenPalette(),
    BS_WaitFrames(20),
    BS_SpawnEffect(30),
    BS_IncrementLocal(0),
    BS_SpawnEffect(30),
    BS_SetObjectAnim(30, 0),
    BS_WaitFrames(1),
    BS_ShowObject(),
    BS_PlaySoundOrDefault(107),
    BS_WaitFrames(5),
    BS_PlaySoundOrDefault(107),
    BS_WaitFrames(5),
    BS_PlaySoundOrDefault(107),
    BS_WaitFrames(5),
    BS_PlaySoundOrDefault(107),
    BS_WaitFrames(27),
    BS_AdvanceAttackOutcome(),
    BS_IncrementLocal(0),
    BS_SpawnEffect(30),
    BS_IncrementLocal(0),
    BS_SpawnEffect(30),
    BS_IncrementLocal(0),
    BS_SpawnEffect(30),
    BS_IncrementLocal(0),
    BS_SpawnEffect(30),
    BS_IncrementLocal(1),
    BS_SetLocal(0, 2),
    BS_SpawnEffect(30),
    BS_IncrementLocal(0),
    BS_SpawnEffect(30),
    BS_IncrementLocal(0),
    BS_SpawnEffect(30),
    BS_IncrementLocal(0),
    BS_SpawnEffect(30),
    BS_WaitFrames(4),
    BS_AdvanceAttackOutcome(),
    BS_AdvanceAttackOutcome(),
    BS_WaitForCounter(),
    BS_HideObject(),
    BS_WaitFrames(40),
    BS_HideObject(),
    BS_RestoreScreenPalette(),
    BS_WaitFrames(20),
    BS_AdvanceAttackOutcome(),
    BS_AdvanceAttackOutcome(),
    BS_AdvanceAttackOutcome(),
    BS_End(),
  BS_Label(49),
    BS_JitterPosition(18, 8),
    BS_SetObjectAnimFromTable2AndPalette(17, 0),
    BS_ShowObject(),
    BS_WaitFrames(1),
    BS_IncrementLocal(1),
    BS_GotoIfLocalBEqual(12, 38),
    BS_SetLocal(0, 0),
    BS_SpawnEffectAtSelf(30),
  BS_Label(38),
    BS_WaitForCounter(),
    BS_End(),
  BS_Label(50),
    BS_JitterPosition(12, 8),
    BS_SetObjectAnimFromTable2AndPalette(17, 4),
    BS_ShowObject(),
    BS_WaitFrames(1),
    BS_IncrementLocal(1),
    BS_GotoIfLocalBEqual(18, 38),
    BS_SetLocal(0, 1),
    BS_SpawnEffectAtSelf(30),
  BS_Label(38),
    BS_WaitForCounter(),
    BS_End(),
  BS_Label(58),
    BS_JitterPosition(12, 8),
    BS_PlaySoundOrDefault(108),
    BS_SetObjectAnimFromTable2AndPalette(17, 8),
    BS_WaitFrames(1),
    BS_ShowObject(),
    BS_StartOrbitMotion(11, 0),
    BS_GotoIfLocalBEqual(1, 62),
    BS_SetVelocity(1, 0),
    BS_Goto(51),
  BS_Label(62),
    BS_SetVelocity(255, 0),
  BS_Label(51),
    BS_WaitFrames(30),
    BS_StartOrbitMotion(8, 0),
    BS_SetVelocity(0, 0),
    BS_SetObjectAnimFromTable2AndPalette(17, 16),
    BS_WaitFrames(6),
    BS_End(),
  BS_Label(59),
    BS_JitterPosition(12, 8),
    BS_PlaySoundOrDefault(108),
    BS_SetObjectAnimFromTable2AndPalette(17, 10),
    BS_WaitFrames(1),
    BS_ShowObject(),
    BS_StartOrbitMotion(11, 0),
    BS_GotoIfLocalBEqual(1, 63),
    BS_SetVelocity(2, 0),
    BS_Goto(52),
  BS_Label(63),
    BS_SetVelocity(254, 0),
  BS_Label(52),
    BS_WaitFrames(30),
    BS_StartOrbitMotion(8, 0),
    BS_SetVelocity(0, 0),
    BS_SetObjectAnimFromTable2AndPalette(17, 19),
    BS_WaitFrames(6),
    BS_End(),
  BS_Label(60),
    BS_JitterPosition(12, 8),
    BS_PlaySoundOrDefault(108),
    BS_SetObjectAnimFromTable2AndPalette(17, 12),
    BS_WaitFrames(1),
    BS_ShowObject(),
    BS_StartOrbitMotion(11, 0),
    BS_GotoIfLocalBEqual(1, 64),
    BS_SetVelocity(253, 0),
    BS_Goto(53),
  BS_Label(64),
    BS_SetVelocity(3, 0),
  BS_Label(53),
    BS_WaitFrames(30),
    BS_StartOrbitMotion(8, 0),
    BS_SetVelocity(0, 0),
    BS_SetObjectAnimFromTable2AndPalette(17, 22),
    BS_WaitFrames(6),
    BS_End(),
  BS_Label(61),
    BS_JitterPosition(12, 8),
    BS_PlaySoundOrDefault(108),
    BS_SetObjectAnimFromTable2AndPalette(17, 14),
    BS_WaitFrames(1),
    BS_ShowObject(),
    BS_StartOrbitMotion(11, 0),
    BS_GotoIfLocalBEqual(1, 65),
    BS_SetVelocity(1, 0),
    BS_Goto(54),
  BS_Label(65),
    BS_SetVelocity(255, 0),
  BS_Label(54),
    BS_WaitFrames(30),
    BS_StartOrbitMotion(8, 0),
    BS_SetVelocity(0, 0),
    BS_SetObjectAnimFromTable2AndPalette(17, 25),
    BS_WaitFrames(6),
    BS_End(),
};
