#include "types.h"
#include "overworld/room_script_bytecode.h"

#include "v1/chain0.h"
#include "v1/talk_fudge1.h"
#include "v1/talk_patron_bar.h"
#include "v1/chain3.h"
#include "v1/try_visit_cellar.h"
#include "v1/chain5.h"
#include "v1/talk_patron_top_left.h"
#include "v1/talk_patron_bottom1.h"
#include "v1/talk_patron_bottom2.h"
#include "v1/talk_tom.h"
#include "v1/locked_door_entrance.h"
