#!/usr/bin/env python3
"""Pack every tile-frames manifest row from data/tile_frames/.

A row `tile-frames <start> <end> <dir> <name>` claims a run of contiguous
tile frames (see tile_frames.py). <dir>/bank.json lists them in ROM order.
The packed frames, and the assembly that labels each as g<FrameName>, go
under build/<ver>/tile_frames/; the C declarations go to include/gen/<name>.h.

Usage: pack_tile_frames.py <ver>
"""
import json
import re
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent))
import blobs
import tile_frames

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))
import stamp

ROOT = Path(__file__).resolve().parents[2]
SYMBOL = re.compile(r"[A-Za-z_][A-Za-z0-9_]*\Z")
ENTRY_KEYS = {"name", "kind", "tiles"}


def tile_frame_rows(ver: str):
    path = ROOT / f"regions.{ver}.txt"
    for lineno, raw in enumerate(path.read_text().splitlines(), 1):
        parts = raw.split("#", 1)[0].split()
        if not parts or parts[0] != "tile-frames":
            continue
        if len(parts) != 5:
            raise SystemExit(f"{path}:{lineno}: expected tile-frames <start> <end> <dir> <name>")
        _, start, end, source, name = parts
        if not SYMBOL.fullmatch(name):
            raise SystemExit(f"{path}:{lineno}: invalid bank name {name!r}")
        yield int(start, 16), int(end, 16), ROOT / source, name


def load_index(source: Path) -> list[dict]:
    path = source / "bank.json"
    index = json.loads(path.read_text())
    if set(index) != {"format", "frames"} or index["format"] != 1:
        raise ValueError(f"{path}: expected format 1 with frames")
    names = set()
    for entry in index["frames"]:
        if set(entry) != ENTRY_KEYS:
            raise ValueError(f"{path}: {entry.get('name')}: expected keys {', '.join(sorted(ENTRY_KEYS))}")
        name = entry["name"]
        if not isinstance(name, str) or not SYMBOL.fullmatch(name) or name in names:
            raise ValueError(f"{path}: invalid or duplicate frame name {name!r}")
        names.add(name)
        for key in ("kind", "tiles"):
            if not (isinstance(entry[key], int) and 0 < entry[key] < 1 << 16):
                raise ValueError(f"{path}: {name}: {key} must be a positive 16-bit integer")
    extras = {p.name for p in source.glob("*.png")} - {f"{e['name']}.png" for e in index["frames"]}
    if extras:
        raise ValueError(f"{path}: unlisted PNG files: {', '.join(sorted(extras))}")
    return index["frames"]


def frame_from_file(source: Path, entry: dict):
    size, pixels, _ = blobs.read_png(source / f"{entry['name']}.png")
    rows = (entry["tiles"] + tile_frames.TILES_PER_ROW - 1) // tile_frames.TILES_PER_ROW
    if size != (tile_frames.TILES_PER_ROW * 8, rows * 8):
        raise ValueError(f"{entry['name']}.png: expected {tile_frames.TILES_PER_ROW * 8}x{rows * 8}, got {size[0]}x{size[1]}")
    limit = 255 if entry["kind"] & tile_frames.KIND_8BPP else 15
    if max(pixels) > limit:
        raise ValueError(f"{entry['name']}.png: color number above {limit}")
    return tile_frames.tiles_from_sheet(pixels, entry["tiles"])


def pack_bank(ver: str, start: int, end: int, source: Path, name: str) -> int:
    entries = load_index(source)
    out = ROOT / "build" / ver / "tile_frames"
    out.mkdir(parents=True, exist_ok=True)
    if stamp.fresh(out / f"{name}.s", source, ROOT / f"regions.{ver}.txt"):
        return len(entries)
    packed = [tile_frames.build(e["kind"], frame_from_file(source, e)) for e in entries]
    size = sum(map(len, packed))
    if size != end - start:
        raise ValueError(f"{name}: packs to {size:#x} bytes, the manifest claims {end - start:#x}")
    (out / f"{name}.bin").write_bytes(b"".join(packed))
    asm, header, offset = [], ["// Generated by tools/graphic_blob/pack_tile_frames.py; do not edit.",
                               "#pragma once", "", '#include "types.h"', ""], 0
    for entry, data in zip(entries, packed):
        label = f"g{entry['name']}"
        asm += [f".global {label}", f"{label}:",
                f'    .incbin "build/{ver}/tile_frames/{name}.bin", {offset}, {len(data)}']
        header.append(f"extern const u8 {label}[];")
        offset += len(data)
    (out / f"{name}.s").write_text("\n".join(asm) + "\n")
    header_path = ROOT / f"include/gen/{name}.h"
    header_text = "\n".join(header) + "\n"
    if not header_path.is_file() or header_path.read_text() != header_text:
        header_path.write_text(header_text)
    return len(entries)


def main() -> None:
    ver = sys.argv[1] if len(sys.argv) > 1 else "us"
    try:
        for start, end, source, name in tile_frame_rows(ver):
            print(f"{ver}: packed {name}: {pack_bank(ver, start, end, source, name)} frames, {end - start} bytes")
    except (OSError, ValueError) as exc:
        sys.exit(str(exc))


if __name__ == "__main__":
    main()
