#!/usr/bin/env python3
"""Pack every fonts manifest row from data/fonts/.

A row `fonts <start> <end> <dir> <name>` claims a run of contiguous font blobs
(see fonts.py). <dir>/bank.json lists them in ROM order. The packed fonts, and
the assembly that labels each as g<FontName>, go under build/<ver>/fonts/; the
C declarations go to include/gen/<name>.h.

Usage: pack_fonts.py <ver>
"""
import json
import re
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent))
import fonts

sys.path.insert(0, str(Path(__file__).resolve().parents[1] / "graphic_blob"))
import blobs

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))
import buildcache

ROOT = Path(__file__).resolve().parents[2]
SYMBOL = re.compile(r"[A-Za-z_][A-Za-z0-9_]*\Z")
ENTRY_KEYS = {"name", "first", "last", "height", "widths"}
OPTIONAL_ENTRY_KEYS = {"flags"}


def font_rows(ver: str):
    path = ROOT / f"regions.{ver}.txt"
    for lineno, raw in enumerate(path.read_text().splitlines(), 1):
        parts = raw.split("#", 1)[0].split()
        if not parts or parts[0] != "fonts":
            continue
        if len(parts) != 5:
            raise SystemExit(f"{path}:{lineno}: expected fonts <start> <end> <dir> <name>")
        _, start, end, source, name = parts
        if not SYMBOL.fullmatch(name):
            raise SystemExit(f"{path}:{lineno}: invalid bank name {name!r}")
        yield int(start, 16), int(end, 16), ROOT / source, name


def load_index(source: Path) -> list[dict]:
    path = source / "bank.json"
    index = json.loads(path.read_text())
    if set(index) != {"format", "fonts"} or index["format"] != 1:
        raise ValueError(f"{path}: expected format 1 with fonts")
    names = set()
    for entry in index["fonts"]:
        if not ENTRY_KEYS <= set(entry) <= ENTRY_KEYS | OPTIONAL_ENTRY_KEYS:
            raise ValueError(f"{path}: {entry.get('name')}: unrecognized set of keys")
        name = entry["name"]
        if not isinstance(name, str) or not SYMBOL.fullmatch(name) or name in names:
            raise ValueError(f"{path}: invalid or duplicate font name {name!r}")
        names.add(name)
        for key in ("first", "last"):
            if not (isinstance(entry[key], int) and 0 <= entry[key] < 1 << 16):
                raise ValueError(f"{path}: {name}: {key} must be a 16-bit integer")
        if not (isinstance(entry["height"], int) and 0 < entry["height"] < 256):
            raise ValueError(f"{path}: {name}: height must be 1-255")
        widths = entry["widths"]
        if not (isinstance(widths, list) and len(widths) == entry["last"] - entry["first"] + 1
                and all(isinstance(w, int) and 0 < w < 256 for w in widths)):
            raise ValueError(f"{path}: {name}: widths must list one width (1-255) per glyph code")
        flags = entry.get("flags")
        if flags is not None and not (isinstance(flags, str) and len(flags) == len(widths)
                                      and set(flags) <= set("0123")):
            raise ValueError(f"{path}: {name}: flags must be one digit 0-3 per glyph code")
    extras = {p.name for p in source.glob("*.png")} - {f"{e['name']}.png" for e in index["fonts"]}
    if extras:
        raise ValueError(f"{path}: unlisted PNG files: {', '.join(sorted(extras))}")
    return index["fonts"]


def font_from_file(source: Path, entry: dict) -> fonts.Font:
    size, pixels, _ = blobs.read_png(source / f"{entry['name']}.png")
    widths, height = entry["widths"], entry["height"]
    rows = (len(widths) + fonts.GLYPHS_PER_ROW - 1) // fonts.GLYPHS_PER_ROW
    if size != (fonts.GLYPHS_PER_ROW * max(widths), rows * height):
        raise ValueError(f"{entry['name']}.png: expected {fonts.GLYPHS_PER_ROW * max(widths)}x{rows * height}, "
                         f"got {size[0]}x{size[1]}")
    if max(pixels) > 3:
        raise ValueError(f"{entry['name']}.png: pixel value above 3")
    flags = [int(c) for c in entry["flags"]] if "flags" in entry else None
    return fonts.Font(entry["first"], entry["last"], height, widths,
                      fonts.glyphs_from_atlas(pixels, widths, height), flags)


def _build(source: Path, e: dict) -> bytes:
    return fonts.build(font_from_file(source, e))


def pack_bank(ver: str, start: int, end: int, source: Path, name: str, tools: str) -> int:
    entries = load_index(source)
    out = ROOT / "build" / ver / "fonts"
    out.mkdir(parents=True, exist_ok=True)
    keys = [buildcache.digest(tools, e, buildcache.file_digest(source / f"{e['name']}.png"))
            for e in entries]
    packed = buildcache.cached_map("fonts", _build, [(source, e) for e in entries], keys)
    size = sum(map(len, packed))
    if size != end - start:
        raise ValueError(f"{name}: packs to {size:#x} bytes, the manifest claims {end - start:#x}")
    buildcache.write_if_changed(out / f"{name}.bin", b"".join(packed))
    asm, header, offset = [], ["// Generated by tools/fonts/pack_fonts.py; do not edit.",
                               "#pragma once", "", '#include "types.h"', ""], 0
    for entry, data in zip(entries, packed):
        label = f"g{entry['name']}"
        asm += [f".global {label}", f"{label}:",
                f'    .incbin "build/{ver}/fonts/{name}.bin", {offset}, {len(data)}']
        header.append(f"extern const u8 {label}[];")
        offset += len(data)
    buildcache.write_if_changed(out / f"{name}.s", "\n".join(asm) + "\n")
    header_path = ROOT / f"include/gen/{name}.h"
    buildcache.write_if_changed(header_path, "\n".join(header) + "\n")
    return len(entries)


def main() -> None:
    ver = sys.argv[1] if len(sys.argv) > 1 else "us"
    try:
        tools = buildcache.tool_digest()
        for start, end, source, name in font_rows(ver):
            print(f"{ver}: packed {name}: {pack_bank(ver, start, end, source, name, tools)} fonts, {end - start} bytes")
    except (OSError, ValueError) as exc:
        sys.exit(str(exc))


if __name__ == "__main__":
    main()
