#include "types.h"
#include "overworld/room_script_bytecode.h"

#include "v2/chain0.h"
#include "v2/chain1.h"
#include "v2/chain2.h"
#include "v2/chain3.h"
#include "v2/chain4.h"
#include "v2/chain5.h"
#include "v2/chain6.h"
#include "v2/chain7.h"
#include "v2/chain8.h"
