[book]
title = "HP3-GBA Decomp Notes"
description = "Notes for the HP3-GBA decompilation project"
authors = ["Variant9"]
language = "en"

[output.html]
git-repository-url = "https://github.com/holly-hacker/hp3-gba-decomp"
edit-url-template = "https://github.com/holly-hacker/hp3-gba-decomp/edit/main/mdbook/{path}"
mathjax-support = true
additional-css = ["custom.css"]
