#pragma once

// g_pItemTable has 132 slots; only 0-78 are normal items, 79 is a dummy
// end-of-list marker, 80-130 are the 51 famous wizard cards (order matches
// sFamousWizardCardNames), 131 is unused padding. See docs/formats/items.md.
#define ITEM_COUNT 132

#define ITEM_ORDINARY_BELT                            0
#define ITEM_LEATHER_BELT                             1
#define ITEM_ROPE                                     2
#define ITEM_SWEDISH_SHORTSNOUT_DRAGON_HIDE_BELT      3
#define ITEM_COMMON_WELSH_GREEN_DRAGON_HIDE_BELT      4
#define ITEM_ROMANIAN_LONGHORN_DRAGON_HIDE_BELT       5
#define ITEM_CHINESE_FIREBALL_DRAGON_HIDE_BELT        6
#define ITEM_HUNGARIAN_HORNTAIL_DRAGON_HIDE_BELT      7
#define ITEM_BRACELET                                 8
#define ITEM_BEADS                                    9
#define ITEM_POCKET_WATCH                             10
#define ITEM_QUIDDITCH_WRIST_GUARDS                   11
#define ITEM_HEAD_BAND                                12
#define ITEM_EAGLE_FEATHER_QUILL                      13
#define ITEM_CRYSTAL_BALL                             14
#define ITEM_DRAGON_LIVER                             15
#define ITEM_RABBIT_FUR_GLOVES                        16
#define ITEM_REMEMBRALL                               17
#define ITEM_SPELLOTAPE                               18
#define ITEM_GOLDEN_SNITCH                            19
#define ITEM_MITTENS                                  20
#define ITEM_LEATHER_GLOVES                           21
#define ITEM_QUIDDITCH_GLOVES                         22
#define ITEM_POTIONS_GLOVES                           23
#define ITEM_SWEDISH_SHORTSNOUT_DRAGON_HIDE_GLOVES    24
#define ITEM_COMMON_WELSH_GREEN_DRAGON_HIDE_GLOVES    25
#define ITEM_ROMANIAN_LONGHORN_DRAGON_HIDE_GLOVES     26
#define ITEM_CHINESE_FIREBALL_DRAGON_HIDE_GLOVES      27
#define ITEM_HUNGARIAN_HORNTAIL_DRAGON_HIDE_GLOVES    28
#define ITEM_SNEAKERS                                 29
#define ITEM_LEATHER_BOOTS                            30
#define ITEM_GALOSHES                                 31
#define ITEM_QUIDDITCH_BOOTS                          32
#define ITEM_SWEDISH_SHORTSNOUT_DRAGON_HIDE_BOOTS     33
#define ITEM_COMMON_WELSH_GREEN_DRAGON_HIDE_BOOTS     34
#define ITEM_ROMANIAN_LONGHORN_DRAGON_HIDE_BOOTS      35
#define ITEM_CHINESE_FIREBALL_DRAGON_HIDE_BOOTS       36
#define ITEM_HUNGARIAN_HORNTAIL_DRAGON_HIDE_BOOTS     37
#define ITEM_CAP                                      38
#define ITEM_BLACK_POINTED_HAT                        39
#define ITEM_REAR_ADMIRALS_HAT                        40
#define ITEM_QUIDDITCH_HELMET                         41
#define ITEM_SWEDISH_SHORTSNOUT_DRAGON_HIDE_CAP       42
#define ITEM_COMMON_WELSH_GREEN_DRAGON_HIDE_CAP       43
#define ITEM_ROMANIAN_LONGHORN_DRAGON_HIDE_CAP        44
#define ITEM_CHINESE_FIREBALL_DRAGON_HIDE_CAP         45
#define ITEM_HUNGARIAN_HORNTAIL_DRAGON_HIDE_CAP       46
#define ITEM_SCHOOL_ROBE                              47
#define ITEM_QUIDDITCH_ROBE                           48
#define ITEM_WINTER_CLOAK                             49
#define ITEM_POTIONS_ROBE                             50
#define ITEM_SWEDISH_SHORTSNOUT_DRAGON_HIDE_CLOAK     51
#define ITEM_COMMON_WELSH_GREEN_DRAGON_HIDE_CLOAK     52
#define ITEM_ROMANIAN_LONGHORN_DRAGON_HIDE_CLOAK      53
#define ITEM_CHINESE_FIREBALL_DRAGON_HIDE_CLOAK       54
#define ITEM_HUNGARIAN_HORNTAIL_DRAGON_HIDE_CLOAK     55
#define ITEM_WIGGENWELD_POTION                        56
#define ITEM_GRAND_WIGGENWELD_POTION                  57
#define ITEM_PEPPERUP_POTION                          58
#define ITEM_GRAND_PEPPERUP_POTION                    59
#define ITEM_ANTIDOTE_TO_COMMON_POISONS               60
#define ITEM_ANTI_PARALYSIS_POTION                    61
#define ITEM_RAT_TONIC                                62
#define ITEM_SHRIVELFIG                               63
#define ITEM_DAISY_ROOTS                              64
#define ITEM_RAT_SPLEEN                               65
#define ITEM_LEECH_JUICE                              66
#define ITEM_FIREBOLT                                 67
#define ITEM_SCABBERS                                 68
#define ITEM_HEDWIG                                   69
#define ITEM_CHOCOLATE_FROGS                          70
#define ITEM_CROOKSHANKS                              71
#define ITEM_TIME_TURNER                              72
#define ITEM_TREVOR                                   73
#define ITEM_A_BOOK_PAGE                              74
#define ITEM_VALVE_HANDLE                             75
#define ITEM_CHOCOLATE                                76
#define ITEM_DEAD_CATERPILLAR                         77
#define ITEM_THE_MONSTER_BOOK_OF_MONSTERS             78

#define SIMPLE_ITEMS_END                              79

#define ITEM_CARD_FULLBERT_THE_FEARFUL                80
#define ITEM_CARD_BEATRIX_BLOXAM                      81
#define ITEM_CARD_MERWYN_THE_MALICIOUS                82
#define ITEM_CARD_HUNGARIAN_HORNTAIL_DRAGON           83
#define ITEM_CARD_HEBRIDEAN_BLACK_DRAGON              84
#define ITEM_CARD_NORWEGIAN_RIDGEBACK_DRAGON          85
#define ITEM_CARD_XAVIER_RASTRICK                     86
#define ITEM_CARD_DYMPHNA_FURMAGE                     87
#define ITEM_CARD_YARDLEY_PLATT                       88
#define ITEM_CARD_MORGAN_LE_FEY                       89
#define ITEM_CARD_WENDELIN_THE_WEIRD                  90
#define ITEM_CARD_HONORIA_NUTCOMBE                    91
#define ITEM_CARD_JOCUNDA_SYKES                       92
#define ITEM_CARD_JUSTUS_PILLIWICKLE                  93
#define ITEM_CARD_ADALBERT_WAFFLING                   94
#define ITEM_CARD_EDGAR_STROULGER                     95
#define ITEM_CARD_MALODORA_GRYMM                      96
#define ITEM_CARD_LETICIA_SOMNOLENS                   97
#define ITEM_CARD_CORDELIA_MISERICORDIA               98
#define ITEM_CARD_CARLOTTA_PINKSTONE                  99
#define ITEM_CARD_UNICORN                             100
#define ITEM_CARD_MANTICORE                           101
#define ITEM_CARD_PHOENIX                             102
#define ITEM_CARD_BURDOCK_MULDOON                     103
#define ITEM_CARD_GONDOLINE_OLIPHANT                  104
#define ITEM_CARD_ALMERICK_SAWBRIDGE                  105
#define ITEM_CARD_MONTAGUE_KNIGHTLY                   106
#define ITEM_CARD_GLANMORE_PEAKES                     107
#define ITEM_CARD_ARTEMISA_LUFKIN                     108
#define ITEM_CARD_MERLIN                              109
#define ITEM_CARD_SIR_HERBERT_VARNEY                  110
#define ITEM_CARD_AMARILLO_LESTOAT                    111
#define ITEM_CARD_LADY_CARMILLA_SANGUINA              112
#define ITEM_CARD_DUMBLEDORE                          113
#define ITEM_CARD_QUEEN_MAEVE                         114
#define ITEM_CARD_HELGA_HUFFLEPUFF                    115
#define ITEM_CARD_BRIDGET_WENLOCK                     116
#define ITEM_CARD_MIRANDA_GOSHAWK                     117
#define ITEM_CARD_ROWENA_RAVENCLAW                    118
#define ITEM_CARD_GODRIC_GRYFFINDOR                   119
#define ITEM_CARD_ROLAND_KEGG                         120
#define ITEM_CARD_GWENOG_JONES                        121
#define ITEM_CARD_JOSCELIND_WADOCK                    122
#define ITEM_CARD_DUNBAR_OGLETHORPE                   123
#define ITEM_CARD_DEVLIN_WHITEHORN                    124
#define ITEM_CARD_CYPRIAN_YOUDLE                      125
#define ITEM_CARD_LEOPOLDINA_SMETHWYCK                126
#define ITEM_CARD_FELIX_SUMERBEE                      127
#define ITEM_CARD_RODERIC_PLUMPTON                    128
#define ITEM_CARD_BOWMAN_WRIGHT                       129
#define ITEM_CARD_HARRY_POTTER                        130

// 131 is unused padding
