const u8 g_abRoom05V1Chain3[] = {
    RS_ArmChainYield(1),
    RS_CancelObjectAnimSequence(0, 255),
    RS_SetQuestState(10, 25),
    // "There he is!"
    // "Let's get him and get back to..."
    RS_ShowRoomDialog(146),
    RS_DelayedRespawnRowAndRunChain(0, 6, 0),
    RS_QueueTileObjectMove(18, 0, 0, 0, 1500, 1),
    RS_DelayedRespawnRowAndRunChain(2, 0, 0),
    RS_SetTileObjectAnimState(6, 0),
    RS_DelayedRespawnRowAndRunChain(3, 9, 0),
    RS_DespawnTileObject(6, 0),
    RS_SetTileObjectAnimState(9, 0),
    RS_QueueTileObjectMove(0, 255, 0, 0, 1500, 1),
    RS_SetTileObjectAnimState(0, 8),
    RS_PlayScreenTransitionOut(),
    RS_DespawnTileObject(20, 0),
    RS_RemovePartyFollower(5),
    RS_PlaySoundById(156),
    RS_DelayedRespawnRowAndRunChain(1, 19, 0),
    RS_PlayScreenTransitionIn(),
    RS_SetQuestState(50, 27),
    RS_DelayedRespawnRowAndRunChain(1, 0, 0),
    // "Uhhh..."
    // "Harry!"
    RS_ShowRoomDialog(147),
    RS_DelayedRespawnRowAndRunChain(1, 0, 0),
    RS_SetTileObjectAnimState(0, 8),
    RS_DelayedRespawnRowAndRunChain(1, 0, 0),
    RS_ArmChainYield(0),
    RS_DespawnTileObject(1, 0),
    RS_DespawnTileObject(1, 1),
    RS_DelayedRespawnRowAndRunChainFrames(0, 25, 0),
    RS_DelayedRespawnRowAndRunChainFrames(0, 28, 0),
    RS_ArmChainYield(1),
    RS_SetTileObjectAnimStateWithSpeed(0, 255),
    RS_DelayedRespawnRowAndRunChain(1, 0, 0),
    RS_SetTileObjectAnimState(0, 8),
    RS_DelayedRespawnRowAndRunChain(1, 0, 0),
    RS_GotoIfQuestStateCompare(128, 0, 1, 7, 0, 0, 0),
    // "It's trying to get in! We have to bar the door!"
    RS_ShowRoomDialog(148),
    RS_DelayedRespawnRowAndRunChain(2, 0, 0),
    RS_SetTileObjectAnimState(0, 8),
    RS_GotoIfQuestStateCompare(128, 0, 1, 7, 0, 0, 0),
    RS_DelayedRespawnRowAndRunChain(2, 0, 0),
    RS_SetTileObjectAnimState(0, 8),
    RS_DelayedRespawnRowAndRunChain(3, 0, 0),
    RS_SetTileObjectAnimState(0, 8),
    RS_GotoIfQuestStateCompare(128, 0, 1, 7, 8, 0, 0),
    RS_End(),
};
