const u8 g_abRoom05V1Chain15[] = {
    RS_ArmChainYield(1),
    RS_CancelObjectAnimSequence(0, 255),
    RS_QueueTileObjectMove(0, 255, 0, 0, 1200, 0),
    RS_DelayedRespawnRowAndRunChain(1, 0, 0),
    RS_RemovePartyFollower(7),
    RS_DelayedRespawnRowAndRunChainFrames(0, 23, 0),
    RS_SetQuestState(0, 226),
    RS_SetQuestState(7, 6),
    RS_SetQuestState(0, 26),
    RS_SetQuestState(13, 25),
    RS_SetQuestState(1, 250),
    RS_DelayedRespawnRowAndRunChain(0, 21, 0),
    RS_PlayScreenTransitionIn(),
    RS_SetTileObjectAnimStateWithSpeed(0, 255),
    RS_End(),
};
