#!/usr/bin/env python3
"""Pack every room-graphics manifest row from data/room_graphics/.

A row `room-graphics <start> <end> <dir> <name>` claims one room's 14
contiguous resources (see roomgfx.py). The packed bytes and the assembly that
labels each resource go under build/<ver>/room_graphics/. The labels are the
name without its "Graphics" suffix plus BgMap0-3, BgBlocks0-3,
CollisionBehavior, CollisionMap, TilesetA, PaletteA, TilesetB and PaletteB;
the room table refers to them.

The C declarations of those labels, and of each room's blob, are written to
include/gen/RoomGraphics.h; they depend only on the room names.

Usage: pack_room_graphics.py <ver>
"""
import re
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent))
from roomfiles import read_room_dir
from roomgfx import build_room

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))
import stamp

ROOT = Path(__file__).resolve().parents[2]
LABELS = {f"map{n}": f"BgMap{n}" for n in range(4)}
LABELS.update({f"blocks{n}": f"BgBlocks{n}" for n in range(4)})
LABELS.update({"collision_behavior": "CollisionBehavior", "collision_map": "CollisionMap",
               "tileset_a": "TilesetA", "palette_a": "PaletteA",
               "tileset_b": "TilesetB", "palette_b": "PaletteB"})


def room_graphics_rows(ver: str):
    path = ROOT / f"regions.{ver}.txt"
    for lineno, raw in enumerate(path.read_text().splitlines(), 1):
        parts = raw.split("#", 1)[0].split()
        if not parts or parts[0] != "room-graphics":
            continue
        if len(parts) != 5:
            raise SystemExit(f"{path}:{lineno}: expected room-graphics <start> <end> <dir> <name>")
        _, start, end, source, name = parts
        if not re.fullmatch(r"\w+Graphics", name):
            raise SystemExit(f"{path}:{lineno}: room graphics name must end in Graphics")
        yield int(start, 16), int(end, 16), ROOT / source, name


def write_header(prefixes: list[str]) -> None:
    lines = ["// Generated by tools/room_graphics/pack_room_graphics.py; do not edit.", "#pragma once", "",
             '#include "types.h"', ""]
    for prefix in prefixes:
        lines += [f"extern const u8 {prefix}{label}[];" for label in [*LABELS.values(), "Blob"]]
        lines.append("")
    (ROOT / "include/gen/RoomGraphics.h").write_text("\n".join(lines).rstrip("\n") + "\n")


def main() -> None:
    ver = sys.argv[1] if len(sys.argv) > 1 else "us"
    out_dir = ROOT / "build" / ver / "room_graphics"
    out_dir.mkdir(parents=True, exist_ok=True)
    rows = list(room_graphics_rows(ver))
    write_header([name[:-len("Graphics")] for _, _, _, name in rows])
    for start, end, source, name in rows:
        if stamp.fresh(out_dir / f"{name}.s", source, ROOT / f"regions.{ver}.txt"):
            continue
        sections = build_room(read_room_dir(source))
        data = b"".join(b for _, b in sections)
        if len(data) != end - start:
            raise SystemExit(f"{name}: packs to {len(data)} bytes, the manifest claims {end - start}")
        (out_dir / f"{name}.bin").write_bytes(data)
        prefix = name[:-len("Graphics")]
        lines, offset = [], 0
        for section, blob in sections:
            label = prefix + LABELS[section]
            lines += [f".global {label}", f"{label}:",
                      f'    .incbin "build/{ver}/room_graphics/{name}.bin", {offset}, {len(blob)}']
            offset += len(blob)
        (out_dir / f"{name}.s").write_text("\n".join(lines) + "\n")


if __name__ == "__main__":
    main()
