#!/usr/bin/env python3
"""One-time bootstrap: extract the Folio Bruti monster stat table from
the US baserom into curated, editable JSON under data/monsters/. See
docs/formats/folio_bruti.md for how the table's address/stride/count and
each field were identified.

Mirrors tools/text/text_migrate.py's role for dialog text: data/monsters/
is NOT regenerated by `just build` -- it's local, user-editable source,
and it's gitignored, same footing as the baserom, per hard rule 2
(CLAUDE.md). Every clone needs to run this once (see the
`migrate-monsters` recipe) before building. Always overwrites existing
files; do not run it against already-hand-edited content.

Table content is not yet confirmed identical between US/JP (unlike
Krawall/dialog text), so this only ever reads baserom.us.gba for now --
see docs/formats/folio_bruti.md's "What's NOT yet known".

Each record also gets leading "_name"/"_description" fields: the
monster's English Folio Bruti name and description, decoded straight
from the ROM's dialog text table via NAME_STRING_ID_BASE/
DESC_STRING_ID_BASE + index (see docs/formats/folio_bruti.md). These are
read-only annotations for human readability, not part of the real
24-byte record -- pack_monsters.py ignores both (see
monster_codec.pack_record).

Only indices 0..FOLIO_BRUTI_COUNT-1 are real Folio Bruti bestiary
entries (PROVEN live, see docs/formats/folio_bruti.md "The grid
boundary") -- indices at/past that cutoff are boss/story battle
participants that share this table but were never wired into the
bestiary UI, so DESC_STRING_ID_BASE + index doesn't land on a real
description there (confirmed: it decodes to unrelated strings -- spell
names, battle-HUD text, etc.). `_description` is set to `null` for
those indices rather than showing that garbage as if it were real
bestiary text. `_name` is kept as-is past the cutoff -- unlike
`_description`, it's frequently still a real string used elsewhere in
the game (e.g. "Crabbe", "Draco", boss names), just not a Folio Bruti
bestiary name; see docs/formats/folio_bruti.md for the known exception
(index 68) where even `_name` lands on unrelated text.

Usage: monster_migrate.py   (reads baserom.us.gba, writes data/monsters/monsters.json)
"""
import json
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent))
from monster_codec import (
    DESC_STRING_ID_BASE, FOLIO_BRUTI_COUNT, MONSTER_COUNT, MONSTER_TABLE_ADDR, NAME_STRING_ID_BASE, RECORD_SIZE,
    unpack_record,
)

sys.path.insert(0, str(Path(__file__).parent.parent / "text"))
from decode_dialog_text import decode_dialog_text

ROM_BASE = 0x08000000


def decode_string(rom: bytes, string_id: int) -> str:
    data = decode_dialog_text(rom, 0, string_id)  # lang 0 = English US
    data = data.rstrip(b"\x00")
    return data.decode("latin-1")


def main() -> None:
    with open("baserom.us.gba", "rb") as f:
        rom = f.read()

    base = MONSTER_TABLE_ADDR - ROM_BASE
    records = []
    for i in range(MONSTER_COUNT):
        off = base + i * RECORD_SIZE
        record = {
            "_name": decode_string(rom, NAME_STRING_ID_BASE + i),
            "_description": decode_string(rom, DESC_STRING_ID_BASE + i) if i < FOLIO_BRUTI_COUNT else None,
        }
        record.update(unpack_record(rom[off:off + RECORD_SIZE]))
        records.append(record)

    out_dir = Path("data/monsters")
    out_dir.mkdir(parents=True, exist_ok=True)
    path = out_dir / "monsters.json"
    path.write_text(json.dumps(records, indent=1) + "\n")
    print(f"{MONSTER_COUNT} monster records -> {path}", file=sys.stderr)


if __name__ == "__main__":
    main()
