#!/usr/bin/env python3
"""Pack every graphics group of regions.<ver>.txt from data/graphics/.

Every item of every group under graphics/ is built through the build cache
(one process pool for all misses), so each feature's header,
include/gen/graphics/<feature>.h, declares the labels of all its groups and
is the same for every version. Each group of this version is written as
build/<ver>/graphics/<Group>.bin plus <Group>.s, which labels each piece
with an .incbin of its slice. See tools/graphics/runs.py.

Usage: pack_graphics.py <ver>
"""
import sys
from pathlib import Path

import runs
import buildcache


def _build(kind: str, source: Path, options: dict, item: dict) -> list[tuple[str, bytes]]:
    return runs.KINDS[kind].build(source, options, item)


def write_header(feature: str, groups: list[tuple[str, list[str]]]) -> None:
    lines = ["/* Generated by tools/graphics/pack_graphics.py; do not edit. */", "#pragma once", "",
             '#include "types.h"']
    for name, labels in groups:
        lines += ["", f"/* {name} */"] + [f"extern const u8 {label}[];" for label in labels]
    buildcache.write_if_changed(runs.header_path(feature), "\n".join(lines) + "\n")


def main() -> None:
    if len(sys.argv) != 2:
        sys.exit(f"usage: {sys.argv[0]} <ver>")
    ver = sys.argv[1]
    try:
        features = runs.features()
        settings = {}
        for feature, groups in features.items():
            settings.update(runs.load(feature, groups))

        tools = buildcache.tool_digest()
        jobs, keys, owners = [], [], []
        for groups in features.values():
            for group in groups:
                for run, run_settings in zip(group.runs, settings[group.name]):
                    kind = runs.KINDS[run.kind]
                    for item in run_settings[kind.ITEMS]:
                        jobs.append((run.kind, group.source, run.options, item))
                        keys.append(buildcache.digest(
                            tools, run.kind, run.options, item,
                            [buildcache.file_digest(group.source / f) for f in kind.item_files(item)]))
                        owners.append(group.name)
        pieces: dict[str, list[tuple[str, bytes]]] = {name: [] for name in settings}
        for name, labeled in zip(owners, buildcache.cached_map("graphics", _build, jobs, keys)):
            pieces[name].extend(labeled)

        for feature, groups in features.items():
            write_header(feature, [(g.name, [label for label, _ in pieces[g.name]]) for g in groups])

        out = runs.ROOT / "build" / ver / "graphics"
        rows = runs.rows(ver, {g.name: g for gs in features.values() for g in gs})
        for row in rows:
            name = row.group.name
            data = b"".join(piece for _, piece in pieces[name])
            if len(data) != row.end - row.start:
                raise ValueError(f"{name}: packs to {len(data):#x} bytes, "
                                 f"regions.{ver}.txt claims {row.end - row.start:#x}")
            bin_path = (out / f"{name}.bin").relative_to(runs.ROOT).as_posix()
            asm, offset = [], 0
            for label, piece in pieces[name]:
                asm += [f".global {label}", f"{label}:", f'    .incbin "{bin_path}", {offset:#x}, {len(piece):#x}']
                offset += len(piece)
            buildcache.write_if_changed(out / f"{name}.bin", data)
            buildcache.write_if_changed(out / f"{name}.s", "\n".join(asm) + "\n")
        print(f"{ver}: packed {len(rows)} graphics groups ({len(jobs)} items, {len(features)} feature headers)")
    except (OSError, ValueError, TypeError, KeyError) as exc:
        sys.exit(str(exc))


if __name__ == "__main__":
    main()
