#!/usr/bin/env python3
"""Pack every graphics run of regions.<ver>.txt from data/graphics/.

Every item of every run is built through the build cache (one process pool
for all misses). Each run of this version is written as
build/<ver>/graphics/<Name>.bin plus <Name>.s, which labels each piece with
an .incbin of its slice. Each feature's header,
include/gen/graphics/<feature>.h, declares the labels of all its runs, also
those only another version uses, so headers are the same for every version.
See tools/graphics/runs.py.

Usage: pack_graphics.py <ver>
"""
import sys

import runs
import buildcache


def _build(kind: str, source, name: str, run: dict, item) -> list[tuple[str, bytes]]:
    return runs.KINDS[kind].build(source, name, run, item)


def write_header(feature, pieces: list[tuple[str, list[tuple[str, bytes]]]]) -> None:
    lines = ["/* Generated by tools/graphics/pack_graphics.py; do not edit. */", "#pragma once", "",
             '#include "types.h"']
    for name, labeled in pieces:
        lines += ["", f"/* {name} */"] + [f"extern const u8 {label}[];" for label, _ in labeled]
    buildcache.write_if_changed(runs.header_path(feature), "\n".join(lines) + "\n")


def main() -> None:
    if len(sys.argv) != 2:
        sys.exit(f"usage: {sys.argv[0]} <ver>")
    ver = sys.argv[1]
    try:
        everywhere = runs.all_rows()
        kinds = {name: row.kind for name, row in everywhere.items()}
        features = {}
        for feature in sorted({row.feature for row in everywhere.values()}):
            features[feature] = runs.load(feature, kinds)
            missing = {n for n, r in everywhere.items() if r.feature == feature} - set(features[feature])
            if missing:
                raise ValueError(f"{feature / runs.INDEX}: no settings for {', '.join(sorted(missing))}")

        tools = buildcache.tool_digest()
        jobs, keys, owners = [], [], []
        for feature, feature_runs in features.items():
            for name, run in feature_runs.items():
                kind = runs.KINDS[kinds[name]]
                settings = {k: v for k, v in run.items() if k != kind.ITEMS}
                for item in runs.items(kinds[name], run):
                    jobs.append((kinds[name], feature, name, settings, item))
                    keys.append(buildcache.digest(
                        tools, kinds[name], name, settings, item,
                        [buildcache.file_digest(feature / f) for f in kind.item_files(run, item)]))
                    owners.append(name)
        built = buildcache.cached_map("graphics", _build, jobs, keys)
        pieces: dict[str, list[tuple[str, bytes]]] = {}
        for name, labeled in zip(owners, built):
            pieces.setdefault(name, []).extend(labeled)

        for feature, feature_runs in features.items():
            write_header(feature, [(name, pieces[name]) for name in feature_runs])

        out = runs.ROOT / "build" / ver / "graphics"
        rows = runs.rows(ver)
        for row in rows:
            data = b"".join(d for _, d in pieces[row.name])
            if len(data) != row.end - row.start:
                raise ValueError(f"{row.name}: packs to {len(data):#x} bytes, "
                                 f"regions.{ver}.txt claims {row.end - row.start:#x}")
            bin_path = (out / f"{row.name}.bin").relative_to(runs.ROOT).as_posix()
            asm, offset = [], 0
            for label, piece in pieces[row.name]:
                asm += [f".global {label}", f"{label}:", f'    .incbin "{bin_path}", {offset}, {len(piece)}']
                offset += len(piece)
            buildcache.write_if_changed(out / f"{row.name}.bin", data)
            buildcache.write_if_changed(out / f"{row.name}.s", "\n".join(asm) + "\n")
        print(f"{ver}: packed {len(rows)} graphics runs ({len(jobs)} items, "
              f"{len(features)} feature headers)")
    except (OSError, ValueError, TypeError, KeyError) as exc:
        sys.exit(str(exc))


if __name__ == "__main__":
    main()
