#include "types.h"
#include "overworld/room_script_bytecode.h"

#include "v1/chain0.h"
#include "v1/chain1.h"
#include "v1/chain2.h"
#include "v1/chain3.h"
#include "v1/chain4.h"
#include "v1/chain5.h"
#include "v1/chain6.h"
#include "v1/chain7.h"
#include "v1/chain8.h"
#include "v1/chain9.h"
#include "v1/chain10.h"
#include "v1/chain11.h"
#include "v1/chain12.h"
#include "v1/chain13.h"
#include "v1/chain14.h"
