#include "types.h"
#include "graphics/display.h"
#include "minigame/divination_tea.h"

// BG2's animation, registered with g_dwDivinationTeaBg2Control.
const BgTileAnimation64 g_DivinationTeaTable = {
    2, 64, 2, 0x1000,
    {
        { gDivinationTeaFrame001, 2 },
        { gDivinationTeaFrame002, 2 },
        { gDivinationTeaFrame003, 2 },
        { gDivinationTeaFrame004, 2 },
        { gDivinationTeaFrame005, 2 },
        { gDivinationTeaFrame006, 2 },
        { gDivinationTeaFrame007, 2 },
        { gDivinationTeaFrame008, 2 },
        { gDivinationTeaFrame009, 2 },
        { gDivinationTeaFrame010, 2 },
        { gDivinationTeaFrame011, 2 },
        { gDivinationTeaFrame012, 2 },
        { gDivinationTeaFrame013, 2 },
        { gDivinationTeaFrame014, 2 },
        { gDivinationTeaFrame015, 2 },
        { gDivinationTeaFrame016, 2 },
        { gDivinationTeaFrame017, 2 },
        { gDivinationTeaFrame018, 2 },
        { gDivinationTeaFrame019, 2 },
        { gDivinationTeaFrame020, 2 },
        { gDivinationTeaFrame021, 2 },
        { gDivinationTeaFrame022, 2 },
        { gDivinationTeaFrame023, 2 },
        { gDivinationTeaFrame024, 2 },
        { gDivinationTeaFrame025, 2 },
        { gDivinationTeaFrame026, 2 },
        { gDivinationTeaFrame027, 2 },
        { gDivinationTeaFrame028, 2 },
        { gDivinationTeaFrame029, 2 },
        { gDivinationTeaFrame030, 2 },
        { gDivinationTeaFrame031, 2 },
        { gDivinationTeaFrame032, 2 },
        { gDivinationTeaFrame033, 2 },
        { gDivinationTeaFrame034, 2 },
        { gDivinationTeaFrame035, 2 },
        { gDivinationTeaFrame036, 2 },
        { gDivinationTeaFrame037, 2 },
        { gDivinationTeaFrame038, 2 },
        { gDivinationTeaFrame039, 2 },
        { gDivinationTeaFrame040, 2 },
        { gDivinationTeaFrame041, 2 },
        { gDivinationTeaFrame042, 2 },
        { gDivinationTeaFrame043, 2 },
        { gDivinationTeaFrame044, 2 },
        { gDivinationTeaFrame045, 2 },
        { gDivinationTeaFrame046, 2 },
        { gDivinationTeaFrame047, 2 },
        { gDivinationTeaFrame048, 2 },
        { gDivinationTeaFrame049, 2 },
        { gDivinationTeaFrame050, 2 },
        { gDivinationTeaFrame051, 2 },
        { gDivinationTeaFrame052, 2 },
        { gDivinationTeaFrame053, 2 },
        { gDivinationTeaFrame054, 2 },
        { gDivinationTeaFrame055, 2 },
        { gDivinationTeaFrame056, 2 },
        { gDivinationTeaFrame057, 2 },
        { gDivinationTeaFrame058, 2 },
        { gDivinationTeaFrame059, 2 },
        { gDivinationTeaFrame060, 2 },
        { gDivinationTeaFrame061, 2 },
        { gDivinationTeaFrame062, 2 },
        { gDivinationTeaFrame063, 2 },
        { gDivinationTeaFrame064, 2 },
    },
};
