#include "types.h"

const u8 sFamousWizardCardNames[51][32] = {
    "02 Fullbert The Fearful",
    "03 Beatrix Bloxam",
    "01 Merwyn The Malicious",
    "38 Hungarian Horntail Dragon",
    "37 Hebridean Black Dragon",
    "40 Norwegian Ridgeback Dragon",
    "07 Xavier Rastrick",
    "09 Dymphna Furmage",
    "08 Yardley Platt",
    "10 Morgan Le Fey",
    "12 Wendelin The Weird",
    "11 Honoria Nutcombe",
    "13 Jocunda Sykes",
    "14 Justus Pilliwickle",
    "16 Adalbert Waffling",
    "15 Edgar Stroulger",
    "12 Malodora Grymm",
    "13 Leticia Somnolens",
    "15 Cordelia Misericordia",
    "20 Carlotta PinkStone",
    "28 Unicorn",
    "27 Manticore",
    "30 Phoenix",
    "24 Burdock Muldoon",
    "26 Gondoline Oliphant",
    "25 Almerick Sawbridge",
    "28 Montague Knightly",
    "29 Glanmore Peakes",
    "27 Artemisa Lufkin",
    "30 Merlin",
    "03 Sir Herbert Varney",
    "02 Amarillo Lestoat",
    "01 Lady Carmilla Sanguina",
    "44 Dumbledore",
    "45 Queen Maeve",
    "46 Helga Hufflepuff",
    "41 Bridget Wenlock",
    "43 Miranda Goshawk",
    "47 Rowena Ravenclaw",
    "50 Godric Gryffindor",
    "51 Roland Kegg",
    "53 Gwenog Jones",
    "52 Joscelind Wadock",
    "56 Dunbar Oglethorpe",
    "55 Devlin Whitehorn",
    "54 Cyprian Youdle",
    "57 Leopoldina Smethwyck",
    "59 Felix Sumerbee",
    "58 Roderic Plumpton",
    "60 Bowman Wright",
    "71 Harry Potter",
};
