#!/usr/bin/env python3
"""One-time bootstrap: convert raw Krawall data from the US baserom into
the curated JSON+WAV format under data/audio/. See docs/formats/krawall.md.

Module/pattern/sample *content* is proven byte-identical between US and JP
(docs/formats/krawall.md's Confirmed stats), so this only ever needs to
read the US ROM -- data/audio/ is version-independent. Per-version
addresses live in regions.<ver>.txt's krawall-module/krawall-samples rows
instead (see tools/krawall/gen_krawall_regions.py, which computes those from the
same address tables this script uses).

data/audio/ is NOT regenerated by `just build` -- it's meant to be
user-editable local source for future modding. It's also gitignored, same
footing as the baserom, per hard rule 2 (see AGENTS.md): every clone needs
to run this once (see the `extract-krawall` recipe) before building.

Names default to Module<N>/Sample<N> but can be overridden via
krawall_names.txt ('<module|sample> <index> <Name>' lines, see
krawall_codec.py's load_krawall_names) -- shared across US/JP since
content is version-independent. Re-run this any time krawall_names.txt
changes to rename already-extracted content; it removes the old
default-named file(s) when a fresh custom name supersedes them, but does
NOT clean up a *previous* custom name if you rename twice (rare enough
not to be worth automating yet -- delete the stale file by hand). It
always overwrites existing files; do not run it against already-hand-edited
content.

Usage: extract_krawall.py   (reads baserom.us.gba, writes data/audio/)
"""
import io
import json
import struct
import sys
import wave
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent))
from dump_krawall import (
    SAMPLE_LIST, MODULE_ADDRS, sample_span, pattern_span, module_header_span,
    u8, u32, is_rom_ptr,
)
from krawall_codec import decompress_pattern, load_krawall_names, resolve_names

VER = "us"
LOOP_NAMES = {0: "none", 1: "forward", 2: "pingpong"}


def s8(data: bytes, off: int) -> int:
    return struct.unpack_from("<b", data, off)[0]


def pcm_to_wav(pcm: bytes, sample_rate: int) -> bytes:
    # Despite the struct field being C-declared `signed char data[1]`, the
    # actual stored bytes are offset-binary -- 128 is the zero/silence
    # reference, not 0 -- confirmed empirically: raw ROM bytes are 5-9x
    # smoother (far smaller consecutive-sample deltas) read that way than
    # as two's-complement signed. This is exactly WAV's own native 8-bit
    # PCM convention, so the raw bytes go in as-is, no transform at all.
    buf = io.BytesIO()
    with wave.open(buf, "wb") as w:
        w.setnchannels(1)
        w.setsampwidth(1)
        w.setframerate(sample_rate)
        w.writeframes(pcm)
    return buf.getvalue()


def parse_sample(data: bytes, addr: int) -> tuple[dict, bytes]:
    meta = {
        "loopLength": u32(data, addr),
        "c2Freq": u32(data, addr + 8),
        "fineTune": s8(data, addr + 12),
        "relativeNote": s8(data, addr + 13),
        "volDefault": u8(data, addr + 14),
        "panDefault": s8(data, addr + 15),
        "loop": LOOP_NAMES[u8(data, addr + 16)],
        "hq": bool(u8(data, addr + 17)),
    }
    span = sample_span(data, addr)
    pcm = data[addr + 18: addr + span]
    return meta, pcm


def parse_module(data: bytes, addr: int) -> tuple[dict, list[int]]:
    """Returns (module dict without "patterns", pattern addrs in table order)."""
    _, pattern_ptrs = module_header_span(data, addr)

    channels = u8(data, addr)
    num_orders = u8(data, addr + 1)
    song_restart = u8(data, addr + 2)
    order_bytes = data[addr + 3: addr + 3 + num_orders]
    order = [None if b == 254 else b for b in order_bytes]
    channel_pan = [s8(data, addr + 3 + 256 + i) for i in range(channels)]

    off = addr + 3 + 256 + 32 + 64
    module = {
        "channels": channels,
        "songRestart": song_restart,
        "channelPan": channel_pan,
        "order": order,
        "volGlobal": u8(data, off),
        "initSpeed": u8(data, off + 1),
        "initBPM": u8(data, off + 2),
        "flagInstrumentBased": bool(u8(data, off + 3)),
        "flagLinearSlides": bool(u8(data, off + 4)),
        "flagFastVolSlides": bool(u8(data, off + 5)),
    }
    return module, pattern_ptrs


def parse_pattern(data: bytes, addr: int, sample_names_by_index: dict[int, str]) -> dict:
    rows = u8(data, addr + 32)
    span = pattern_span(data, addr)
    body = data[addr + 33: addr + span]
    decoded = decompress_pattern(body, rows)
    for row in decoded:
        for ev in row:
            instr = ev.get("instrument")
            if instr:
                ev["instrument"] = sample_names_by_index[instr]
            elif "instrument" in ev:
                del ev["instrument"]
    return {"rows": decoded}


def remove_stale(dir_: Path, default_name: str, resolved_name: str, extra_exts: tuple[str, ...] = ()) -> None:
    """If a custom name superseded the default Module<N>/Sample<N> one,
    remove the now-orphaned default-named file(s) left by an earlier run."""
    if resolved_name == default_name:
        return
    for ext in (".json",) + extra_exts:
        stale = dir_ / f"{default_name}{ext}"
        if stale.exists():
            stale.unlink()


def main() -> None:
    with open(f"baserom.{VER}.gba", "rb") as f:
        data = f.read()

    module_name_overrides, sample_name_overrides = load_krawall_names()

    sample_addr, sample_count = SAMPLE_LIST[VER]
    sample_names = resolve_names("sample", sample_count, sample_name_overrides)
    samples_dir = Path("data/audio/samples")
    samples_dir.mkdir(parents=True, exist_ok=True)

    sample_names_by_index: dict[int, str] = {}
    for i in range(sample_count):
        ptr = u32(data, sample_addr + i * 4)
        if not is_rom_ptr(ptr):
            sys.exit(f"sample list entry {i} is not a ROM pointer")
        addr = ptr & 0x1FFFFFF
        meta, pcm = parse_sample(data, addr)
        meta["index"] = i  # authoritative ROM/instrument order -- see pack_krawall.py
        name = sample_names[i]
        sample_names_by_index[i + 1] = name  # patterns reference 1-based index
        remove_stale(samples_dir, f"Sample{i}", name, extra_exts=(".wav",))
        (samples_dir / f"{name}.json").write_text(json.dumps(meta, indent=2) + "\n")
        (samples_dir / f"{name}.wav").write_bytes(pcm_to_wav(pcm, meta["c2Freq"]))
    print(f"wrote {sample_count} samples", file=sys.stderr)

    module_names = resolve_names("module", len(MODULE_ADDRS[VER]), module_name_overrides)
    modules_dir = Path("data/audio/modules")
    modules_dir.mkdir(parents=True, exist_ok=True)
    for m_i, m_addr in enumerate(MODULE_ADDRS[VER]):
        module, pattern_addrs = parse_module(data, m_addr)
        module["patterns"] = [
            parse_pattern(data, p_addr, sample_names_by_index) for p_addr in pattern_addrs
        ]
        name = module_names[m_i]
        remove_stale(modules_dir, f"Module{m_i}", name)
        (modules_dir / f"{name}.json").write_text(json.dumps(module, indent=2) + "\n")
    print(f"wrote {len(MODULE_ADDRS[VER])} modules", file=sys.stderr)


if __name__ == "__main__":
    main()
