#include "types.h"
#include "graphics/audio.h"

// Indexed by sound id (PlaySoundById). Sample rows index g_aSoundSamples, variant rows index
// g_aSoundVariants.
const SoundConfigRow g_aSoundConfig[179] = {
    { SoundModeSample, 0 }, { SoundModeSample, 1 }, { SoundModeSample, 2 },
    { SoundModeSample, 3 }, { SoundModeSample, 4 }, { SoundModeSample, 5 },
    { SoundModeSample, 6 }, { SoundModeSample, 7 }, { SoundModeSample, 8 },
    { SoundModeSample, 9 }, { SoundModeSample, 10 }, { SoundModeSample, 11 },
    { SoundModeSample, 12 }, { SoundModeSample, 13 }, { SoundModeSample, 14 },
    { SoundModeSample, 15 }, { SoundModeSample, 16 }, { SoundModeSample, 17 },
    { SoundModeSample, 18 }, { SoundModeSample, 19 }, { SoundModeSample, 20 },
    { SoundModeSample, 21 }, { SoundModeSample, 22 }, { SoundModeSample, 23 },
    { SoundModeVariants, 0 }, { SoundModeSample, 24 }, { SoundModeSample, 25 },
    { SoundModeSample, 26 }, { SoundModeSample, 27 }, { SoundModeSample, 28 },
    { SoundModeSample, 29 }, { SoundModeSample, 30 }, { SoundModeVariants, 1 },
    { SoundModeSample, 31 }, { SoundModeSample, 32 }, { SoundModeSample, 33 },
    { SoundModeSample, 34 }, { SoundModeSample, 35 }, { SoundModeSample, 36 },
    { SoundModeSample, 37 }, { SoundModeSample, 38 }, { SoundModeSample, 39 },
    { SoundModeSample, 40 }, { SoundModeSample, 41 }, { SoundModeSample, 42 },
    { SoundModeSample, 43 }, { SoundModeSample, 44 }, { SoundModeSample, 45 },
    { SoundModeSample, 46 }, { SoundModeSample, 47 }, { SoundModeSample, 48 },
    { SoundModeSample, 49 }, { SoundModeSample, 50 }, { SoundModeSample, 51 },
    { SoundModeSample, 52 }, { SoundModeSample, 53 }, { SoundModeSample, 54 },
    { SoundModeSample, 55 }, { SoundModeVariants, 2 }, { SoundModeSample, 56 },
    { SoundModeVariants, 3 }, { SoundModeSample, 57 }, { SoundModeSample, 58 },
    { SoundModeSample, 59 }, { SoundModeSample, 60 }, { SoundModeSample, 61 },
    { SoundModeSample, 62 }, { SoundModeSample, 63 }, { SoundModeSample, 64 },
    { SoundModeSample, 65 }, { SoundModeSample, 66 }, { SoundModeSample, 67 },
    { SoundModeSample, 68 }, { SoundModeSample, 69 }, { SoundModeSample, 70 },
    { SoundModeSample, 71 }, { SoundModeSample, 72 }, { SoundModeSample, 73 },
    { SoundModeSample, 74 }, { SoundModeSample, 75 }, { SoundModeSample, 76 },
    { SoundModeSample, 77 }, { SoundModeSample, 78 }, { SoundModeSample, 79 },
    { SoundModeSample, 80 }, { SoundModeSample, 81 }, { SoundModeSample, 82 },
    { SoundModeSample, 83 }, { SoundModeSample, 84 }, { SoundModeSample, 85 },
    { SoundModeSample, 86 }, { SoundModeSample, 87 }, { SoundModeSample, 88 },
    { SoundModeSample, 89 }, { SoundModeSample, 90 }, { SoundModeSample, 91 },
    { SoundModeSample, 92 }, { SoundModeSample, 93 }, { SoundModeSample, 94 },
    { SoundModeSample, 95 }, { SoundModeSample, 96 }, { SoundModeSample, 97 },
    { SoundModeSample, 98 }, { SoundModeSample, 99 }, { SoundModeSample, 100 },
    { SoundModeSample, 101 }, { SoundModeSample, 102 }, { SoundModeSample, 103 },
    { SoundModeSample, 104 }, { SoundModeSample, 105 }, { SoundModeSample, 106 },
    { SoundModeSample, 107 }, { SoundModeSample, 108 }, { SoundModeSample, 109 },
    { SoundModeSample, 110 }, { SoundModeSample, 111 }, { SoundModeSample, 112 },
    { SoundModeSample, 113 }, { SoundModeSample, 114 }, { SoundModeSample, 115 },
    { SoundModeSample, 116 }, { SoundModeSample, 117 }, { SoundModeSample, 118 },
    { SoundModeSample, 119 }, { SoundModeSample, 120 }, { SoundModeSample, 121 },
    { SoundModeSample, 122 }, { SoundModeSample, 123 }, { SoundModeSample, 124 },
    { SoundModeSample, 125 }, { SoundModeSample, 126 }, { SoundModeSample, 127 },
    { SoundModeSample, 128 }, { SoundModeSample, 129 }, { SoundModeSample, 130 },
    { SoundModeSample, 131 }, { SoundModeSample, 132 }, { SoundModeSample, 133 },
    { SoundModeSample, 134 }, { SoundModeSample, 135 }, { SoundModeVariants, 4 },
    { SoundModeSample, 136 }, { SoundModeSample, 137 }, { SoundModeSample, 138 },
    { SoundModeSample, 139 }, { SoundModeSample, 140 }, { SoundModeSample, 141 },
    { SoundModeSample, 142 }, { SoundModeSample, 143 }, { SoundModeSample, 144 },
    { SoundModeSample, 145 }, { SoundModeSample, 146 }, { SoundModeSample, 147 },
    { SoundModeSample, 148 }, { SoundModeSample, 149 }, { SoundModeVariants, 5 },
    { SoundModeSample, 150 }, { SoundModeVariants, 6 }, { SoundModeSample, 151 },
    { SoundModeVariants, 7 }, { SoundModeVariants, 8 }, { SoundModeSample, 152 },
    { SoundModeVariants, 9 }, { SoundModeVariants, 10 }, { SoundModeSample, 153 },
    { SoundModeVariants, 12 }, { SoundModeVariants, 11 }, { SoundModeSample, 154 },
    { SoundModeVariants, 13 }, { SoundModeVariants, 14 }, { SoundModeSample, 155 },
    { SoundModeSample, 156 }, { SoundModeSample, 157 }, { SoundModeSample, 158 },
    { SoundModeSample, 159 }, { SoundModeSample, 160 }, { SoundModeSample, 161 },
    { SoundModeSample, 162 }, { SoundModeSample, 163 },
};
