const u8 g_abRoom15V1Chain41[] = {
    RS_ArmChainYield(1),
    RS_Unk02(14, 0, 1),
    RS_DespawnRoomRowObjects(14),
    RS_DespawnRoomRowObjects(13),
    RS_DespawnRoomRowObjects(11),
    RS_RecruitPartyFollower(6),
    RS_RecruitPartyFollower(7),
    RS_DespawnRoomRowObjects(12),
    RS_ClearQuestStateUpperHalf(),
    RS_SetQuestState(19, 25),
    RS_SetStoryStage(4),
    RS_SetTileObjectAnimStateWithSpeed(0, 255),
    RS_End(),
};
