const u8 g_abRoom15V1Chain27[] = {
    RS_ArmChainYield(1),
    // "This is very easy. I bet you're not dangerous at all, are you, you ugly great brute?"
    RS_ShowRoomDialog(269),
    RS_PlaySoundById(57),
    RS_Unk02(10, 1, 8),
    RS_SetTileObjectSpecialFlag(13, 0, 1),
    RS_SetTileObjectSpecialFlag(10, 1, 1),
    RS_ArmChainYield(0),
    RS_PlayTileObjectAnimation(13, 0, 20),
    RS_PlaySoundById(55),
    RS_DelayedRespawnRowAndRunChain(1, 0, 0),
    RS_PlaySoundById(58),
    RS_PlayTileObjectAnimation(10, 1, 15),
    RS_PlaySoundById(59),
    RS_PlayMusicModuleAndFlagIfChain1(16),
    RS_ArmChainYield(0),
    RS_StartObjectAnimSequence(10, 1, 0, 0, 30, 0, 1, 0, 0, 0),
    RS_End(),
};
