#include "types.h"
#include "gen/RoomGraphics.h"
#include "graphics/display.h"
#include "overworld/room.h"

// One entry per room id. Each room's resources are the Room<NN>... symbols of its
// graphics region (data/room_graphics/) and blob region (asm/room/blobs/).
const RoomTableEntry g_aRoomTable[55] = {
    // 0 defense_against_the_dark_arts_classroom
    {
        .pBgTilemap0 = Room00BgMap0,
        .pBgLayer0Extra = Room00BgBlocks0,
        .pBgTilemap1 = Room00BgMap1,
        .pBgLayer1Extra = Room00BgBlocks1,
        .pBgTilemap2 = Room00BgMap2,
        .pBgLayer2Extra = Room00BgBlocks2,
        .pBgTilemap3 = Room00BgMap3,
        .pBgLayer3Extra = Room00BgBlocks3,
        .pCollisionBehaviorTable = Room00CollisionBehavior,
        .pCollisionTilemap = Room00CollisionMap,
        .pRoomResourceBlob = Room00Blob,
        .aBgResources = {{Room00TilesetA, Room00PaletteA}, {Room00TilesetB, Room00PaletteB}},
        .bEncounterCountA = 12,
        .bEncounterCountB = 12,
        .bEncounterVariant = 11,
        .bDefaultMusicModule = 13,
    },
    // 1 potions_classroom
    {
        .pBgTilemap0 = Room01BgMap0,
        .pBgLayer0Extra = Room01BgBlocks0,
        .pBgTilemap1 = Room01BgMap1,
        .pBgLayer1Extra = Room01BgBlocks1,
        .pBgTilemap2 = Room01BgMap2,
        .pBgLayer2Extra = Room01BgBlocks2,
        .pBgTilemap3 = Room01BgMap3,
        .pBgLayer3Extra = Room01BgBlocks3,
        .pCollisionBehaviorTable = Room01CollisionBehavior,
        .pCollisionTilemap = Room01CollisionMap,
        .pRoomResourceBlob = Room01Blob,
        .aBgResources = {{Room01TilesetA, Room01PaletteA}, {Room01TilesetB, Room01PaletteB}},
        .bEncounterCountA = 12,
        .bEncounterCountB = 12,
        .bEncounterVariant = 7,
        .bDefaultMusicModule = 13,
    },
    // 2 potions_classroom_maze
    {
        .pBgTilemap0 = Room02BgMap0,
        .pBgLayer0Extra = Room02BgBlocks0,
        .pBgTilemap1 = Room02BgMap1,
        .pBgLayer1Extra = Room02BgBlocks1,
        .pBgTilemap2 = Room02BgMap2,
        .pBgLayer2Extra = Room02BgBlocks2,
        .pBgTilemap3 = Room02BgMap3,
        .pBgLayer3Extra = Room02BgBlocks3,
        .pCollisionBehaviorTable = Room02CollisionBehavior,
        .pCollisionTilemap = Room02CollisionMap,
        .pRoomResourceBlob = Room02Blob,
        .aBgResources = {{Room02TilesetA, Room02PaletteA}, {Room02TilesetB, Room02PaletteB}},
        .bEncounterCountA = 12,
        .bEncounterCountB = 12,
        .bEncounterVariant = 8,
        .bDefaultMusicModule = 19,
    },
    // 3 transfiguration_classroom
    {
        .pBgTilemap0 = Room03BgMap0,
        .pBgLayer0Extra = Room03BgBlocks0,
        .pBgTilemap1 = Room03BgMap1,
        .pBgLayer1Extra = Room03BgBlocks1,
        .pBgTilemap2 = Room03BgMap2,
        .pBgLayer2Extra = Room03BgBlocks2,
        .pBgTilemap3 = Room03BgMap3,
        .pBgLayer3Extra = Room03BgBlocks3,
        .pCollisionBehaviorTable = Room03CollisionBehavior,
        .pCollisionTilemap = Room03CollisionMap,
        .pRoomResourceBlob = Room03Blob,
        .aBgResources = {{Room03TilesetA, Room03PaletteA}, {Room03TilesetB, Room03PaletteB}},
        .bEncounterCountA = 12,
        .bEncounterCountB = 12,
        .bEncounterVariant = 5,
        .bDefaultMusicModule = 13,
    },
    // 4 transfiguration_classroom_maze
    {
        .pBgTilemap0 = Room04BgMap0,
        .pBgLayer0Extra = Room04BgBlocks0,
        .pBgTilemap1 = Room04BgMap1,
        .pBgLayer1Extra = Room04BgBlocks1,
        .pBgTilemap2 = Room04BgMap2,
        .pBgLayer2Extra = Room04BgBlocks2,
        .pBgTilemap3 = Room04BgMap3,
        .pBgLayer3Extra = Room04BgBlocks3,
        .pCollisionBehaviorTable = Room04CollisionBehavior,
        .pCollisionTilemap = Room04CollisionMap,
        .pRoomResourceBlob = Room04Blob,
        .aBgResources = {{Room04TilesetA, Room04PaletteA}, {Room04TilesetB, Room04PaletteB}},
        .bEncounterCountA = 10,
        .bEncounterCountB = 10,
        .bEncounterVariant = 6,
        .bDefaultMusicModule = 19,
    },
    // 5 hogwarts_express_baggage_car
    {
        .pBgTilemap0 = Room05BgMap0,
        .pBgLayer0Extra = Room05BgBlocks0,
        .pBgTilemap1 = Room05BgMap1,
        .pBgLayer1Extra = Room05BgBlocks1,
        .pBgTilemap2 = Room05BgMap2,
        .pBgLayer2Extra = Room05BgBlocks2,
        .pBgTilemap3 = Room05BgMap3,
        .pBgLayer3Extra = Room05BgBlocks3,
        .pCollisionBehaviorTable = Room05CollisionBehavior,
        .pCollisionTilemap = Room05CollisionMap,
        .pRoomResourceBlob = Room05Blob,
        .aBgResources = {{Room05TilesetA, Room05PaletteA}, {Room05TilesetB, Room05PaletteB}},
        .pBgControlOverrideA = g_aSpecialSceneBg2,
        .bEncounterCountA = 6,
        .bEncounterCountB = 6,
        .bEncounterVariant = 4,
        .bDefaultMusicModule = 51,
    },
    // 6 hogwarts_express_passenger_car
    {
        .pBgTilemap0 = Room06BgMap0,
        .pBgLayer0Extra = Room06BgBlocks0,
        .pBgTilemap1 = Room06BgMap1,
        .pBgLayer1Extra = Room06BgBlocks1,
        .pBgTilemap2 = Room06BgMap2,
        .pBgLayer2Extra = Room06BgBlocks2,
        .pBgTilemap3 = Room06BgMap3,
        .pBgLayer3Extra = Room06BgBlocks3,
        .pCollisionBehaviorTable = Room06CollisionBehavior,
        .pCollisionTilemap = Room06CollisionMap,
        .pRoomResourceBlob = Room06Blob,
        .aBgResources = {{Room06TilesetA, Room06PaletteA}, {Room06TilesetB, Room06PaletteB}},
        .pBgControlOverrideA = g_aSpecialSceneBg2,
        .bEncounterCountA = 12,
        .bEncounterCountB = 12,
        .bEncounterVariant = 4,
        .bDefaultMusicModule = 51,
    },
    // 7 hogwarts_express_buffet_car
    {
        .pBgTilemap0 = Room07BgMap0,
        .pBgLayer0Extra = Room07BgBlocks0,
        .pBgTilemap1 = Room07BgMap1,
        .pBgLayer1Extra = Room07BgBlocks1,
        .pBgTilemap2 = Room07BgMap2,
        .pBgLayer2Extra = Room07BgBlocks2,
        .pBgTilemap3 = Room07BgMap3,
        .pBgLayer3Extra = Room07BgBlocks3,
        .pCollisionBehaviorTable = Room07CollisionBehavior,
        .pCollisionTilemap = Room07CollisionMap,
        .pRoomResourceBlob = Room07Blob,
        .aBgResources = {{Room07TilesetA, Room07PaletteA}, {Room07TilesetB, Room07PaletteB}},
        .pBgControlOverrideA = g_aSpecialSceneBg2,
        .bEncounterCountA = 12,
        .bEncounterVariant = 4,
        .bDefaultMusicModule = 51,
    },
    // 8 hogwarts_grounds_castle_doors
    {
        .pBgTilemap0 = Room08BgMap0,
        .pBgLayer0Extra = Room08BgBlocks0,
        .pBgTilemap1 = Room08BgMap1,
        .pBgLayer1Extra = Room08BgBlocks1,
        .pBgTilemap2 = Room08BgMap2,
        .pBgLayer2Extra = Room08BgBlocks2,
        .pBgTilemap3 = Room08BgMap3,
        .pBgLayer3Extra = Room08BgBlocks3,
        .pCollisionBehaviorTable = Room08CollisionBehavior,
        .pCollisionTilemap = Room08CollisionMap,
        .pRoomResourceBlob = Room08Blob,
        .aBgResources = {{Room08TilesetA, Room08PaletteA}, {Room08TilesetB, Room08PaletteB}},
        .bEncounterCountA = 12,
        .bEncounterCountB = 12,
        .bEncounterVariant = 15,
        .bDefaultMusicModule = 7,
    },
    // 9 hogwarts_grounds_boathouse
    {
        .pBgTilemap0 = Room09BgMap0,
        .pBgLayer0Extra = Room09BgBlocks0,
        .pBgTilemap1 = Room09BgMap1,
        .pBgLayer1Extra = Room09BgBlocks1,
        .pBgTilemap2 = Room09BgMap2,
        .pBgLayer2Extra = Room09BgBlocks2,
        .pBgTilemap3 = Room09BgMap3,
        .pBgLayer3Extra = Room09BgBlocks3,
        .pCollisionBehaviorTable = Room09CollisionBehavior,
        .pCollisionTilemap = Room09CollisionMap,
        .pRoomResourceBlob = Room09Blob,
        .aBgResources = {{Room09TilesetA, Room09PaletteA}, {Room09TilesetB, Room09PaletteB}},
        .bEncounterCountA = 12,
        .bEncounterCountB = 12,
        .bEncounterVariant = 15,
        .bDefaultMusicModule = 7,
    },
    // 10 hogwarts_grounds_greenhouses
    {
        .pBgTilemap0 = Room10BgMap0,
        .pBgLayer0Extra = Room10BgBlocks0,
        .pBgTilemap1 = Room10BgMap1,
        .pBgLayer1Extra = Room10BgBlocks1,
        .pBgTilemap2 = Room10BgMap2,
        .pBgLayer2Extra = Room10BgBlocks2,
        .pBgTilemap3 = Room10BgMap3,
        .pBgLayer3Extra = Room10BgBlocks3,
        .pCollisionBehaviorTable = Room10CollisionBehavior,
        .pCollisionTilemap = Room10CollisionMap,
        .pRoomResourceBlob = Room10Blob,
        .aBgResources = {{Room10TilesetA, Room10PaletteA}, {Room10TilesetB, Room10PaletteB}},
        .bEncounterCountA = 12,
        .bEncounterCountB = 12,
        .bEncounterVariant = 15,
        .bDefaultMusicModule = 7,
    },
    // 11 hagrids_hut
    {
        .pBgTilemap0 = Room11BgMap0,
        .pBgLayer0Extra = Room11BgBlocks0,
        .pBgTilemap1 = Room11BgMap1,
        .pBgLayer1Extra = Room11BgBlocks1,
        .pBgTilemap2 = Room11BgMap2,
        .pBgLayer2Extra = Room11BgBlocks2,
        .pBgTilemap3 = Room11BgMap3,
        .pBgLayer3Extra = Room11BgBlocks3,
        .pCollisionBehaviorTable = Room11CollisionBehavior,
        .pCollisionTilemap = Room11CollisionMap,
        .pRoomResourceBlob = Room11Blob,
        .aBgResources = {{Room11TilesetA, Room11PaletteA}, {Room11TilesetB, Room11PaletteB}},
        .bEncounterCountA = 12,
        .bEncounterCountB = 12,
        .bEncounterVariant = 15,
        .bDefaultMusicModule = 20,
    },
    // 12 hagrids_garden_maze
    {
        .pBgTilemap0 = Room12BgMap0,
        .pBgLayer0Extra = Room12BgBlocks0,
        .pBgTilemap1 = Room12BgMap1,
        .pBgLayer1Extra = Room12BgBlocks1,
        .pBgTilemap2 = Room12BgMap2,
        .pBgLayer2Extra = Room12BgBlocks2,
        .pBgTilemap3 = Room12BgMap3,
        .pBgLayer3Extra = Room12BgBlocks3,
        .pCollisionBehaviorTable = Room12CollisionBehavior,
        .pCollisionTilemap = Room12CollisionMap,
        .pRoomResourceBlob = Room12Blob,
        .aBgResources = {{Room12TilesetA, Room12PaletteA}, {Room12TilesetB, Room12PaletteB}},
        .bEncounterCountA = 9,
        .bEncounterCountB = 9,
        .bEncounterVariant = 14,
        .bDefaultMusicModule = 18,
    },
    // 13 hogwarts_grounds_lake
    {
        .pBgTilemap0 = Room13BgMap0,
        .pBgLayer0Extra = Room13BgBlocks0,
        .pBgTilemap1 = Room13BgMap1,
        .pBgLayer1Extra = Room13BgBlocks1,
        .pBgTilemap2 = Room13BgMap2,
        .pBgLayer2Extra = Room13BgBlocks2,
        .pBgTilemap3 = Room13BgMap3,
        .pBgLayer3Extra = Room13BgBlocks3,
        .pCollisionBehaviorTable = Room13CollisionBehavior,
        .pCollisionTilemap = Room13CollisionMap,
        .pRoomResourceBlob = Room13Blob,
        .aBgResources = {{Room13TilesetA, Room13PaletteA}, {Room13TilesetB, Room13PaletteB}},
        .bEncounterCountA = 12,
        .bEncounterCountB = 12,
        .bEncounterVariant = 19,
        .bDefaultMusicModule = 7,
    },
    // 14 path_to_hagrids_hut
    {
        .pBgTilemap0 = Room14BgMap0,
        .pBgLayer0Extra = Room14BgBlocks0,
        .pBgTilemap1 = Room14BgMap1,
        .pBgLayer1Extra = Room14BgBlocks1,
        .pBgTilemap2 = Room14BgMap2,
        .pBgLayer2Extra = Room14BgBlocks2,
        .pBgTilemap3 = Room14BgMap3,
        .pBgLayer3Extra = Room14BgBlocks3,
        .pCollisionBehaviorTable = Room14CollisionBehavior,
        .pCollisionTilemap = Room14CollisionMap,
        .pRoomResourceBlob = Room14Blob,
        .aBgResources = {{Room14TilesetA, Room14PaletteA}, {Room14TilesetB, Room14PaletteB}},
        .bEncounterCountA = 9,
        .bEncounterCountB = 9,
        .bEncounterCountC = 9,
        .bEncounterVariant = 20,
        .bDefaultMusicModule = 16,
    },
    // 15 hogwarts_grounds_whomping_willow
    {
        .pBgTilemap0 = Room15BgMap0,
        .pBgLayer0Extra = Room15BgBlocks0,
        .pBgTilemap1 = Room15BgMap1,
        .pBgLayer1Extra = Room15BgBlocks1,
        .pBgTilemap2 = Room15BgMap2,
        .pBgLayer2Extra = Room15BgBlocks2,
        .pBgTilemap3 = Room15BgMap3,
        .pBgLayer3Extra = Room15BgBlocks3,
        .pCollisionBehaviorTable = Room15CollisionBehavior,
        .pCollisionTilemap = Room15CollisionMap,
        .pRoomResourceBlob = Room15Blob,
        .aBgResources = {{Room15TilesetA, Room15PaletteA}, {Room15TilesetB, Room15PaletteB}},
        .bEncounterCountA = 12,
        .bEncounterCountB = 12,
        .bEncounterVariant = 18,
        .bDefaultMusicModule = 7,
    },
    // 16 entrance_hall
    {
        .pBgTilemap0 = Room16BgMap0,
        .pBgLayer0Extra = Room16BgBlocks0,
        .pBgTilemap1 = Room16BgMap1,
        .pBgLayer1Extra = Room16BgBlocks1,
        .pBgTilemap2 = Room16BgMap2,
        .pBgLayer2Extra = Room16BgBlocks2,
        .pBgTilemap3 = Room16BgMap3,
        .pBgLayer3Extra = Room16BgBlocks3,
        .pCollisionBehaviorTable = Room16CollisionBehavior,
        .pCollisionTilemap = Room16CollisionMap,
        .pRoomResourceBlob = Room16Blob,
        .aBgResources = {{Room16TilesetA, Room16PaletteA}, {Room16TilesetB, Room16PaletteB}},
        .bEncounterVariant = 30,
        .bDefaultMusicModule = 5,
    },
    // 17 great_hall
    {
        .pBgTilemap0 = Room17BgMap0,
        .pBgLayer0Extra = Room17BgBlocks0,
        .pBgTilemap1 = Room17BgMap1,
        .pBgLayer1Extra = Room17BgBlocks1,
        .pBgTilemap2 = Room17BgMap2,
        .pBgLayer2Extra = Room17BgBlocks2,
        .pBgTilemap3 = Room17BgMap3,
        .pBgLayer3Extra = Room17BgBlocks3,
        .pCollisionBehaviorTable = Room17CollisionBehavior,
        .pCollisionTilemap = Room17CollisionMap,
        .pRoomResourceBlob = Room17Blob,
        .aBgResources = {{Room17TilesetA, Room17PaletteA}, {Room17TilesetB, Room17PaletteB}},
        .bEncounterCountA = 12,
        .bEncounterCountB = 12,
        .bEncounterVariant = 13,
        .bDefaultMusicModule = 5,
    },
    // 18 hogwarts_dungeons
    {
        .pBgTilemap0 = Room18BgMap0,
        .pBgLayer0Extra = Room18BgBlocks0,
        .pBgTilemap1 = Room18BgMap1,
        .pBgLayer1Extra = Room18BgBlocks1,
        .pBgTilemap2 = Room18BgMap2,
        .pBgLayer2Extra = Room18BgBlocks2,
        .pBgTilemap3 = Room18BgMap3,
        .pBgLayer3Extra = Room18BgBlocks3,
        .pCollisionBehaviorTable = Room18CollisionBehavior,
        .pCollisionTilemap = Room18CollisionMap,
        .pRoomResourceBlob = Room18Blob,
        .aBgResources = {{Room18TilesetA, Room18PaletteA}, {Room18TilesetB, Room18PaletteB}},
        .bEncounterVariant = 30,
        .bDefaultMusicModule = 6,
    },
    // 19 second_floor
    {
        .pBgTilemap0 = Room19BgMap0,
        .pBgLayer0Extra = Room19BgBlocks0,
        .pBgTilemap1 = Room19BgMap1,
        .pBgLayer1Extra = Room19BgBlocks1,
        .pBgTilemap2 = Room19BgMap2,
        .pBgLayer2Extra = Room19BgBlocks2,
        .pBgTilemap3 = Room19BgMap3,
        .pBgLayer3Extra = Room19BgBlocks3,
        .pCollisionBehaviorTable = Room19CollisionBehavior,
        .pCollisionTilemap = Room19CollisionMap,
        .pRoomResourceBlob = Room19Blob,
        .aBgResources = {{Room19TilesetA, Room19PaletteA}, {Room19TilesetB, Room19PaletteB}},
        .bEncounterVariant = 30,
        .bDefaultMusicModule = 6,
    },
    // 20 third_floor
    {
        .pBgTilemap0 = Room20BgMap0,
        .pBgLayer0Extra = Room20BgBlocks0,
        .pBgTilemap1 = Room20BgMap1,
        .pBgLayer1Extra = Room20BgBlocks1,
        .pBgTilemap2 = Room20BgMap2,
        .pBgLayer2Extra = Room20BgBlocks2,
        .pBgTilemap3 = Room20BgMap3,
        .pBgLayer3Extra = Room20BgBlocks3,
        .pCollisionBehaviorTable = Room20CollisionBehavior,
        .pCollisionTilemap = Room20CollisionMap,
        .pRoomResourceBlob = Room20Blob,
        .aBgResources = {{Room20TilesetA, Room20PaletteA}, {Room20TilesetB, Room20PaletteB}},
        .bEncounterVariant = 30,
        .bDefaultMusicModule = 6,
    },
    // 21 fourth_floor
    {
        .pBgTilemap0 = Room21BgMap0,
        .pBgLayer0Extra = Room21BgBlocks0,
        .pBgTilemap1 = Room21BgMap1,
        .pBgLayer1Extra = Room21BgBlocks1,
        .pBgTilemap2 = Room21BgMap2,
        .pBgLayer2Extra = Room21BgBlocks2,
        .pBgTilemap3 = Room21BgMap3,
        .pBgLayer3Extra = Room21BgBlocks3,
        .pCollisionBehaviorTable = Room21CollisionBehavior,
        .pCollisionTilemap = Room21CollisionMap,
        .pRoomResourceBlob = Room21Blob,
        .aBgResources = {{Room21TilesetA, Room21PaletteA}, {Room21TilesetB, Room21PaletteB}},
        .bEncounterVariant = 30,
        .bDefaultMusicModule = 6,
    },
    // 22 fifth_floor
    {
        .pBgTilemap0 = Room22BgMap0,
        .pBgLayer0Extra = Room22BgBlocks0,
        .pBgTilemap1 = Room22BgMap1,
        .pBgLayer1Extra = Room22BgBlocks1,
        .pBgTilemap2 = Room22BgMap2,
        .pBgLayer2Extra = Room22BgBlocks2,
        .pBgTilemap3 = Room22BgMap3,
        .pBgLayer3Extra = Room22BgBlocks3,
        .pCollisionBehaviorTable = Room22CollisionBehavior,
        .pCollisionTilemap = Room22CollisionMap,
        .pRoomResourceBlob = Room22Blob,
        .aBgResources = {{Room22TilesetA, Room22PaletteA}, {Room22TilesetB, Room22PaletteB}},
        .bEncounterCountA = 12,
        .bEncounterCountB = 12,
        .bEncounterVariant = 25,
        .bDefaultMusicModule = 6,
    },
    // 23 sixth_floor
    {
        .pBgTilemap0 = Room23BgMap0,
        .pBgLayer0Extra = Room23BgBlocks0,
        .pBgTilemap1 = Room23BgMap1,
        .pBgLayer1Extra = Room23BgBlocks1,
        .pBgTilemap2 = Room23BgMap2,
        .pBgLayer2Extra = Room23BgBlocks2,
        .pBgTilemap3 = Room23BgMap3,
        .pBgLayer3Extra = Room23BgBlocks3,
        .pCollisionBehaviorTable = Room23CollisionBehavior,
        .pCollisionTilemap = Room23CollisionMap,
        .pRoomResourceBlob = Room23Blob,
        .aBgResources = {{Room23TilesetA, Room23PaletteA}, {Room23TilesetB, Room23PaletteB}},
        .bEncounterCountA = 12,
        .bEncounterCountB = 12,
        .bEncounterVariant = 25,
        .bDefaultMusicModule = 6,
    },
    // 24 seventh_floor
    {
        .pBgTilemap0 = Room24BgMap0,
        .pBgLayer0Extra = Room24BgBlocks0,
        .pBgTilemap1 = Room24BgMap1,
        .pBgLayer1Extra = Room24BgBlocks1,
        .pBgTilemap2 = Room24BgMap2,
        .pBgLayer2Extra = Room24BgBlocks2,
        .pBgTilemap3 = Room24BgMap3,
        .pBgLayer3Extra = Room24BgBlocks3,
        .pCollisionBehaviorTable = Room24CollisionBehavior,
        .pCollisionTilemap = Room24CollisionMap,
        .pRoomResourceBlob = Room24Blob,
        .aBgResources = {{Room24TilesetA, Room24PaletteA}, {Room24TilesetB, Room24PaletteB}},
        .bEncounterVariant = 30,
        .bDefaultMusicModule = 6,
    },
    // 25 rooftop
    {
        .pBgTilemap0 = Room25BgMap0,
        .pBgLayer0Extra = Room25BgBlocks0,
        .pBgTilemap1 = Room25BgMap1,
        .pBgLayer1Extra = Room25BgBlocks1,
        .pBgTilemap2 = Room25BgMap2,
        .pBgLayer2Extra = Room25BgBlocks2,
        .pBgTilemap3 = Room25BgMap3,
        .pBgLayer3Extra = Room25BgBlocks3,
        .pCollisionBehaviorTable = Room25CollisionBehavior,
        .pCollisionTilemap = Room25CollisionMap,
        .pRoomResourceBlob = Room25Blob,
        .aBgResources = {{Room25TilesetA, Room25PaletteA}, {Room25TilesetB, Room25PaletteB}},
        .wScrollBoundMaxX = 800,
        .wScrollBoundMaxY = 1662,
        .bEncounterCountA = 12,
        .bEncounterCountB = 12,
        .bEncounterVariant = 17,
        .bDefaultMusicModule = 47,
    },
    // 26 lupins_office
    {
        .pBgTilemap0 = Room26BgMap0,
        .pBgLayer0Extra = Room26BgBlocks0,
        .pBgTilemap1 = Room26BgMap1,
        .pBgLayer1Extra = Room26BgBlocks1,
        .pBgTilemap2 = Room26BgMap2,
        .pBgLayer2Extra = Room26BgBlocks2,
        .pBgTilemap3 = Room26BgMap3,
        .pBgLayer3Extra = Room26BgBlocks3,
        .pCollisionBehaviorTable = Room26CollisionBehavior,
        .pCollisionTilemap = Room26CollisionMap,
        .pRoomResourceBlob = Room26Blob,
        .aBgResources = {{Room26TilesetA, Room26PaletteA}, {Room26TilesetB, Room26PaletteB}},
        .bEncounterVariant = 30,
        .bDefaultMusicModule = 13,
    },
    // 27 staff_room
    {
        .pBgTilemap0 = Room27BgMap0,
        .pBgLayer0Extra = Room27BgBlocks0,
        .pBgTilemap1 = Room27BgMap1,
        .pBgLayer1Extra = Room27BgBlocks1,
        .pBgTilemap2 = Room27BgMap2,
        .pBgLayer2Extra = Room27BgBlocks2,
        .pBgTilemap3 = Room27BgMap3,
        .pBgLayer3Extra = Room27BgBlocks3,
        .pCollisionBehaviorTable = Room27CollisionBehavior,
        .pCollisionTilemap = Room27CollisionMap,
        .pRoomResourceBlob = Room27Blob,
        .aBgResources = {{Room27TilesetA, Room27PaletteA}, {Room27TilesetB, Room27PaletteB}},
        .bEncounterCountA = 12,
        .bEncounterCountB = 12,
        .bEncounterVariant = 12,
        .bDefaultMusicModule = 13,
    },
    // 28 gryffindor_boys_dormitory
    {
        .pBgTilemap0 = Room28BgMap0,
        .pBgLayer0Extra = Room28BgBlocks0,
        .pBgTilemap1 = Room28BgMap1,
        .pBgLayer1Extra = Room28BgBlocks1,
        .pBgTilemap2 = Room28BgMap2,
        .pBgLayer2Extra = Room28BgBlocks2,
        .pBgTilemap3 = Room28BgMap3,
        .pBgLayer3Extra = Room28BgBlocks3,
        .pCollisionBehaviorTable = Room28CollisionBehavior,
        .pCollisionTilemap = Room28CollisionMap,
        .pRoomResourceBlob = Room28Blob,
        .aBgResources = {{Room28TilesetA, Room28PaletteA}, {Room28TilesetB, Room28PaletteB}},
        .bEncounterVariant = 30,
        .bDefaultMusicModule = 11,
    },
    // 29 gryffindor_common_room
    {
        .pBgTilemap0 = Room29BgMap0,
        .pBgLayer0Extra = Room29BgBlocks0,
        .pBgTilemap1 = Room29BgMap1,
        .pBgLayer1Extra = Room29BgBlocks1,
        .pBgTilemap2 = Room29BgMap2,
        .pBgLayer2Extra = Room29BgBlocks2,
        .pBgTilemap3 = Room29BgMap3,
        .pBgLayer3Extra = Room29BgBlocks3,
        .pCollisionBehaviorTable = Room29CollisionBehavior,
        .pCollisionTilemap = Room29CollisionMap,
        .pRoomResourceBlob = Room29Blob,
        .aBgResources = {{Room29TilesetA, Room29PaletteA}, {Room29TilesetB, Room29PaletteB}},
        .bEncounterVariant = 30,
        .bDefaultMusicModule = 11,
    },
    // 30 grand_staircase
    {
        .pBgTilemap0 = Room30BgMap0,
        .pBgLayer0Extra = Room30BgBlocks0,
        .pBgTilemap1 = Room30BgMap1,
        .pBgLayer1Extra = Room30BgBlocks1,
        .pBgTilemap2 = Room30BgMap2,
        .pBgLayer2Extra = Room30BgBlocks2,
        .pBgTilemap3 = Room30BgMap3,
        .pBgLayer3Extra = Room30BgBlocks3,
        .pCollisionBehaviorTable = Room30CollisionBehavior,
        .pCollisionTilemap = Room30CollisionMap,
        .pRoomResourceBlob = Room30Blob,
        .aBgResources = {{Room30TilesetA, Room30PaletteA}, {Room30TilesetB, Room30PaletteB}},
        .wScrollBoundMaxX = 472,
        .wScrollBoundMaxY = 870,
        .bEncounterVariant = 30,
        .bDefaultMusicModule = 6,
    },
    // 31 portrait_room
    {
        .pBgTilemap0 = Room31BgMap0,
        .pBgLayer0Extra = Room31BgBlocks0,
        .pBgTilemap1 = Room31BgMap1,
        .pBgLayer1Extra = Room31BgBlocks1,
        .pBgTilemap2 = Room31BgMap2,
        .pBgLayer2Extra = Room31BgBlocks2,
        .pBgTilemap3 = Room31BgMap3,
        .pBgLayer3Extra = Room31BgBlocks3,
        .pCollisionBehaviorTable = Room31CollisionBehavior,
        .pCollisionTilemap = Room31CollisionMap,
        .pRoomResourceBlob = Room31Blob,
        .aBgResources = {{Room31TilesetA, Room31PaletteA}, {Room31TilesetB, Room31PaletteB}},
        .bEncounterVariant = 30,
        .bDefaultMusicModule = 6,
    },
    // 32 portrait_room_passage
    {
        .pBgTilemap0 = Room32BgMap0,
        .pBgLayer0Extra = Room32BgBlocks0,
        .pBgTilemap1 = Room32BgMap1,
        .pBgLayer1Extra = Room32BgBlocks1,
        .pBgTilemap2 = Room32BgMap2,
        .pBgLayer2Extra = Room32BgBlocks2,
        .pBgTilemap3 = Room32BgMap3,
        .pBgLayer3Extra = Room32BgBlocks3,
        .pCollisionBehaviorTable = Room32CollisionBehavior,
        .pCollisionTilemap = Room32CollisionMap,
        .pRoomResourceBlob = Room32Blob,
        .aBgResources = {{Room32TilesetA, Room32PaletteA}, {Room32TilesetB, Room32PaletteB}},
        .bEncounterVariant = 30,
        .bDefaultMusicModule = 6,
    },
    // 33 hospital_wing
    {
        .pBgTilemap0 = Room33BgMap0,
        .pBgLayer0Extra = Room33BgBlocks0,
        .pBgTilemap1 = Room33BgMap1,
        .pBgLayer1Extra = Room33BgBlocks1,
        .pBgTilemap2 = Room33BgMap2,
        .pBgLayer2Extra = Room33BgBlocks2,
        .pBgTilemap3 = Room33BgMap3,
        .pBgLayer3Extra = Room33BgBlocks3,
        .pCollisionBehaviorTable = Room33CollisionBehavior,
        .pCollisionTilemap = Room33CollisionMap,
        .pRoomResourceBlob = Room33Blob,
        .aBgResources = {{Room33TilesetA, Room33PaletteA}, {Room33TilesetB, Room33PaletteB}},
        .bEncounterVariant = 30,
        .bDefaultMusicModule = 11,
    },
    // 34 library
    {
        .pBgTilemap0 = Room34BgMap0,
        .pBgLayer0Extra = Room34BgBlocks0,
        .pBgTilemap1 = Room34BgMap1,
        .pBgLayer1Extra = Room34BgBlocks1,
        .pBgTilemap2 = Room34BgMap2,
        .pBgLayer2Extra = Room34BgBlocks2,
        .pBgTilemap3 = Room34BgMap3,
        .pBgLayer3Extra = Room34BgBlocks3,
        .pCollisionBehaviorTable = Room34CollisionBehavior,
        .pCollisionTilemap = Room34CollisionMap,
        .pRoomResourceBlob = Room34Blob,
        .aBgResources = {{Room34TilesetA, Room34PaletteA}, {Room34TilesetB, Room34PaletteB}},
        .bEncounterCountA = 7,
        .bEncounterCountB = 7,
        .bEncounterCountC = 7,
        .bEncounterVariant = 9,
        .bDefaultMusicModule = 11,
    },
    // 35 library_2
    {
        .pBgTilemap0 = Room35BgMap0,
        .pBgLayer0Extra = Room35BgBlocks0,
        .pBgTilemap1 = Room35BgMap1,
        .pBgLayer1Extra = Room35BgBlocks1,
        .pBgTilemap2 = Room35BgMap2,
        .pBgLayer2Extra = Room35BgBlocks2,
        .pBgTilemap3 = Room35BgMap3,
        .pBgLayer3Extra = Room35BgBlocks3,
        .pCollisionBehaviorTable = Room35CollisionBehavior,
        .pCollisionTilemap = Room35CollisionMap,
        .pRoomResourceBlob = Room35Blob,
        .aBgResources = {{Room35TilesetA, Room35PaletteA}, {Room35TilesetB, Room35PaletteB}},
        .bEncounterCountA = 5,
        .bEncounterCountB = 5,
        .bEncounterCountC = 5,
        .bEncounterVariant = 10,
        .bDefaultMusicModule = 11,
    },
    // 36 fred_and_georges_shop
    {
        .pBgTilemap0 = Room36BgMap0,
        .pBgLayer0Extra = Room36BgBlocks0,
        .pBgTilemap1 = Room36BgMap1,
        .pBgLayer1Extra = Room36BgBlocks1,
        .pBgTilemap2 = Room36BgMap2,
        .pBgLayer2Extra = Room36BgBlocks2,
        .pBgTilemap3 = Room36BgMap3,
        .pBgLayer3Extra = Room36BgBlocks3,
        .pCollisionBehaviorTable = Room36CollisionBehavior,
        .pCollisionTilemap = Room36CollisionMap,
        .pRoomResourceBlob = Room36Blob,
        .aBgResources = {{Room36TilesetA, Room36PaletteA}, {Room36TilesetB, Room36PaletteB}},
        .wScrollBoundMinX = 32,
        .wScrollBoundMinY = 32,
        .wScrollBoundMaxX = 288,
        .wScrollBoundMaxY = 240,
        .bEncounterVariant = 30,
        .bDefaultMusicModule = 4,
    },
    // 37 wizard_card_collectors_club
    {
        .pBgTilemap0 = Room37BgMap0,
        .pBgLayer0Extra = Room37BgBlocks0,
        .pBgTilemap1 = Room37BgMap1,
        .pBgLayer1Extra = Room37BgBlocks1,
        .pBgTilemap2 = Room37BgMap2,
        .pBgLayer2Extra = Room37BgBlocks2,
        .pBgTilemap3 = Room37BgMap3,
        .pBgLayer3Extra = Room37BgBlocks3,
        .pCollisionBehaviorTable = Room37CollisionBehavior,
        .pCollisionTilemap = Room37CollisionMap,
        .pRoomResourceBlob = Room37Blob,
        .aBgResources = {{Room37TilesetA, Room37PaletteA}, {Room37TilesetB, Room37PaletteB}},
        .bEncounterVariant = 30,
        .bDefaultMusicModule = 4,
    },
    // 38 leaky_cauldron_cellar_1
    {
        .pBgTilemap0 = Room38BgMap0,
        .pBgLayer0Extra = Room38BgBlocks0,
        .pBgTilemap1 = Room38BgMap1,
        .pBgLayer1Extra = Room38BgBlocks1,
        .pBgTilemap2 = Room38BgMap2,
        .pBgLayer2Extra = Room38BgBlocks2,
        .pBgTilemap3 = Room38BgMap3,
        .pBgLayer3Extra = Room38BgBlocks3,
        .pCollisionBehaviorTable = Room38CollisionBehavior,
        .pCollisionTilemap = Room38CollisionMap,
        .pRoomResourceBlob = Room38Blob,
        .aBgResources = {{Room38TilesetA, Room38PaletteA}, {Room38TilesetB, Room38PaletteB}},
        .bEncounterCountA = 12,
        .bEncounterCountB = 12,
        .bDefaultMusicModule = 1,
    },
    // 39 leaky_cauldron_cellar_2
    {
        .pBgTilemap0 = Room39BgMap0,
        .pBgLayer0Extra = Room39BgBlocks0,
        .pBgTilemap1 = Room39BgMap1,
        .pBgLayer1Extra = Room39BgBlocks1,
        .pBgTilemap2 = Room39BgMap2,
        .pBgLayer2Extra = Room39BgBlocks2,
        .pBgTilemap3 = Room39BgMap3,
        .pBgLayer3Extra = Room39BgBlocks3,
        .pCollisionBehaviorTable = Room39CollisionBehavior,
        .pCollisionTilemap = Room39CollisionMap,
        .pRoomResourceBlob = Room39Blob,
        .aBgResources = {{Room39TilesetA, Room39PaletteA}, {Room39TilesetB, Room39PaletteB}},
        .bEncounterCountA = 12,
        .bEncounterCountB = 12,
        .bEncounterVariant = 1,
        .bDefaultMusicModule = 1,
    },
    // 40 leaky_cauldron_hallway
    {
        .pBgTilemap0 = Room40BgMap0,
        .pBgLayer0Extra = Room40BgBlocks0,
        .pBgTilemap1 = Room40BgMap1,
        .pBgLayer1Extra = Room40BgBlocks1,
        .pBgTilemap2 = Room40BgMap2,
        .pBgLayer2Extra = Room40BgBlocks2,
        .pBgTilemap3 = Room40BgMap3,
        .pBgLayer3Extra = Room40BgBlocks3,
        .pCollisionBehaviorTable = Room40CollisionBehavior,
        .pCollisionTilemap = Room40CollisionMap,
        .pRoomResourceBlob = Room40Blob,
        .aBgResources = {{Room40TilesetA, Room40PaletteA}, {Room40TilesetB, Room40PaletteB}},
        .bEncounterVariant = 30,
    },
    // 41 leaky_cauldron_harrys_room
    {
        .pBgTilemap0 = Room41BgMap0,
        .pBgLayer0Extra = Room41BgBlocks0,
        .pBgTilemap1 = Room41BgMap1,
        .pBgLayer1Extra = Room41BgBlocks1,
        .pBgTilemap2 = Room41BgMap2,
        .pBgLayer2Extra = Room41BgBlocks2,
        .pBgTilemap3 = Room41BgMap3,
        .pBgLayer3Extra = Room41BgBlocks3,
        .pCollisionBehaviorTable = Room41CollisionBehavior,
        .pCollisionTilemap = Room41CollisionMap,
        .pRoomResourceBlob = Room41Blob,
        .aBgResources = {{Room41TilesetA, Room41PaletteA}, {Room41TilesetB, Room41PaletteB}},
        .wScrollBoundMaxX = 285,
        .wScrollBoundMaxY = 294,
        .bEncounterVariant = 30,
    },
    // 42 leaky_cauldron_main
    {
        .pBgTilemap0 = Room42BgMap0,
        .pBgLayer0Extra = Room42BgBlocks0,
        .pBgTilemap1 = Room42BgMap1,
        .pBgLayer1Extra = Room42BgBlocks1,
        .pBgTilemap2 = Room42BgMap2,
        .pBgLayer2Extra = Room42BgBlocks2,
        .pBgTilemap3 = Room42BgMap3,
        .pBgLayer3Extra = Room42BgBlocks3,
        .pCollisionBehaviorTable = Room42CollisionBehavior,
        .pCollisionTilemap = Room42CollisionMap,
        .pRoomResourceBlob = Room42Blob,
        .aBgResources = {{Room42TilesetA, Room42PaletteA}, {Room42TilesetB, Room42PaletteB}},
        .wScrollBoundMaxX = 775,
        .wScrollBoundMaxY = 668,
        .bEncounterVariant = 30,
    },
    // 43 shrieking_shack_interior
    {
        .pBgTilemap0 = Room43BgMap0,
        .pBgLayer0Extra = Room43BgBlocks0,
        .pBgTilemap1 = Room43BgMap1,
        .pBgLayer1Extra = Room43BgBlocks1,
        .pBgTilemap2 = Room43BgMap2,
        .pBgLayer2Extra = Room43BgBlocks2,
        .pBgTilemap3 = Room43BgMap3,
        .pBgLayer3Extra = Room43BgBlocks3,
        .pCollisionBehaviorTable = Room43CollisionBehavior,
        .pCollisionTilemap = Room43CollisionMap,
        .pRoomResourceBlob = Room43Blob,
        .aBgResources = {{Room43TilesetA, Room43PaletteA}, {Room43TilesetB, Room43PaletteB}},
        .bEncounterCountA = 12,
        .bEncounterCountB = 12,
        .bEncounterCountC = 12,
        .bEncounterVariant = 21,
        .bDefaultMusicModule = 47,
    },
    // 44 shrieking_shack_path
    {
        .pBgTilemap0 = Room44BgMap0,
        .pBgLayer0Extra = Room44BgBlocks0,
        .pBgTilemap1 = Room44BgMap1,
        .pBgLayer1Extra = Room44BgBlocks1,
        .pBgTilemap2 = Room44BgMap2,
        .pBgLayer2Extra = Room44BgBlocks2,
        .pBgTilemap3 = Room44BgMap3,
        .pBgLayer3Extra = Room44BgBlocks3,
        .pCollisionBehaviorTable = Room44CollisionBehavior,
        .pCollisionTilemap = Room44CollisionMap,
        .pRoomResourceBlob = Room44Blob,
        .aBgResources = {{Room44TilesetA, Room44PaletteA}, {Room44TilesetB, Room44PaletteB}},
        .bEncounterCountA = 12,
        .bEncounterCountB = 12,
        .bEncounterCountC = 12,
        .bEncounterVariant = 21,
        .bDefaultMusicModule = 31,
    },
    // 45 shrieking_shack_path_2
    {
        .pBgTilemap0 = Room45BgMap0,
        .pBgLayer0Extra = Room45BgBlocks0,
        .pBgTilemap1 = Room45BgMap1,
        .pBgLayer1Extra = Room45BgBlocks1,
        .pBgTilemap2 = Room45BgMap2,
        .pBgLayer2Extra = Room45BgBlocks2,
        .pBgTilemap3 = Room45BgMap3,
        .pBgLayer3Extra = Room45BgBlocks3,
        .pCollisionBehaviorTable = Room45CollisionBehavior,
        .pCollisionTilemap = Room45CollisionMap,
        .pRoomResourceBlob = Room45Blob,
        .aBgResources = {{Room45TilesetA, Room45PaletteA}, {Room45TilesetB, Room45PaletteB}},
        .wScrollBoundMaxX = 1184,
        .wScrollBoundMaxY = 1056,
        .bEncounterCountA = 4,
        .bEncounterCountB = 4,
        .bEncounterCountC = 4,
        .bEncounterVariant = 22,
        .bDefaultMusicModule = 31,
    },
    // 46 shrieking_shack_path_3
    {
        .pBgTilemap0 = Room46BgMap0,
        .pBgLayer0Extra = Room46BgBlocks0,
        .pBgTilemap1 = Room46BgMap1,
        .pBgLayer1Extra = Room46BgBlocks1,
        .pBgTilemap2 = Room46BgMap2,
        .pBgLayer2Extra = Room46BgBlocks2,
        .pBgTilemap3 = Room46BgMap3,
        .pBgLayer3Extra = Room46BgBlocks3,
        .pCollisionBehaviorTable = Room46CollisionBehavior,
        .pCollisionTilemap = Room46CollisionMap,
        .pRoomResourceBlob = Room46Blob,
        .aBgResources = {{Room46TilesetA, Room46PaletteA}, {Room46TilesetB, Room46PaletteB}},
        .bEncounterCountA = 6,
        .bEncounterCountB = 6,
        .bEncounterCountC = 6,
        .bEncounterVariant = 21,
        .bDefaultMusicModule = 31,
    },
    // 47 shrieking_shack_path_4
    {
        .pBgTilemap0 = Room47BgMap0,
        .pBgLayer0Extra = Room47BgBlocks0,
        .pBgTilemap1 = Room47BgMap1,
        .pBgLayer1Extra = Room47BgBlocks1,
        .pBgTilemap2 = Room47BgMap2,
        .pBgLayer2Extra = Room47BgBlocks2,
        .pBgTilemap3 = Room47BgMap3,
        .pBgLayer3Extra = Room47BgBlocks3,
        .pCollisionBehaviorTable = Room47CollisionBehavior,
        .pCollisionTilemap = Room47CollisionMap,
        .pRoomResourceBlob = Room47Blob,
        .aBgResources = {{Room47TilesetA, Room47PaletteA}, {Room47TilesetB, Room47PaletteB}},
        .bEncounterCountA = 6,
        .bEncounterCountB = 6,
        .bEncounterCountC = 6,
        .bEncounterVariant = 21,
        .bDefaultMusicModule = 31,
    },
    // 48 shrieking_shack_path_5
    {
        .pBgTilemap0 = Room48BgMap0,
        .pBgLayer0Extra = Room48BgBlocks0,
        .pBgTilemap1 = Room48BgMap1,
        .pBgLayer1Extra = Room48BgBlocks1,
        .pBgTilemap2 = Room48BgMap2,
        .pBgLayer2Extra = Room48BgBlocks2,
        .pBgTilemap3 = Room48BgMap3,
        .pBgLayer3Extra = Room48BgBlocks3,
        .pCollisionBehaviorTable = Room48CollisionBehavior,
        .pCollisionTilemap = Room48CollisionMap,
        .pRoomResourceBlob = Room48Blob,
        .aBgResources = {{Room48TilesetA, Room48PaletteA}, {Room48TilesetB, Room48PaletteB}},
        .bEncounterCountA = 6,
        .bEncounterCountB = 6,
        .bEncounterCountC = 6,
        .bEncounterVariant = 21,
        .bDefaultMusicModule = 31,
    },
    // 49 shrieking_shack_path_6
    {
        .pBgTilemap0 = Room49BgMap0,
        .pBgLayer0Extra = Room49BgBlocks0,
        .pBgTilemap1 = Room49BgMap1,
        .pBgLayer1Extra = Room49BgBlocks1,
        .pBgTilemap2 = Room49BgMap2,
        .pBgLayer2Extra = Room49BgBlocks2,
        .pBgTilemap3 = Room49BgMap3,
        .pBgLayer3Extra = Room49BgBlocks3,
        .pCollisionBehaviorTable = Room49CollisionBehavior,
        .pCollisionTilemap = Room49CollisionMap,
        .pRoomResourceBlob = Room49Blob,
        .aBgResources = {{Room49TilesetA, Room49PaletteA}, {Room49TilesetB, Room49PaletteB}},
        .bEncounterCountA = 6,
        .bEncounterCountB = 6,
        .bEncounterCountC = 6,
        .bEncounterVariant = 21,
        .bDefaultMusicModule = 31,
    },
    // 50 diagon_alley_test_map1
    {
        .pBgTilemap0 = Room50BgMap0,
        .pBgLayer0Extra = Room50BgBlocks0,
        .pBgTilemap1 = Room50BgMap1,
        .pBgLayer1Extra = Room50BgBlocks1,
        .pBgTilemap2 = Room50BgMap2,
        .pBgLayer2Extra = Room50BgBlocks2,
        .pBgTilemap3 = Room50BgMap3,
        .pBgLayer3Extra = Room50BgBlocks3,
        .pCollisionBehaviorTable = Room50CollisionBehavior,
        .pCollisionTilemap = Room50CollisionMap,
        .pRoomResourceBlob = Room50Blob,
        .aBgResources = {{Room50TilesetA, Room50PaletteA}, {Room50TilesetB, Room50PaletteB}},
        .bEncounterCountA = 12,
        .bEncounterCountB = 12,
        .bEncounterVariant = 27,
        .bDefaultMusicModule = 4,
    },
    // 51 diagon_alley_test_map_2
    {
        .pBgTilemap0 = Room51BgMap0,
        .pBgLayer0Extra = Room51BgBlocks0,
        .pBgTilemap1 = Room51BgMap1,
        .pBgLayer1Extra = Room51BgBlocks1,
        .pBgTilemap2 = Room51BgMap2,
        .pBgLayer2Extra = Room51BgBlocks2,
        .pBgTilemap3 = Room51BgMap3,
        .pBgLayer3Extra = Room51BgBlocks3,
        .pCollisionBehaviorTable = Room51CollisionBehavior,
        .pCollisionTilemap = Room51CollisionMap,
        .pRoomResourceBlob = Room51Blob,
        .aBgResources = {{Room51TilesetA, Room51PaletteA}, {Room51TilesetB, Room51PaletteB}},
        .bEncounterCountA = 12,
        .bEncounterCountB = 12,
        .bEncounterVariant = 28,
        .bDefaultMusicModule = 4,
    },
    // 52 diagon_alley_test_map_3
    {
        .pBgTilemap0 = Room52BgMap0,
        .pBgLayer0Extra = Room52BgBlocks0,
        .pBgTilemap1 = Room52BgMap1,
        .pBgLayer1Extra = Room52BgBlocks1,
        .pBgTilemap2 = Room52BgMap2,
        .pBgLayer2Extra = Room52BgBlocks2,
        .pBgTilemap3 = Room52BgMap3,
        .pBgLayer3Extra = Room52BgBlocks3,
        .pCollisionBehaviorTable = Room52CollisionBehavior,
        .pCollisionTilemap = Room52CollisionMap,
        .pRoomResourceBlob = Room52Blob,
        .aBgResources = {{Room52TilesetA, Room52PaletteA}, {Room52TilesetB, Room52PaletteB}},
        .bEncounterCountA = 12,
        .bEncounterCountB = 12,
        .bEncounterVariant = 29,
        .bDefaultMusicModule = 4,
    },
    // 53 diagon_alley_test_map_4
    {
        .pBgTilemap0 = Room53BgMap0,
        .pBgLayer0Extra = Room53BgBlocks0,
        .pBgTilemap1 = Room53BgMap1,
        .pBgLayer1Extra = Room53BgBlocks1,
        .pBgTilemap2 = Room53BgMap2,
        .pBgLayer2Extra = Room53BgBlocks2,
        .pBgTilemap3 = Room53BgMap3,
        .pBgLayer3Extra = Room53BgBlocks3,
        .pCollisionBehaviorTable = Room53CollisionBehavior,
        .pCollisionTilemap = Room53CollisionMap,
        .pRoomResourceBlob = Room53Blob,
        .aBgResources = {{Room53TilesetA, Room53PaletteA}, {Room53TilesetB, Room53PaletteB}},
        .bEncounterCountA = 10,
        .bEncounterCountB = 10,
        .bEncounterVariant = 2,
        .bDefaultMusicModule = 4,
    },
    // 54 diagon_alley_test_map_5
    {
        .pBgTilemap0 = Room54BgMap0,
        .pBgLayer0Extra = Room54BgBlocks0,
        .pBgTilemap1 = Room54BgMap1,
        .pBgLayer1Extra = Room54BgBlocks1,
        .pBgTilemap2 = Room54BgMap2,
        .pBgLayer2Extra = Room54BgBlocks2,
        .pBgTilemap3 = Room54BgMap3,
        .pBgLayer3Extra = Room54BgBlocks3,
        .pCollisionBehaviorTable = Room54CollisionBehavior,
        .pCollisionTilemap = Room54CollisionMap,
        .pRoomResourceBlob = Room54Blob,
        .aBgResources = {{Room54TilesetA, Room54PaletteA}, {Room54TilesetB, Room54PaletteB}},
        .bEncounterCountA = 12,
        .bEncounterCountB = 12,
        .bEncounterVariant = 3,
        .bDefaultMusicModule = 4,
    },
};
