#include "types.h"
#include "gen/graphics/rooms.h"
#include "overworld/room_blob.h"
#include "graphics/display.h"
#include "overworld/room.h"

// One entry per room id. Each room's resources are the Room<NN>... symbols of its
// graphics region (data/room_graphics/) and blob region (asm/room/blobs/).
const RoomTableEntry g_aRoomTable[55] = {
    // 0 defense_against_the_dark_arts_classroom
    {
        .pBgTilemap0 = gRoom00BgMap0,
        .pBgLayer0Extra = gRoom00BgBlocks0,
        .pBgTilemap1 = gRoom00BgMap1,
        .pBgLayer1Extra = gRoom00BgBlocks1,
        .pBgTilemap2 = gRoom00BgMap2,
        .pBgLayer2Extra = gRoom00BgBlocks2,
        .pBgTilemap3 = gRoom00BgMap3,
        .pBgLayer3Extra = gRoom00BgBlocks3,
        .pCollisionBehaviorTable = gRoom00CollisionBehavior,
        .pCollisionTilemap = gRoom00CollisionMap,
        .pRoomResourceBlob = Room00Blob,
        .aBgResources = {{gRoom00TilesetA, gRoom00PaletteA}, {gRoom00TilesetB, gRoom00PaletteB}},
        .bEncounterCountA = 12,
        .bEncounterCountB = 12,
        .bEncounterVariant = 11,
        .bDefaultMusicModule = 13,
    },
    // 1 potions_classroom
    {
        .pBgTilemap0 = gRoom01BgMap0,
        .pBgLayer0Extra = gRoom01BgBlocks0,
        .pBgTilemap1 = gRoom01BgMap1,
        .pBgLayer1Extra = gRoom01BgBlocks1,
        .pBgTilemap2 = gRoom01BgMap2,
        .pBgLayer2Extra = gRoom01BgBlocks2,
        .pBgTilemap3 = gRoom01BgMap3,
        .pBgLayer3Extra = gRoom01BgBlocks3,
        .pCollisionBehaviorTable = gRoom01CollisionBehavior,
        .pCollisionTilemap = gRoom01CollisionMap,
        .pRoomResourceBlob = Room01Blob,
        .aBgResources = {{gRoom01TilesetA, gRoom01PaletteA}, {gRoom01TilesetB, gRoom01PaletteB}},
        .bEncounterCountA = 12,
        .bEncounterCountB = 12,
        .bEncounterVariant = 7,
        .bDefaultMusicModule = 13,
    },
    // 2 potions_classroom_maze
    {
        .pBgTilemap0 = gRoom02BgMap0,
        .pBgLayer0Extra = gRoom02BgBlocks0,
        .pBgTilemap1 = gRoom02BgMap1,
        .pBgLayer1Extra = gRoom02BgBlocks1,
        .pBgTilemap2 = gRoom02BgMap2,
        .pBgLayer2Extra = gRoom02BgBlocks2,
        .pBgTilemap3 = gRoom02BgMap3,
        .pBgLayer3Extra = gRoom02BgBlocks3,
        .pCollisionBehaviorTable = gRoom02CollisionBehavior,
        .pCollisionTilemap = gRoom02CollisionMap,
        .pRoomResourceBlob = Room02Blob,
        .aBgResources = {{gRoom02TilesetA, gRoom02PaletteA}, {gRoom02TilesetB, gRoom02PaletteB}},
        .bEncounterCountA = 12,
        .bEncounterCountB = 12,
        .bEncounterVariant = 8,
        .bDefaultMusicModule = 19,
    },
    // 3 transfiguration_classroom
    {
        .pBgTilemap0 = gRoom03BgMap0,
        .pBgLayer0Extra = gRoom03BgBlocks0,
        .pBgTilemap1 = gRoom03BgMap1,
        .pBgLayer1Extra = gRoom03BgBlocks1,
        .pBgTilemap2 = gRoom03BgMap2,
        .pBgLayer2Extra = gRoom03BgBlocks2,
        .pBgTilemap3 = gRoom03BgMap3,
        .pBgLayer3Extra = gRoom03BgBlocks3,
        .pCollisionBehaviorTable = gRoom03CollisionBehavior,
        .pCollisionTilemap = gRoom03CollisionMap,
        .pRoomResourceBlob = Room03Blob,
        .aBgResources = {{gRoom03TilesetA, gRoom03PaletteA}, {gRoom03TilesetB, gRoom03PaletteB}},
        .bEncounterCountA = 12,
        .bEncounterCountB = 12,
        .bEncounterVariant = 5,
        .bDefaultMusicModule = 13,
    },
    // 4 transfiguration_classroom_maze
    {
        .pBgTilemap0 = gRoom04BgMap0,
        .pBgLayer0Extra = gRoom04BgBlocks0,
        .pBgTilemap1 = gRoom04BgMap1,
        .pBgLayer1Extra = gRoom04BgBlocks1,
        .pBgTilemap2 = gRoom04BgMap2,
        .pBgLayer2Extra = gRoom04BgBlocks2,
        .pBgTilemap3 = gRoom04BgMap3,
        .pBgLayer3Extra = gRoom04BgBlocks3,
        .pCollisionBehaviorTable = gRoom04CollisionBehavior,
        .pCollisionTilemap = gRoom04CollisionMap,
        .pRoomResourceBlob = Room04Blob,
        .aBgResources = {{gRoom04TilesetA, gRoom04PaletteA}, {gRoom04TilesetB, gRoom04PaletteB}},
        .bEncounterCountA = 10,
        .bEncounterCountB = 10,
        .bEncounterVariant = 6,
        .bDefaultMusicModule = 19,
    },
    // 5 hogwarts_express_baggage_car
    {
        .pBgTilemap0 = gRoom05BgMap0,
        .pBgLayer0Extra = gRoom05BgBlocks0,
        .pBgTilemap1 = gRoom05BgMap1,
        .pBgLayer1Extra = gRoom05BgBlocks1,
        .pBgTilemap2 = gRoom05BgMap2,
        .pBgLayer2Extra = gRoom05BgBlocks2,
        .pBgTilemap3 = gRoom05BgMap3,
        .pBgLayer3Extra = gRoom05BgBlocks3,
        .pCollisionBehaviorTable = gRoom05CollisionBehavior,
        .pCollisionTilemap = gRoom05CollisionMap,
        .pRoomResourceBlob = Room05Blob,
        .aBgResources = {{gRoom05TilesetA, gRoom05PaletteA}, {gRoom05TilesetB, gRoom05PaletteB}},
        .pBgControlOverrideA = &g_aSpecialSceneBg2,
        .bEncounterCountA = 6,
        .bEncounterCountB = 6,
        .bEncounterVariant = 4,
        .bDefaultMusicModule = 51,
    },
    // 6 hogwarts_express_passenger_car
    {
        .pBgTilemap0 = gRoom06BgMap0,
        .pBgLayer0Extra = gRoom06BgBlocks0,
        .pBgTilemap1 = gRoom06BgMap1,
        .pBgLayer1Extra = gRoom06BgBlocks1,
        .pBgTilemap2 = gRoom06BgMap2,
        .pBgLayer2Extra = gRoom06BgBlocks2,
        .pBgTilemap3 = gRoom06BgMap3,
        .pBgLayer3Extra = gRoom06BgBlocks3,
        .pCollisionBehaviorTable = gRoom06CollisionBehavior,
        .pCollisionTilemap = gRoom06CollisionMap,
        .pRoomResourceBlob = Room06Blob,
        .aBgResources = {{gRoom06TilesetA, gRoom06PaletteA}, {gRoom06TilesetB, gRoom06PaletteB}},
        .pBgControlOverrideA = &g_aSpecialSceneBg2,
        .bEncounterCountA = 12,
        .bEncounterCountB = 12,
        .bEncounterVariant = 4,
        .bDefaultMusicModule = 51,
    },
    // 7 hogwarts_express_buffet_car
    {
        .pBgTilemap0 = gRoom07BgMap0,
        .pBgLayer0Extra = gRoom07BgBlocks0,
        .pBgTilemap1 = gRoom07BgMap1,
        .pBgLayer1Extra = gRoom07BgBlocks1,
        .pBgTilemap2 = gRoom07BgMap2,
        .pBgLayer2Extra = gRoom07BgBlocks2,
        .pBgTilemap3 = gRoom07BgMap3,
        .pBgLayer3Extra = gRoom07BgBlocks3,
        .pCollisionBehaviorTable = gRoom07CollisionBehavior,
        .pCollisionTilemap = gRoom07CollisionMap,
        .pRoomResourceBlob = Room07Blob,
        .aBgResources = {{gRoom07TilesetA, gRoom07PaletteA}, {gRoom07TilesetB, gRoom07PaletteB}},
        .pBgControlOverrideA = &g_aSpecialSceneBg2,
        .bEncounterCountA = 12,
        .bEncounterVariant = 4,
        .bDefaultMusicModule = 51,
    },
    // 8 hogwarts_grounds_castle_doors
    {
        .pBgTilemap0 = gRoom08BgMap0,
        .pBgLayer0Extra = gRoom08BgBlocks0,
        .pBgTilemap1 = gRoom08BgMap1,
        .pBgLayer1Extra = gRoom08BgBlocks1,
        .pBgTilemap2 = gRoom08BgMap2,
        .pBgLayer2Extra = gRoom08BgBlocks2,
        .pBgTilemap3 = gRoom08BgMap3,
        .pBgLayer3Extra = gRoom08BgBlocks3,
        .pCollisionBehaviorTable = gRoom08CollisionBehavior,
        .pCollisionTilemap = gRoom08CollisionMap,
        .pRoomResourceBlob = Room08Blob,
        .aBgResources = {{gRoom08TilesetA, gRoom08PaletteA}, {gRoom08TilesetB, gRoom08PaletteB}},
        .bEncounterCountA = 12,
        .bEncounterCountB = 12,
        .bEncounterVariant = 15,
        .bDefaultMusicModule = 7,
    },
    // 9 hogwarts_grounds_boathouse
    {
        .pBgTilemap0 = gRoom09BgMap0,
        .pBgLayer0Extra = gRoom09BgBlocks0,
        .pBgTilemap1 = gRoom09BgMap1,
        .pBgLayer1Extra = gRoom09BgBlocks1,
        .pBgTilemap2 = gRoom09BgMap2,
        .pBgLayer2Extra = gRoom09BgBlocks2,
        .pBgTilemap3 = gRoom09BgMap3,
        .pBgLayer3Extra = gRoom09BgBlocks3,
        .pCollisionBehaviorTable = gRoom09CollisionBehavior,
        .pCollisionTilemap = gRoom09CollisionMap,
        .pRoomResourceBlob = Room09Blob,
        .aBgResources = {{gRoom09TilesetA, gRoom09PaletteA}, {gRoom09TilesetB, gRoom09PaletteB}},
        .bEncounterCountA = 12,
        .bEncounterCountB = 12,
        .bEncounterVariant = 15,
        .bDefaultMusicModule = 7,
    },
    // 10 hogwarts_grounds_greenhouses
    {
        .pBgTilemap0 = gRoom10BgMap0,
        .pBgLayer0Extra = gRoom10BgBlocks0,
        .pBgTilemap1 = gRoom10BgMap1,
        .pBgLayer1Extra = gRoom10BgBlocks1,
        .pBgTilemap2 = gRoom10BgMap2,
        .pBgLayer2Extra = gRoom10BgBlocks2,
        .pBgTilemap3 = gRoom10BgMap3,
        .pBgLayer3Extra = gRoom10BgBlocks3,
        .pCollisionBehaviorTable = gRoom10CollisionBehavior,
        .pCollisionTilemap = gRoom10CollisionMap,
        .pRoomResourceBlob = Room10Blob,
        .aBgResources = {{gRoom10TilesetA, gRoom10PaletteA}, {gRoom10TilesetB, gRoom10PaletteB}},
        .bEncounterCountA = 12,
        .bEncounterCountB = 12,
        .bEncounterVariant = 15,
        .bDefaultMusicModule = 7,
    },
    // 11 hagrids_hut
    {
        .pBgTilemap0 = gRoom11BgMap0,
        .pBgLayer0Extra = gRoom11BgBlocks0,
        .pBgTilemap1 = gRoom11BgMap1,
        .pBgLayer1Extra = gRoom11BgBlocks1,
        .pBgTilemap2 = gRoom11BgMap2,
        .pBgLayer2Extra = gRoom11BgBlocks2,
        .pBgTilemap3 = gRoom11BgMap3,
        .pBgLayer3Extra = gRoom11BgBlocks3,
        .pCollisionBehaviorTable = gRoom11CollisionBehavior,
        .pCollisionTilemap = gRoom11CollisionMap,
        .pRoomResourceBlob = Room11Blob,
        .aBgResources = {{gRoom11TilesetA, gRoom11PaletteA}, {gRoom11TilesetB, gRoom11PaletteB}},
        .bEncounterCountA = 12,
        .bEncounterCountB = 12,
        .bEncounterVariant = 15,
        .bDefaultMusicModule = 20,
    },
    // 12 hagrids_garden_maze
    {
        .pBgTilemap0 = gRoom12BgMap0,
        .pBgLayer0Extra = gRoom12BgBlocks0,
        .pBgTilemap1 = gRoom12BgMap1,
        .pBgLayer1Extra = gRoom12BgBlocks1,
        .pBgTilemap2 = gRoom12BgMap2,
        .pBgLayer2Extra = gRoom12BgBlocks2,
        .pBgTilemap3 = gRoom12BgMap3,
        .pBgLayer3Extra = gRoom12BgBlocks3,
        .pCollisionBehaviorTable = gRoom12CollisionBehavior,
        .pCollisionTilemap = gRoom12CollisionMap,
        .pRoomResourceBlob = Room12Blob,
        .aBgResources = {{gRoom12TilesetA, gRoom12PaletteA}, {gRoom12TilesetB, gRoom12PaletteB}},
        .bEncounterCountA = 9,
        .bEncounterCountB = 9,
        .bEncounterVariant = 14,
        .bDefaultMusicModule = 18,
    },
    // 13 hogwarts_grounds_lake
    {
        .pBgTilemap0 = gRoom13BgMap0,
        .pBgLayer0Extra = gRoom13BgBlocks0,
        .pBgTilemap1 = gRoom13BgMap1,
        .pBgLayer1Extra = gRoom13BgBlocks1,
        .pBgTilemap2 = gRoom13BgMap2,
        .pBgLayer2Extra = gRoom13BgBlocks2,
        .pBgTilemap3 = gRoom13BgMap3,
        .pBgLayer3Extra = gRoom13BgBlocks3,
        .pCollisionBehaviorTable = gRoom13CollisionBehavior,
        .pCollisionTilemap = gRoom13CollisionMap,
        .pRoomResourceBlob = Room13Blob,
        .aBgResources = {{gRoom13TilesetA, gRoom13PaletteA}, {gRoom13TilesetB, gRoom13PaletteB}},
        .bEncounterCountA = 12,
        .bEncounterCountB = 12,
        .bEncounterVariant = 19,
        .bDefaultMusicModule = 7,
    },
    // 14 path_to_hagrids_hut
    {
        .pBgTilemap0 = gRoom14BgMap0,
        .pBgLayer0Extra = gRoom14BgBlocks0,
        .pBgTilemap1 = gRoom14BgMap1,
        .pBgLayer1Extra = gRoom14BgBlocks1,
        .pBgTilemap2 = gRoom14BgMap2,
        .pBgLayer2Extra = gRoom14BgBlocks2,
        .pBgTilemap3 = gRoom14BgMap3,
        .pBgLayer3Extra = gRoom14BgBlocks3,
        .pCollisionBehaviorTable = gRoom14CollisionBehavior,
        .pCollisionTilemap = gRoom14CollisionMap,
        .pRoomResourceBlob = Room14Blob,
        .aBgResources = {{gRoom14TilesetA, gRoom14PaletteA}, {gRoom14TilesetB, gRoom14PaletteB}},
        .bEncounterCountA = 9,
        .bEncounterCountB = 9,
        .bEncounterCountC = 9,
        .bEncounterVariant = 20,
        .bDefaultMusicModule = 16,
    },
    // 15 hogwarts_grounds_whomping_willow
    {
        .pBgTilemap0 = gRoom15BgMap0,
        .pBgLayer0Extra = gRoom15BgBlocks0,
        .pBgTilemap1 = gRoom15BgMap1,
        .pBgLayer1Extra = gRoom15BgBlocks1,
        .pBgTilemap2 = gRoom15BgMap2,
        .pBgLayer2Extra = gRoom15BgBlocks2,
        .pBgTilemap3 = gRoom15BgMap3,
        .pBgLayer3Extra = gRoom15BgBlocks3,
        .pCollisionBehaviorTable = gRoom15CollisionBehavior,
        .pCollisionTilemap = gRoom15CollisionMap,
        .pRoomResourceBlob = Room15Blob,
        .aBgResources = {{gRoom15TilesetA, gRoom15PaletteA}, {gRoom15TilesetB, gRoom15PaletteB}},
        .bEncounterCountA = 12,
        .bEncounterCountB = 12,
        .bEncounterVariant = 18,
        .bDefaultMusicModule = 7,
    },
    // 16 entrance_hall
    {
        .pBgTilemap0 = gRoom16BgMap0,
        .pBgLayer0Extra = gRoom16BgBlocks0,
        .pBgTilemap1 = gRoom16BgMap1,
        .pBgLayer1Extra = gRoom16BgBlocks1,
        .pBgTilemap2 = gRoom16BgMap2,
        .pBgLayer2Extra = gRoom16BgBlocks2,
        .pBgTilemap3 = gRoom16BgMap3,
        .pBgLayer3Extra = gRoom16BgBlocks3,
        .pCollisionBehaviorTable = gRoom16CollisionBehavior,
        .pCollisionTilemap = gRoom16CollisionMap,
        .pRoomResourceBlob = Room16Blob,
        .aBgResources = {{gRoom16TilesetA, gRoom16PaletteA}, {gRoom16TilesetB, gRoom16PaletteB}},
        .bEncounterVariant = 30,
        .bDefaultMusicModule = 5,
    },
    // 17 great_hall
    {
        .pBgTilemap0 = gRoom17BgMap0,
        .pBgLayer0Extra = gRoom17BgBlocks0,
        .pBgTilemap1 = gRoom17BgMap1,
        .pBgLayer1Extra = gRoom17BgBlocks1,
        .pBgTilemap2 = gRoom17BgMap2,
        .pBgLayer2Extra = gRoom17BgBlocks2,
        .pBgTilemap3 = gRoom17BgMap3,
        .pBgLayer3Extra = gRoom17BgBlocks3,
        .pCollisionBehaviorTable = gRoom17CollisionBehavior,
        .pCollisionTilemap = gRoom17CollisionMap,
        .pRoomResourceBlob = Room17Blob,
        .aBgResources = {{gRoom17TilesetA, gRoom17PaletteA}, {gRoom17TilesetB, gRoom17PaletteB}},
        .bEncounterCountA = 12,
        .bEncounterCountB = 12,
        .bEncounterVariant = 13,
        .bDefaultMusicModule = 5,
    },
    // 18 hogwarts_dungeons
    {
        .pBgTilemap0 = gRoom18BgMap0,
        .pBgLayer0Extra = gRoom18BgBlocks0,
        .pBgTilemap1 = gRoom18BgMap1,
        .pBgLayer1Extra = gRoom18BgBlocks1,
        .pBgTilemap2 = gRoom18BgMap2,
        .pBgLayer2Extra = gRoom18BgBlocks2,
        .pBgTilemap3 = gRoom18BgMap3,
        .pBgLayer3Extra = gRoom18BgBlocks3,
        .pCollisionBehaviorTable = gRoom18CollisionBehavior,
        .pCollisionTilemap = gRoom18CollisionMap,
        .pRoomResourceBlob = Room18Blob,
        .aBgResources = {{gRoom18TilesetA, gRoom18PaletteA}, {gRoom18TilesetB, gRoom18PaletteB}},
        .bEncounterVariant = 30,
        .bDefaultMusicModule = 6,
    },
    // 19 second_floor
    {
        .pBgTilemap0 = gRoom19BgMap0,
        .pBgLayer0Extra = gRoom19BgBlocks0,
        .pBgTilemap1 = gRoom19BgMap1,
        .pBgLayer1Extra = gRoom19BgBlocks1,
        .pBgTilemap2 = gRoom19BgMap2,
        .pBgLayer2Extra = gRoom19BgBlocks2,
        .pBgTilemap3 = gRoom19BgMap3,
        .pBgLayer3Extra = gRoom19BgBlocks3,
        .pCollisionBehaviorTable = gRoom19CollisionBehavior,
        .pCollisionTilemap = gRoom19CollisionMap,
        .pRoomResourceBlob = Room19Blob,
        .aBgResources = {{gRoom19TilesetA, gRoom19PaletteA}, {gRoom19TilesetB, gRoom19PaletteB}},
        .bEncounterVariant = 30,
        .bDefaultMusicModule = 6,
    },
    // 20 third_floor
    {
        .pBgTilemap0 = gRoom20BgMap0,
        .pBgLayer0Extra = gRoom20BgBlocks0,
        .pBgTilemap1 = gRoom20BgMap1,
        .pBgLayer1Extra = gRoom20BgBlocks1,
        .pBgTilemap2 = gRoom20BgMap2,
        .pBgLayer2Extra = gRoom20BgBlocks2,
        .pBgTilemap3 = gRoom20BgMap3,
        .pBgLayer3Extra = gRoom20BgBlocks3,
        .pCollisionBehaviorTable = gRoom20CollisionBehavior,
        .pCollisionTilemap = gRoom20CollisionMap,
        .pRoomResourceBlob = Room20Blob,
        .aBgResources = {{gRoom20TilesetA, gRoom20PaletteA}, {gRoom20TilesetB, gRoom20PaletteB}},
        .bEncounterVariant = 30,
        .bDefaultMusicModule = 6,
    },
    // 21 fourth_floor
    {
        .pBgTilemap0 = gRoom21BgMap0,
        .pBgLayer0Extra = gRoom21BgBlocks0,
        .pBgTilemap1 = gRoom21BgMap1,
        .pBgLayer1Extra = gRoom21BgBlocks1,
        .pBgTilemap2 = gRoom21BgMap2,
        .pBgLayer2Extra = gRoom21BgBlocks2,
        .pBgTilemap3 = gRoom21BgMap3,
        .pBgLayer3Extra = gRoom21BgBlocks3,
        .pCollisionBehaviorTable = gRoom21CollisionBehavior,
        .pCollisionTilemap = gRoom21CollisionMap,
        .pRoomResourceBlob = Room21Blob,
        .aBgResources = {{gRoom21TilesetA, gRoom21PaletteA}, {gRoom21TilesetB, gRoom21PaletteB}},
        .bEncounterVariant = 30,
        .bDefaultMusicModule = 6,
    },
    // 22 fifth_floor
    {
        .pBgTilemap0 = gRoom22BgMap0,
        .pBgLayer0Extra = gRoom22BgBlocks0,
        .pBgTilemap1 = gRoom22BgMap1,
        .pBgLayer1Extra = gRoom22BgBlocks1,
        .pBgTilemap2 = gRoom22BgMap2,
        .pBgLayer2Extra = gRoom22BgBlocks2,
        .pBgTilemap3 = gRoom22BgMap3,
        .pBgLayer3Extra = gRoom22BgBlocks3,
        .pCollisionBehaviorTable = gRoom22CollisionBehavior,
        .pCollisionTilemap = gRoom22CollisionMap,
        .pRoomResourceBlob = Room22Blob,
        .aBgResources = {{gRoom22TilesetA, gRoom22PaletteA}, {gRoom22TilesetB, gRoom22PaletteB}},
        .bEncounterCountA = 12,
        .bEncounterCountB = 12,
        .bEncounterVariant = 25,
        .bDefaultMusicModule = 6,
    },
    // 23 sixth_floor
    {
        .pBgTilemap0 = gRoom23BgMap0,
        .pBgLayer0Extra = gRoom23BgBlocks0,
        .pBgTilemap1 = gRoom23BgMap1,
        .pBgLayer1Extra = gRoom23BgBlocks1,
        .pBgTilemap2 = gRoom23BgMap2,
        .pBgLayer2Extra = gRoom23BgBlocks2,
        .pBgTilemap3 = gRoom23BgMap3,
        .pBgLayer3Extra = gRoom23BgBlocks3,
        .pCollisionBehaviorTable = gRoom23CollisionBehavior,
        .pCollisionTilemap = gRoom23CollisionMap,
        .pRoomResourceBlob = Room23Blob,
        .aBgResources = {{gRoom23TilesetA, gRoom23PaletteA}, {gRoom23TilesetB, gRoom23PaletteB}},
        .bEncounterCountA = 12,
        .bEncounterCountB = 12,
        .bEncounterVariant = 25,
        .bDefaultMusicModule = 6,
    },
    // 24 seventh_floor
    {
        .pBgTilemap0 = gRoom24BgMap0,
        .pBgLayer0Extra = gRoom24BgBlocks0,
        .pBgTilemap1 = gRoom24BgMap1,
        .pBgLayer1Extra = gRoom24BgBlocks1,
        .pBgTilemap2 = gRoom24BgMap2,
        .pBgLayer2Extra = gRoom24BgBlocks2,
        .pBgTilemap3 = gRoom24BgMap3,
        .pBgLayer3Extra = gRoom24BgBlocks3,
        .pCollisionBehaviorTable = gRoom24CollisionBehavior,
        .pCollisionTilemap = gRoom24CollisionMap,
        .pRoomResourceBlob = Room24Blob,
        .aBgResources = {{gRoom24TilesetA, gRoom24PaletteA}, {gRoom24TilesetB, gRoom24PaletteB}},
        .bEncounterVariant = 30,
        .bDefaultMusicModule = 6,
    },
    // 25 rooftop
    {
        .pBgTilemap0 = gRoom25BgMap0,
        .pBgLayer0Extra = gRoom25BgBlocks0,
        .pBgTilemap1 = gRoom25BgMap1,
        .pBgLayer1Extra = gRoom25BgBlocks1,
        .pBgTilemap2 = gRoom25BgMap2,
        .pBgLayer2Extra = gRoom25BgBlocks2,
        .pBgTilemap3 = gRoom25BgMap3,
        .pBgLayer3Extra = gRoom25BgBlocks3,
        .pCollisionBehaviorTable = gRoom25CollisionBehavior,
        .pCollisionTilemap = gRoom25CollisionMap,
        .pRoomResourceBlob = Room25Blob,
        .aBgResources = {{gRoom25TilesetA, gRoom25PaletteA}, {gRoom25TilesetB, gRoom25PaletteB}},
        .wScrollBoundMaxX = 800,
        .wScrollBoundMaxY = 1662,
        .bEncounterCountA = 12,
        .bEncounterCountB = 12,
        .bEncounterVariant = 17,
        .bDefaultMusicModule = 47,
    },
    // 26 lupins_office
    {
        .pBgTilemap0 = gRoom26BgMap0,
        .pBgLayer0Extra = gRoom26BgBlocks0,
        .pBgTilemap1 = gRoom26BgMap1,
        .pBgLayer1Extra = gRoom26BgBlocks1,
        .pBgTilemap2 = gRoom26BgMap2,
        .pBgLayer2Extra = gRoom26BgBlocks2,
        .pBgTilemap3 = gRoom26BgMap3,
        .pBgLayer3Extra = gRoom26BgBlocks3,
        .pCollisionBehaviorTable = gRoom26CollisionBehavior,
        .pCollisionTilemap = gRoom26CollisionMap,
        .pRoomResourceBlob = Room26Blob,
        .aBgResources = {{gRoom26TilesetA, gRoom26PaletteA}, {gRoom26TilesetB, gRoom26PaletteB}},
        .bEncounterVariant = 30,
        .bDefaultMusicModule = 13,
    },
    // 27 staff_room
    {
        .pBgTilemap0 = gRoom27BgMap0,
        .pBgLayer0Extra = gRoom27BgBlocks0,
        .pBgTilemap1 = gRoom27BgMap1,
        .pBgLayer1Extra = gRoom27BgBlocks1,
        .pBgTilemap2 = gRoom27BgMap2,
        .pBgLayer2Extra = gRoom27BgBlocks2,
        .pBgTilemap3 = gRoom27BgMap3,
        .pBgLayer3Extra = gRoom27BgBlocks3,
        .pCollisionBehaviorTable = gRoom27CollisionBehavior,
        .pCollisionTilemap = gRoom27CollisionMap,
        .pRoomResourceBlob = Room27Blob,
        .aBgResources = {{gRoom27TilesetA, gRoom27PaletteA}, {gRoom27TilesetB, gRoom27PaletteB}},
        .bEncounterCountA = 12,
        .bEncounterCountB = 12,
        .bEncounterVariant = 12,
        .bDefaultMusicModule = 13,
    },
    // 28 gryffindor_boys_dormitory
    {
        .pBgTilemap0 = gRoom28BgMap0,
        .pBgLayer0Extra = gRoom28BgBlocks0,
        .pBgTilemap1 = gRoom28BgMap1,
        .pBgLayer1Extra = gRoom28BgBlocks1,
        .pBgTilemap2 = gRoom28BgMap2,
        .pBgLayer2Extra = gRoom28BgBlocks2,
        .pBgTilemap3 = gRoom28BgMap3,
        .pBgLayer3Extra = gRoom28BgBlocks3,
        .pCollisionBehaviorTable = gRoom28CollisionBehavior,
        .pCollisionTilemap = gRoom28CollisionMap,
        .pRoomResourceBlob = Room28Blob,
        .aBgResources = {{gRoom28TilesetA, gRoom28PaletteA}, {gRoom28TilesetB, gRoom28PaletteB}},
        .bEncounterVariant = 30,
        .bDefaultMusicModule = 11,
    },
    // 29 gryffindor_common_room
    {
        .pBgTilemap0 = gRoom29BgMap0,
        .pBgLayer0Extra = gRoom29BgBlocks0,
        .pBgTilemap1 = gRoom29BgMap1,
        .pBgLayer1Extra = gRoom29BgBlocks1,
        .pBgTilemap2 = gRoom29BgMap2,
        .pBgLayer2Extra = gRoom29BgBlocks2,
        .pBgTilemap3 = gRoom29BgMap3,
        .pBgLayer3Extra = gRoom29BgBlocks3,
        .pCollisionBehaviorTable = gRoom29CollisionBehavior,
        .pCollisionTilemap = gRoom29CollisionMap,
        .pRoomResourceBlob = Room29Blob,
        .aBgResources = {{gRoom29TilesetA, gRoom29PaletteA}, {gRoom29TilesetB, gRoom29PaletteB}},
        .bEncounterVariant = 30,
        .bDefaultMusicModule = 11,
    },
    // 30 grand_staircase
    {
        .pBgTilemap0 = gRoom30BgMap0,
        .pBgLayer0Extra = gRoom30BgBlocks0,
        .pBgTilemap1 = gRoom30BgMap1,
        .pBgLayer1Extra = gRoom30BgBlocks1,
        .pBgTilemap2 = gRoom30BgMap2,
        .pBgLayer2Extra = gRoom30BgBlocks2,
        .pBgTilemap3 = gRoom30BgMap3,
        .pBgLayer3Extra = gRoom30BgBlocks3,
        .pCollisionBehaviorTable = gRoom30CollisionBehavior,
        .pCollisionTilemap = gRoom30CollisionMap,
        .pRoomResourceBlob = Room30Blob,
        .aBgResources = {{gRoom30TilesetA, gRoom30PaletteA}, {gRoom30TilesetB, gRoom30PaletteB}},
        .wScrollBoundMaxX = 472,
        .wScrollBoundMaxY = 870,
        .bEncounterVariant = 30,
        .bDefaultMusicModule = 6,
    },
    // 31 portrait_room
    {
        .pBgTilemap0 = gRoom31BgMap0,
        .pBgLayer0Extra = gRoom31BgBlocks0,
        .pBgTilemap1 = gRoom31BgMap1,
        .pBgLayer1Extra = gRoom31BgBlocks1,
        .pBgTilemap2 = gRoom31BgMap2,
        .pBgLayer2Extra = gRoom31BgBlocks2,
        .pBgTilemap3 = gRoom31BgMap3,
        .pBgLayer3Extra = gRoom31BgBlocks3,
        .pCollisionBehaviorTable = gRoom31CollisionBehavior,
        .pCollisionTilemap = gRoom31CollisionMap,
        .pRoomResourceBlob = Room31Blob,
        .aBgResources = {{gRoom31TilesetA, gRoom31PaletteA}, {gRoom31TilesetB, gRoom31PaletteB}},
        .bEncounterVariant = 30,
        .bDefaultMusicModule = 6,
    },
    // 32 portrait_room_passage
    {
        .pBgTilemap0 = gRoom32BgMap0,
        .pBgLayer0Extra = gRoom32BgBlocks0,
        .pBgTilemap1 = gRoom32BgMap1,
        .pBgLayer1Extra = gRoom32BgBlocks1,
        .pBgTilemap2 = gRoom32BgMap2,
        .pBgLayer2Extra = gRoom32BgBlocks2,
        .pBgTilemap3 = gRoom32BgMap3,
        .pBgLayer3Extra = gRoom32BgBlocks3,
        .pCollisionBehaviorTable = gRoom32CollisionBehavior,
        .pCollisionTilemap = gRoom32CollisionMap,
        .pRoomResourceBlob = Room32Blob,
        .aBgResources = {{gRoom32TilesetA, gRoom32PaletteA}, {gRoom32TilesetB, gRoom32PaletteB}},
        .bEncounterVariant = 30,
        .bDefaultMusicModule = 6,
    },
    // 33 hospital_wing
    {
        .pBgTilemap0 = gRoom33BgMap0,
        .pBgLayer0Extra = gRoom33BgBlocks0,
        .pBgTilemap1 = gRoom33BgMap1,
        .pBgLayer1Extra = gRoom33BgBlocks1,
        .pBgTilemap2 = gRoom33BgMap2,
        .pBgLayer2Extra = gRoom33BgBlocks2,
        .pBgTilemap3 = gRoom33BgMap3,
        .pBgLayer3Extra = gRoom33BgBlocks3,
        .pCollisionBehaviorTable = gRoom33CollisionBehavior,
        .pCollisionTilemap = gRoom33CollisionMap,
        .pRoomResourceBlob = Room33Blob,
        .aBgResources = {{gRoom33TilesetA, gRoom33PaletteA}, {gRoom33TilesetB, gRoom33PaletteB}},
        .bEncounterVariant = 30,
        .bDefaultMusicModule = 11,
    },
    // 34 library
    {
        .pBgTilemap0 = gRoom34BgMap0,
        .pBgLayer0Extra = gRoom34BgBlocks0,
        .pBgTilemap1 = gRoom34BgMap1,
        .pBgLayer1Extra = gRoom34BgBlocks1,
        .pBgTilemap2 = gRoom34BgMap2,
        .pBgLayer2Extra = gRoom34BgBlocks2,
        .pBgTilemap3 = gRoom34BgMap3,
        .pBgLayer3Extra = gRoom34BgBlocks3,
        .pCollisionBehaviorTable = gRoom34CollisionBehavior,
        .pCollisionTilemap = gRoom34CollisionMap,
        .pRoomResourceBlob = Room34Blob,
        .aBgResources = {{gRoom34TilesetA, gRoom34PaletteA}, {gRoom34TilesetB, gRoom34PaletteB}},
        .bEncounterCountA = 7,
        .bEncounterCountB = 7,
        .bEncounterCountC = 7,
        .bEncounterVariant = 9,
        .bDefaultMusicModule = 11,
    },
    // 35 library_2
    {
        .pBgTilemap0 = gRoom35BgMap0,
        .pBgLayer0Extra = gRoom35BgBlocks0,
        .pBgTilemap1 = gRoom35BgMap1,
        .pBgLayer1Extra = gRoom35BgBlocks1,
        .pBgTilemap2 = gRoom35BgMap2,
        .pBgLayer2Extra = gRoom35BgBlocks2,
        .pBgTilemap3 = gRoom35BgMap3,
        .pBgLayer3Extra = gRoom35BgBlocks3,
        .pCollisionBehaviorTable = gRoom35CollisionBehavior,
        .pCollisionTilemap = gRoom35CollisionMap,
        .pRoomResourceBlob = Room35Blob,
        .aBgResources = {{gRoom35TilesetA, gRoom35PaletteA}, {gRoom35TilesetB, gRoom35PaletteB}},
        .bEncounterCountA = 5,
        .bEncounterCountB = 5,
        .bEncounterCountC = 5,
        .bEncounterVariant = 10,
        .bDefaultMusicModule = 11,
    },
    // 36 fred_and_georges_shop
    {
        .pBgTilemap0 = gRoom36BgMap0,
        .pBgLayer0Extra = gRoom36BgBlocks0,
        .pBgTilemap1 = gRoom36BgMap1,
        .pBgLayer1Extra = gRoom36BgBlocks1,
        .pBgTilemap2 = gRoom36BgMap2,
        .pBgLayer2Extra = gRoom36BgBlocks2,
        .pBgTilemap3 = gRoom36BgMap3,
        .pBgLayer3Extra = gRoom36BgBlocks3,
        .pCollisionBehaviorTable = gRoom36CollisionBehavior,
        .pCollisionTilemap = gRoom36CollisionMap,
        .pRoomResourceBlob = Room36Blob,
        .aBgResources = {{gRoom36TilesetA, gRoom36PaletteA}, {gRoom36TilesetB, gRoom36PaletteB}},
        .wScrollBoundMinX = 32,
        .wScrollBoundMinY = 32,
        .wScrollBoundMaxX = 288,
        .wScrollBoundMaxY = 240,
        .bEncounterVariant = 30,
        .bDefaultMusicModule = 4,
    },
    // 37 wizard_card_collectors_club
    {
        .pBgTilemap0 = gRoom37BgMap0,
        .pBgLayer0Extra = gRoom37BgBlocks0,
        .pBgTilemap1 = gRoom37BgMap1,
        .pBgLayer1Extra = gRoom37BgBlocks1,
        .pBgTilemap2 = gRoom37BgMap2,
        .pBgLayer2Extra = gRoom37BgBlocks2,
        .pBgTilemap3 = gRoom37BgMap3,
        .pBgLayer3Extra = gRoom37BgBlocks3,
        .pCollisionBehaviorTable = gRoom37CollisionBehavior,
        .pCollisionTilemap = gRoom37CollisionMap,
        .pRoomResourceBlob = Room37Blob,
        .aBgResources = {{gRoom37TilesetA, gRoom37PaletteA}, {gRoom37TilesetB, gRoom37PaletteB}},
        .bEncounterVariant = 30,
        .bDefaultMusicModule = 4,
    },
    // 38 leaky_cauldron_cellar_1
    {
        .pBgTilemap0 = gRoom38BgMap0,
        .pBgLayer0Extra = gRoom38BgBlocks0,
        .pBgTilemap1 = gRoom38BgMap1,
        .pBgLayer1Extra = gRoom38BgBlocks1,
        .pBgTilemap2 = gRoom38BgMap2,
        .pBgLayer2Extra = gRoom38BgBlocks2,
        .pBgTilemap3 = gRoom38BgMap3,
        .pBgLayer3Extra = gRoom38BgBlocks3,
        .pCollisionBehaviorTable = gRoom38CollisionBehavior,
        .pCollisionTilemap = gRoom38CollisionMap,
        .pRoomResourceBlob = Room38Blob,
        .aBgResources = {{gRoom38TilesetA, gRoom38PaletteA}, {gRoom38TilesetB, gRoom38PaletteB}},
        .bEncounterCountA = 12,
        .bEncounterCountB = 12,
        .bDefaultMusicModule = 1,
    },
    // 39 leaky_cauldron_cellar_2
    {
        .pBgTilemap0 = gRoom39BgMap0,
        .pBgLayer0Extra = gRoom39BgBlocks0,
        .pBgTilemap1 = gRoom39BgMap1,
        .pBgLayer1Extra = gRoom39BgBlocks1,
        .pBgTilemap2 = gRoom39BgMap2,
        .pBgLayer2Extra = gRoom39BgBlocks2,
        .pBgTilemap3 = gRoom39BgMap3,
        .pBgLayer3Extra = gRoom39BgBlocks3,
        .pCollisionBehaviorTable = gRoom39CollisionBehavior,
        .pCollisionTilemap = gRoom39CollisionMap,
        .pRoomResourceBlob = Room39Blob,
        .aBgResources = {{gRoom39TilesetA, gRoom39PaletteA}, {gRoom39TilesetB, gRoom39PaletteB}},
        .bEncounterCountA = 12,
        .bEncounterCountB = 12,
        .bEncounterVariant = 1,
        .bDefaultMusicModule = 1,
    },
    // 40 leaky_cauldron_hallway
    {
        .pBgTilemap0 = gRoom40BgMap0,
        .pBgLayer0Extra = gRoom40BgBlocks0,
        .pBgTilemap1 = gRoom40BgMap1,
        .pBgLayer1Extra = gRoom40BgBlocks1,
        .pBgTilemap2 = gRoom40BgMap2,
        .pBgLayer2Extra = gRoom40BgBlocks2,
        .pBgTilemap3 = gRoom40BgMap3,
        .pBgLayer3Extra = gRoom40BgBlocks3,
        .pCollisionBehaviorTable = gRoom40CollisionBehavior,
        .pCollisionTilemap = gRoom40CollisionMap,
        .pRoomResourceBlob = Room40Blob,
        .aBgResources = {{gRoom40TilesetA, gRoom40PaletteA}, {gRoom40TilesetB, gRoom40PaletteB}},
        .bEncounterVariant = 30,
    },
    // 41 leaky_cauldron_harrys_room
    {
        .pBgTilemap0 = gRoom41BgMap0,
        .pBgLayer0Extra = gRoom41BgBlocks0,
        .pBgTilemap1 = gRoom41BgMap1,
        .pBgLayer1Extra = gRoom41BgBlocks1,
        .pBgTilemap2 = gRoom41BgMap2,
        .pBgLayer2Extra = gRoom41BgBlocks2,
        .pBgTilemap3 = gRoom41BgMap3,
        .pBgLayer3Extra = gRoom41BgBlocks3,
        .pCollisionBehaviorTable = gRoom41CollisionBehavior,
        .pCollisionTilemap = gRoom41CollisionMap,
        .pRoomResourceBlob = Room41Blob,
        .aBgResources = {{gRoom41TilesetA, gRoom41PaletteA}, {gRoom41TilesetB, gRoom41PaletteB}},
        .wScrollBoundMaxX = 285,
        .wScrollBoundMaxY = 294,
        .bEncounterVariant = 30,
    },
    // 42 leaky_cauldron_main
    {
        .pBgTilemap0 = gRoom42BgMap0,
        .pBgLayer0Extra = gRoom42BgBlocks0,
        .pBgTilemap1 = gRoom42BgMap1,
        .pBgLayer1Extra = gRoom42BgBlocks1,
        .pBgTilemap2 = gRoom42BgMap2,
        .pBgLayer2Extra = gRoom42BgBlocks2,
        .pBgTilemap3 = gRoom42BgMap3,
        .pBgLayer3Extra = gRoom42BgBlocks3,
        .pCollisionBehaviorTable = gRoom42CollisionBehavior,
        .pCollisionTilemap = gRoom42CollisionMap,
        .pRoomResourceBlob = Room42Blob,
        .aBgResources = {{gRoom42TilesetA, gRoom42PaletteA}, {gRoom42TilesetB, gRoom42PaletteB}},
        .wScrollBoundMaxX = 775,
        .wScrollBoundMaxY = 668,
        .bEncounterVariant = 30,
    },
    // 43 shrieking_shack_interior
    {
        .pBgTilemap0 = gRoom43BgMap0,
        .pBgLayer0Extra = gRoom43BgBlocks0,
        .pBgTilemap1 = gRoom43BgMap1,
        .pBgLayer1Extra = gRoom43BgBlocks1,
        .pBgTilemap2 = gRoom43BgMap2,
        .pBgLayer2Extra = gRoom43BgBlocks2,
        .pBgTilemap3 = gRoom43BgMap3,
        .pBgLayer3Extra = gRoom43BgBlocks3,
        .pCollisionBehaviorTable = gRoom43CollisionBehavior,
        .pCollisionTilemap = gRoom43CollisionMap,
        .pRoomResourceBlob = Room43Blob,
        .aBgResources = {{gRoom43TilesetA, gRoom43PaletteA}, {gRoom43TilesetB, gRoom43PaletteB}},
        .bEncounterCountA = 12,
        .bEncounterCountB = 12,
        .bEncounterCountC = 12,
        .bEncounterVariant = 21,
        .bDefaultMusicModule = 47,
    },
    // 44 shrieking_shack_path
    {
        .pBgTilemap0 = gRoom44BgMap0,
        .pBgLayer0Extra = gRoom44BgBlocks0,
        .pBgTilemap1 = gRoom44BgMap1,
        .pBgLayer1Extra = gRoom44BgBlocks1,
        .pBgTilemap2 = gRoom44BgMap2,
        .pBgLayer2Extra = gRoom44BgBlocks2,
        .pBgTilemap3 = gRoom44BgMap3,
        .pBgLayer3Extra = gRoom44BgBlocks3,
        .pCollisionBehaviorTable = gRoom44CollisionBehavior,
        .pCollisionTilemap = gRoom44CollisionMap,
        .pRoomResourceBlob = Room44Blob,
        .aBgResources = {{gRoom44TilesetA, gRoom44PaletteA}, {gRoom44TilesetB, gRoom44PaletteB}},
        .bEncounterCountA = 12,
        .bEncounterCountB = 12,
        .bEncounterCountC = 12,
        .bEncounterVariant = 21,
        .bDefaultMusicModule = 31,
    },
    // 45 shrieking_shack_path_2
    {
        .pBgTilemap0 = gRoom45BgMap0,
        .pBgLayer0Extra = gRoom45BgBlocks0,
        .pBgTilemap1 = gRoom45BgMap1,
        .pBgLayer1Extra = gRoom45BgBlocks1,
        .pBgTilemap2 = gRoom45BgMap2,
        .pBgLayer2Extra = gRoom45BgBlocks2,
        .pBgTilemap3 = gRoom45BgMap3,
        .pBgLayer3Extra = gRoom45BgBlocks3,
        .pCollisionBehaviorTable = gRoom45CollisionBehavior,
        .pCollisionTilemap = gRoom45CollisionMap,
        .pRoomResourceBlob = Room45Blob,
        .aBgResources = {{gRoom45TilesetA, gRoom45PaletteA}, {gRoom45TilesetB, gRoom45PaletteB}},
        .wScrollBoundMaxX = 1184,
        .wScrollBoundMaxY = 1056,
        .bEncounterCountA = 4,
        .bEncounterCountB = 4,
        .bEncounterCountC = 4,
        .bEncounterVariant = 22,
        .bDefaultMusicModule = 31,
    },
    // 46 shrieking_shack_path_3
    {
        .pBgTilemap0 = gRoom46BgMap0,
        .pBgLayer0Extra = gRoom46BgBlocks0,
        .pBgTilemap1 = gRoom46BgMap1,
        .pBgLayer1Extra = gRoom46BgBlocks1,
        .pBgTilemap2 = gRoom46BgMap2,
        .pBgLayer2Extra = gRoom46BgBlocks2,
        .pBgTilemap3 = gRoom46BgMap3,
        .pBgLayer3Extra = gRoom46BgBlocks3,
        .pCollisionBehaviorTable = gRoom46CollisionBehavior,
        .pCollisionTilemap = gRoom46CollisionMap,
        .pRoomResourceBlob = Room46Blob,
        .aBgResources = {{gRoom46TilesetA, gRoom46PaletteA}, {gRoom46TilesetB, gRoom46PaletteB}},
        .bEncounterCountA = 6,
        .bEncounterCountB = 6,
        .bEncounterCountC = 6,
        .bEncounterVariant = 21,
        .bDefaultMusicModule = 31,
    },
    // 47 shrieking_shack_path_4
    {
        .pBgTilemap0 = gRoom47BgMap0,
        .pBgLayer0Extra = gRoom47BgBlocks0,
        .pBgTilemap1 = gRoom47BgMap1,
        .pBgLayer1Extra = gRoom47BgBlocks1,
        .pBgTilemap2 = gRoom47BgMap2,
        .pBgLayer2Extra = gRoom47BgBlocks2,
        .pBgTilemap3 = gRoom47BgMap3,
        .pBgLayer3Extra = gRoom47BgBlocks3,
        .pCollisionBehaviorTable = gRoom47CollisionBehavior,
        .pCollisionTilemap = gRoom47CollisionMap,
        .pRoomResourceBlob = Room47Blob,
        .aBgResources = {{gRoom47TilesetA, gRoom47PaletteA}, {gRoom47TilesetB, gRoom47PaletteB}},
        .bEncounterCountA = 6,
        .bEncounterCountB = 6,
        .bEncounterCountC = 6,
        .bEncounterVariant = 21,
        .bDefaultMusicModule = 31,
    },
    // 48 shrieking_shack_path_5
    {
        .pBgTilemap0 = gRoom48BgMap0,
        .pBgLayer0Extra = gRoom48BgBlocks0,
        .pBgTilemap1 = gRoom48BgMap1,
        .pBgLayer1Extra = gRoom48BgBlocks1,
        .pBgTilemap2 = gRoom48BgMap2,
        .pBgLayer2Extra = gRoom48BgBlocks2,
        .pBgTilemap3 = gRoom48BgMap3,
        .pBgLayer3Extra = gRoom48BgBlocks3,
        .pCollisionBehaviorTable = gRoom48CollisionBehavior,
        .pCollisionTilemap = gRoom48CollisionMap,
        .pRoomResourceBlob = Room48Blob,
        .aBgResources = {{gRoom48TilesetA, gRoom48PaletteA}, {gRoom48TilesetB, gRoom48PaletteB}},
        .bEncounterCountA = 6,
        .bEncounterCountB = 6,
        .bEncounterCountC = 6,
        .bEncounterVariant = 21,
        .bDefaultMusicModule = 31,
    },
    // 49 shrieking_shack_path_6
    {
        .pBgTilemap0 = gRoom49BgMap0,
        .pBgLayer0Extra = gRoom49BgBlocks0,
        .pBgTilemap1 = gRoom49BgMap1,
        .pBgLayer1Extra = gRoom49BgBlocks1,
        .pBgTilemap2 = gRoom49BgMap2,
        .pBgLayer2Extra = gRoom49BgBlocks2,
        .pBgTilemap3 = gRoom49BgMap3,
        .pBgLayer3Extra = gRoom49BgBlocks3,
        .pCollisionBehaviorTable = gRoom49CollisionBehavior,
        .pCollisionTilemap = gRoom49CollisionMap,
        .pRoomResourceBlob = Room49Blob,
        .aBgResources = {{gRoom49TilesetA, gRoom49PaletteA}, {gRoom49TilesetB, gRoom49PaletteB}},
        .bEncounterCountA = 6,
        .bEncounterCountB = 6,
        .bEncounterCountC = 6,
        .bEncounterVariant = 21,
        .bDefaultMusicModule = 31,
    },
    // 50 diagon_alley_test_map1
    {
        .pBgTilemap0 = gRoom50BgMap0,
        .pBgLayer0Extra = gRoom50BgBlocks0,
        .pBgTilemap1 = gRoom50BgMap1,
        .pBgLayer1Extra = gRoom50BgBlocks1,
        .pBgTilemap2 = gRoom50BgMap2,
        .pBgLayer2Extra = gRoom50BgBlocks2,
        .pBgTilemap3 = gRoom50BgMap3,
        .pBgLayer3Extra = gRoom50BgBlocks3,
        .pCollisionBehaviorTable = gRoom50CollisionBehavior,
        .pCollisionTilemap = gRoom50CollisionMap,
        .pRoomResourceBlob = Room50Blob,
        .aBgResources = {{gRoom50TilesetA, gRoom50PaletteA}, {gRoom50TilesetB, gRoom50PaletteB}},
        .bEncounterCountA = 12,
        .bEncounterCountB = 12,
        .bEncounterVariant = 27,
        .bDefaultMusicModule = 4,
    },
    // 51 diagon_alley_test_map_2
    {
        .pBgTilemap0 = gRoom51BgMap0,
        .pBgLayer0Extra = gRoom51BgBlocks0,
        .pBgTilemap1 = gRoom51BgMap1,
        .pBgLayer1Extra = gRoom51BgBlocks1,
        .pBgTilemap2 = gRoom51BgMap2,
        .pBgLayer2Extra = gRoom51BgBlocks2,
        .pBgTilemap3 = gRoom51BgMap3,
        .pBgLayer3Extra = gRoom51BgBlocks3,
        .pCollisionBehaviorTable = gRoom51CollisionBehavior,
        .pCollisionTilemap = gRoom51CollisionMap,
        .pRoomResourceBlob = Room51Blob,
        .aBgResources = {{gRoom51TilesetA, gRoom51PaletteA}, {gRoom51TilesetB, gRoom51PaletteB}},
        .bEncounterCountA = 12,
        .bEncounterCountB = 12,
        .bEncounterVariant = 28,
        .bDefaultMusicModule = 4,
    },
    // 52 diagon_alley_test_map_3
    {
        .pBgTilemap0 = gRoom52BgMap0,
        .pBgLayer0Extra = gRoom52BgBlocks0,
        .pBgTilemap1 = gRoom52BgMap1,
        .pBgLayer1Extra = gRoom52BgBlocks1,
        .pBgTilemap2 = gRoom52BgMap2,
        .pBgLayer2Extra = gRoom52BgBlocks2,
        .pBgTilemap3 = gRoom52BgMap3,
        .pBgLayer3Extra = gRoom52BgBlocks3,
        .pCollisionBehaviorTable = gRoom52CollisionBehavior,
        .pCollisionTilemap = gRoom52CollisionMap,
        .pRoomResourceBlob = Room52Blob,
        .aBgResources = {{gRoom52TilesetA, gRoom52PaletteA}, {gRoom52TilesetB, gRoom52PaletteB}},
        .bEncounterCountA = 12,
        .bEncounterCountB = 12,
        .bEncounterVariant = 29,
        .bDefaultMusicModule = 4,
    },
    // 53 diagon_alley_test_map_4
    {
        .pBgTilemap0 = gRoom53BgMap0,
        .pBgLayer0Extra = gRoom53BgBlocks0,
        .pBgTilemap1 = gRoom53BgMap1,
        .pBgLayer1Extra = gRoom53BgBlocks1,
        .pBgTilemap2 = gRoom53BgMap2,
        .pBgLayer2Extra = gRoom53BgBlocks2,
        .pBgTilemap3 = gRoom53BgMap3,
        .pBgLayer3Extra = gRoom53BgBlocks3,
        .pCollisionBehaviorTable = gRoom53CollisionBehavior,
        .pCollisionTilemap = gRoom53CollisionMap,
        .pRoomResourceBlob = Room53Blob,
        .aBgResources = {{gRoom53TilesetA, gRoom53PaletteA}, {gRoom53TilesetB, gRoom53PaletteB}},
        .bEncounterCountA = 10,
        .bEncounterCountB = 10,
        .bEncounterVariant = 2,
        .bDefaultMusicModule = 4,
    },
    // 54 diagon_alley_test_map_5
    {
        .pBgTilemap0 = gRoom54BgMap0,
        .pBgLayer0Extra = gRoom54BgBlocks0,
        .pBgTilemap1 = gRoom54BgMap1,
        .pBgLayer1Extra = gRoom54BgBlocks1,
        .pBgTilemap2 = gRoom54BgMap2,
        .pBgLayer2Extra = gRoom54BgBlocks2,
        .pBgTilemap3 = gRoom54BgMap3,
        .pBgLayer3Extra = gRoom54BgBlocks3,
        .pCollisionBehaviorTable = gRoom54CollisionBehavior,
        .pCollisionTilemap = gRoom54CollisionMap,
        .pRoomResourceBlob = Room54Blob,
        .aBgResources = {{gRoom54TilesetA, gRoom54PaletteA}, {gRoom54TilesetB, gRoom54PaletteB}},
        .bEncounterCountA = 12,
        .bEncounterCountB = 12,
        .bEncounterVariant = 3,
        .bDefaultMusicModule = 4,
    },
};
