#!/usr/bin/env python3
"""One-time bootstrap: extract the item/equipment table
(g_pItemTable) from the US baserom into curated, editable JSON
under data/items/. See docs/formats/save.md's "Item quantities and
equipment" section for how the table's address/stride/count and each
field were identified.

Mirrors tools/monsters/extract_monsters.py's role for the Folio Bruti
monster table: data/items/ is NOT regenerated by `just build` -- it's
local, user-editable source, and it's gitignored, same footing as the
baserom, per hard rule 2 (CLAUDE.md). Every clone needs to run this
once (see the `extract-items` recipe) before building. Always
overwrites existing files; do not run it against already-hand-edited
content.

Table content is not yet confirmed identical between US/JP, so this
only ever reads baserom.us.gba for now -- see docs/formats/save.md.

Each record also gets a leading "_name" field: the item's display name,
decoded straight from the ROM's dialog text table via the record's own
nNameTextId field. This is a read-only annotation for human readability,
not part of the real 52-byte record -- pack_items.py ignores it entirely
(see item_codec.pack_record). Following extract_monsters.py's precedent
for its own "_description" annotation, "_name" is set to null for
indices >= REAL_ITEM_COUNT (79): the dummy record at 79 and the all-zero
padding at 80-131 aren't real items, and their nNameTextId (0 in every
case) would otherwise decode to unrelated text (the first dialog string)
rather than anything meaningful for that slot.

Usage: extract_items.py   (reads baserom.us.gba, writes data/items/items.json)
"""
import json
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent))
from item_codec import ITEM_COUNT, ITEM_TABLE_ADDR, REAL_ITEM_COUNT, RECORD_SIZE, unpack_record

sys.path.insert(0, str(Path(__file__).parent.parent / "text"))
from decode_dialog_text import decode_dialog_text

ROM_BASE = 0x08000000


def decode_string(rom: bytes, string_id: int) -> str:
    data = decode_dialog_text(rom, 0, string_id)  # lang 0 = English US
    data = data.rstrip(b"\x00")
    return data.decode("latin-1")


def main() -> None:
    with open("baserom.us.gba", "rb") as f:
        rom = f.read()

    base = ITEM_TABLE_ADDR - ROM_BASE
    records = []
    for i in range(ITEM_COUNT):
        off = base + i * RECORD_SIZE
        record = unpack_record(rom[off:off + RECORD_SIZE])
        out = {"_name": decode_string(rom, record["nNameTextId"]) if i < REAL_ITEM_COUNT else None}
        out.update(record)
        records.append(out)

    out_dir = Path("data/items")
    out_dir.mkdir(parents=True, exist_ok=True)
    path = out_dir / "items.json"
    path.write_text(json.dumps(records, indent=1) + "\n")
    print(f"{ITEM_COUNT} item records -> {path}", file=sys.stderr)


if __name__ == "__main__":
    main()
