#include "types.h"
#include "overworld/room_script_bytecode.h"

#include "v4/chain0.h"
#include "v4/chain1.h"
#include "v4/chain2.h"
#include "v4/chain3.h"
#include "v4/chain4.h"
#include "v4/chain5.h"
#include "v4/chain6.h"
#include "v4/chain7.h"
#include "v4/chain8.h"
#include "v4/chain9.h"
#include "v4/chain10.h"
#include "v4/chain11.h"
#include "v4/chain12.h"
#include "v4/chain13.h"
#include "v4/chain14.h"
