#!/usr/bin/env python3
"""One-time bootstrap: extract the battle-script bytecode
table from the US baserom into curated, editable text under
data/battle_scripts/. See docs/formats/battle_scripts.md.

Mirrors tools/monsters/extract_monsters.py's role for the Folio Bruti
table: data/battle_scripts/ is NOT regenerated by `just build` -- it's local,
user-editable source, and it's gitignored, same footing as the baserom,
per hard rule 2 (CLAUDE.md). Every clone needs to run this once (see the
`extract-battle-scripts` recipe) before building. Clears every `*.txt` file in
the output directory before writing, so a script whose name changes (via
`script_names.json`) doesn't leave its old filename behind as a stale
orphan; do not run it against already-hand-edited content.

Each of the 65 scripts (effect ids 0-64) becomes its own text file --
one instruction per line, "<name> [operand operand ...]" (see
battle_scripts_codec.format_script_text). Instruction names come from
opcodes.json at extraction time, so re-running this after naming a new
opcode there refreshes every script's text to use the new name.

A script's filename (and, via pack_battle_scripts.py, its assembly label)
comes from script_names.json (effect id -> curated {"name",
"description"}) when that effect id has an entry there, falling back to
the default "EffectN" otherwise. script_names.json is committed (same
footing as opcodes.json -- curated RE knowledge, not extracted content),
so identifications made there survive re-running this bootstrap, unlike
a plain filename rename (see "Renaming a script" in
docs/formats/battle_scripts.md). Each entry's "description", if present,
is written as a leading "# ..." comment in the script's text --
purely informational, ignored by parse_script_text/pack_battle_scripts.py.

Effect id -> filename order is recorded explicitly in
data/battle_scripts/index.json (a JSON array of filenames, position = effect
id) rather than inferred from the filenames themselves, so a script's
file can be freely renamed later (once its real purpose is identified)
without disturbing build order -- pack_battle_scripts.py reads this same
index, never a directory listing. This bootstrap always (re)writes
index.json with the names derived from script_names.json (or the
default "EffectN.txt" names where absent); if you've renamed files by
hand instead of via script_names.json, re-running this deletes that
-- same caveat as the rest of this file's content.

Content is not yet confirmed identical between US/JP (unlike
Krawall/dialog text), so this only ever reads baserom.us.gba for now.

Usage: extract_battle_scripts.py   (reads baserom.us.gba, writes data/battle_scripts/)
"""
import json
import struct
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent))
from battle_scripts_codec import (
    SCRIPT_COUNT,
    SCRIPT_DATA_START,
    SCRIPT_DESCRIPTION_BY_EFFECT_ID,
    SCRIPT_NAME_BY_EFFECT_ID,
    SCRIPT_TABLE_ADDR,
    decode_script,
    format_script_text,
)

ROM_BASE = 0x08000000


def main() -> None:
    rom_path = Path(__file__).parent.parent.parent / "baserom.us.gba"
    rom = rom_path.read_bytes()

    def off(addr: int) -> int:
        return addr - ROM_BASE

    pointers = [
        struct.unpack_from("<I", rom, off(SCRIPT_TABLE_ADDR + i * 4))[0]
        for i in range(SCRIPT_COUNT)
    ]
    if pointers[0] != SCRIPT_DATA_START:
        sys.exit(f"script 0 pointer {pointers[0]:#x} != expected SCRIPT_DATA_START {SCRIPT_DATA_START:#x} "
                  "-- baserom.us.gba doesn't match the layout this tool was built against")

    out_dir = Path(__file__).parent.parent.parent / "data" / "battle_scripts"
    out_dir.mkdir(parents=True, exist_ok=True)
    for stale in out_dir.glob("*.txt"):
        stale.unlink()

    filenames = []
    for i in range(SCRIPT_COUNT):
        start = pointers[i]
        end = pointers[i + 1] if i + 1 < SCRIPT_COUNT else SCRIPT_TABLE_ADDR
        raw = rom[off(start):off(end)]
        instructions = decode_script(raw)
        filename = f"{SCRIPT_NAME_BY_EFFECT_ID.get(i, f'Effect{i}')}.txt"
        text = format_script_text(instructions, SCRIPT_DESCRIPTION_BY_EFFECT_ID.get(i))
        (out_dir / filename).write_text(text)
        filenames.append(filename)

    (out_dir / "index.json").write_text(json.dumps(filenames, indent=2) + "\n")
    print(f"wrote {SCRIPT_COUNT} scripts + index.json to {out_dir}")


if __name__ == "__main__":
    main()
