const u8 g_abRoom16V1Chain68[] = {
    RS_ArmChainYield(1),
    RS_RespawnRowAndRunChain(0, 66),
    RS_ArmChainYield(1),
    RS_DelayedRespawnRowAndRunChain(5, 0, 0),
    RS_RespawnRowAndRunChain(0, 67),
    RS_ArmChainYield(1),
    RS_DelayedRespawnRowAndRunChain(7, 0, 0),
    RS_RespawnRowAndRunChain(0, 68),
    RS_ArmChainYield(1),
    RS_DelayedRespawnRowAndRunChain(6, 0, 0),
    RS_RespawnRowAndRunChain(0, 70),
    RS_ArmChainYield(1),
    RS_DelayedRespawnRowAndRunChain(7, 0, 0),
    RS_RespawnRowAndRunChain(0, 71),
    RS_ArmChainYield(1),
    RS_DelayedRespawnRowAndRunChain(6, 0, 0),
    RS_RespawnRowAndRunChain(0, 72),
    RS_End(),
};
