#pragma once

#include "room_script.h"

// Room-script opcode handlers, indexed by g_apRoomScriptOpcodeHandlers.
extern void RoomScriptOpDespawnTileObject(RoomScriptRecord *pRecord);
extern void RoomScriptOp2(RoomScriptRecord *pRecord);
void RoomScriptOpSetTileObjectFlagBit(RoomScriptRecord *pRecord);
void RoomScriptOpClearTileObjectFlagBit(RoomScriptRecord *pRecord);
extern void RoomScriptOpShowRoomDialog(RoomScriptRecord *pRecord);
void RoomScriptOpPauseMusic(RoomScriptRecord *pRecord);
void RoomScriptOpResumeMusic(RoomScriptRecord *pRecord);
void RoomScriptOpPlayMusicModuleAndFlagIfChain1(RoomScriptRecord *pRecord);
void RoomScriptOpPlayRoomSoundEffect(RoomScriptRecord *pRecord);
void RoomScriptOpPlaySoundById(RoomScriptRecord *pRecord);
void RoomScriptOpSetRoomMusicVolume(RoomScriptRecord *pRecord);
void RoomScriptOpSetSoundEffectVolume(RoomScriptRecord *pRecord);
extern void RoomScriptOpSetCameraPanSpeedOrRunRowChain(RoomScriptRecord *pRecord);
void RoomScriptOpSetStoryStage(RoomScriptRecord *pRecord);
void RoomScriptOpSetTileObjectAnimState(RoomScriptRecord *pRecord);
extern void RoomScriptOpQueueTileObjectMove(RoomScriptRecord *pRecord);
void RoomScriptOpReturnToOverworld(RoomScriptRecord *pRecord);
extern void RoomScriptOpSetAllQueuedMoveParams(RoomScriptRecord *pRecord);
void RoomScriptOpClearAllQueuedMoves(RoomScriptRecord *pRecord);
extern void RoomScriptOpSetTileObjectPosition(RoomScriptRecord *pRecord);
extern void RoomScriptOpPlayCutscene(RoomScriptRecord *pRecord);
void RoomScriptOpCloseRoomDialog(RoomScriptRecord *pRecord);
extern void RoomScriptOpSetTileObjectShadow(RoomScriptRecord *pRecord);
extern void RoomScriptOpStartObjectAnimSequence(RoomScriptRecord *pRecord);
extern void RoomScriptOpStartTileObjectScript(RoomScriptRecord *pRecord);
void RoomScriptOpPlayTileObjectAnimation(RoomScriptRecord *pRecord);
void RoomScriptOpOpenMainMenu(RoomScriptRecord *pRecord);
void RoomScriptOpArmChainYield(RoomScriptRecord *pRecord);
void RoomScriptOpGotoIfQuestStateCompare(RoomScriptRecord *pRecord);
void RoomScriptOpGotoIfQuestStatePairCompare(RoomScriptRecord *pRecord);
void RoomScriptOpSetQuestState(RoomScriptRecord *pRecord);
void RoomScriptOpCopyQuestState(RoomScriptRecord *pRecord);
void RoomScriptOpCancelObjectAnimSequence(RoomScriptRecord *pRecord);
void RoomScriptOpSetTileObjectAnimStateWithSpeed(RoomScriptRecord *pRecord);
void RoomScriptOpPatchRoomBackgroundTile(RoomScriptRecord *pRecord);
void RoomScriptOpShowLoadingScreenTransition(RoomScriptRecord *pRecord);
void RoomScriptOpPlayScreenTransitionOut(RoomScriptRecord *pRecord);
void RoomScriptOpPlayScreenTransitionIn(RoomScriptRecord *pRecord);
void RoomScriptOpRecruitPartyFollower(RoomScriptRecord *pRecord);
void RoomScriptOpRemovePartyFollower(RoomScriptRecord *pRecord);
void RoomScriptOpSpawnPartyFollowerAtTile(RoomScriptRecord *pRecord);
void RoomScriptOp42(RoomScriptRecord *pRecord);
void RoomScriptOpStartBattle(RoomScriptRecord *pRecord);
void RoomScriptOpSetTileObjectAnimStateValue(RoomScriptRecord *pRecord);
void RoomScriptOpGrantRoomReward(RoomScriptRecord *pRecord);
void RoomScriptOpSetBackgroundBlendLayers(RoomScriptRecord *pRecord);
void RoomScriptOpShowBackgroundLayer(RoomScriptRecord *pRecord);
void RoomScriptOpHideBackgroundLayer(RoomScriptRecord *pRecord);
void RoomScriptOpSetBackgroundPriority(RoomScriptRecord *pRecord);
extern void RoomScriptOp50(RoomScriptRecord *pRecord);
extern void RoomScriptOpPlaySpecialSceneEffect(RoomScriptRecord *pRecord);
extern void RoomScriptOpSetCameraPanSpeedOrRunRowChainAlt(RoomScriptRecord *pRecord);
void RoomScriptOpSetTileObjectAndLinkedVisible(RoomScriptRecord *pRecord);
void RoomScriptOpGotoIfStoryStageCompare(RoomScriptRecord *pRecord);
void RoomScriptOpSetRandomQuestState(RoomScriptRecord *pRecord);
void RoomScriptOpNoOp(RoomScriptRecord *pRecord);
void RoomScriptOpSetScreenWindow(RoomScriptRecord *pRecord);
void RoomScriptOpHideScreenWindow(RoomScriptRecord *pRecord);
void RoomScriptOpSetTileObjectFacing(RoomScriptRecord *pRecord);
void RoomScriptOpAddQuestState(RoomScriptRecord *pRecord);
void RoomScriptOpSubtractQuestState(RoomScriptRecord *pRecord);
void RoomScriptOpClearQuestStateUpperHalf(RoomScriptRecord *pRecord);
void RoomScriptOpNoOpAlt(RoomScriptRecord *pRecord);
void RoomScriptOpInvokeChainIfEnabled(RoomScriptRecord *pRecord);
void RoomScriptOpGrantPartyExperience(RoomScriptRecord *pRecord);
void RoomScriptOpSetBattleDefeatState(RoomScriptRecord *pRecord);
extern void RoomScriptOpSetTileObjectDrawLayer(RoomScriptRecord *pRecord);
extern void RoomScriptOpEnterFredAndGeorgesShop(RoomScriptRecord *pRecord);
extern void RoomScriptOpFullHealParty(RoomScriptRecord *pRecord);
void RoomScriptOpRespawnRowAndRunChain(RoomScriptRecord *pRecord);
extern void RoomScriptOpStartMinigame(RoomScriptRecord *pRecord);
void RoomScriptOpDespawnRoomRowObjects(RoomScriptRecord *pRecord);
void RoomScriptOpGrantPartySpell(RoomScriptRecord *pRecord);
void RoomScriptOpSetOverworldMonstersDisabled(RoomScriptRecord *pRecord);
void RoomScriptOpClearOverworldMonstersDisabled(RoomScriptRecord *pRecord);
void RoomScriptOpSetTileObjectFacingAndScriptPage(RoomScriptRecord *pRecord);
void RoomScriptOpSetTileObjectSpecialFlag(RoomScriptRecord *pRecord);
extern void RoomScriptOpUnlockMinigame(RoomScriptRecord *pRecord);
void RoomScriptOpShowRewardPickupMessage(RoomScriptRecord *pRecord);
void RoomScriptOpShowItemRemovedMessage(RoomScriptRecord *pRecord);
void RoomScriptOpShowSpellLearnedMessage(RoomScriptRecord *pRecord);
void RoomScriptOpSetPauseMenuLocked(RoomScriptRecord *pRecord);
extern void RoomScriptOpGotoIfFolioPageGroupComplete(RoomScriptRecord *pRecord);
void RoomScriptOpShowFolioCategoryStatusMessage(RoomScriptRecord *pRecord);
extern void RoomScriptOpShowMinigameUnlockedMessage(RoomScriptRecord *pRecord);
void RoomScriptOpShowPartyLevelUpMessage(RoomScriptRecord *pRecord);
void RoomScriptOpGrantPartyLevelUps(RoomScriptRecord *pRecord);
void RoomScriptOpUnmuteAllMusicChannels(RoomScriptRecord *pRecord);
void RoomScriptOpConsumeRoomItem(RoomScriptRecord *pRecord);
void RoomScriptOpResetPartyLeaderSelection(RoomScriptRecord *pRecord);
extern void RoomScriptOpGotoIfAllQuestFlagsSet(RoomScriptRecord *pRecord);
void RoomScriptOpSetPendingChainFromExitParam(RoomScriptRecord *pRecord);
