#!/usr/bin/env python3
"""One-time bootstrap: decode the game's real dialog/UI string tables
from the US baserom into curated, editable JSON under data/text/. See
docs/formats/text.md's "The real dialog string table, decoded" section.

Mirrors tools/krawall_migrate.py's role for audio: data/text/ is NOT
regenerated by `just build` -- it's local, user-editable source, and it's
gitignored, same footing as the baserom, per hard rule 2 (CLAUDE.md).
Every clone needs to run this once (see the `migrate-text` recipe)
before building. Always overwrites existing files; do not run it against
already-hand-edited content.

Text is currently only located/decoded from the US/EU cart (8 languages
in one ROM image); the JP cart's dialog text has not been investigated
and is very likely a different mechanism entirely (JP needs far more than
256 base + 4096 extended glyph codes) -- this only ever reads
baserom.us.gba.

Each data/text/<lang>.json holds:
  - "tree_hex": the language's real Huffman tree bytes (hex), needed
    verbatim to reassemble a byte-exact blob (see tools/text_codec.py).
  - "encode_map": {glyph_byte: packed_int}, captured empirically from
    real bit paths in this language's actual compressed data -- NOT
    re-derivable from tree_hex alone, since the tree contains
    structurally-reachable duplicate leaves (and, past those, genuinely
    unreachable/cyclic garbage -- see docs/formats/text.md) that real
    content never exercises. Required for pack_text.py to re-encode any
    edited/unmodified string later without needing the baserom again.
    Each bit path (max real depth 11 bits) is packed into one integer
    via text_codec.path_to_int()'s leading-1-sentinel trick
    (value = (1 << length) | code) instead of a nested [bit, bit, ...]
    array, so each symbol is one compact JSON number, not one array
    element per line.
  - "strings": one entry per string ID (index = ID), each the decoded
    text run through text_codec.bytes_to_editable() -- plain, editable
    ASCII for ordinary Latin text; anything outside 0x20-0x7E (control
    codes, or the not-yet-decoded extended/accented two-byte glyph
    codes) becomes an opaque but exact Private-Use-Area placeholder
    character, not a real accented letter -- see text_codec.py.

Usage: text_migrate.py   (reads baserom.us.gba, writes data/text/)
"""
import json
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent))
from text_codec import (
    TextBlob, build_encode_map_from_corpus, bytes_to_editable, lang_base, LANGS, path_to_int,
)


def main() -> None:
    with open("baserom.us.gba", "rb") as f:
        rom = f.read()

    out_dir = Path("data/text")
    out_dir.mkdir(parents=True, exist_ok=True)

    for i, code in enumerate(LANGS):
        base = lang_base(rom, i)
        blob = TextBlob.from_rom(rom, base)
        encode_map = build_encode_map_from_corpus(blob)
        strings = []
        for sid in range(blob.count):
            data = blob.decode(sid)
            assert data[-1] == 0, f"{code} string {sid}: missing terminator"
            strings.append(bytes_to_editable(data[:-1]))

        payload = {
            "tree_hex": blob.tree_bytes.hex(),
            "encode_map": {str(sym): path_to_int(bits) for sym, bits in sorted(encode_map.items())},
            "strings": strings,
        }
        path = out_dir / f"{code}.json"
        path.write_text(json.dumps(payload, indent=1, ensure_ascii=False) + "\n")
        print(f"{code}: {blob.count} strings -> {path}", file=sys.stderr)


if __name__ == "__main__":
    main()
