#!/usr/bin/env python3
"""One-time bootstrap: extract the 3 per-character level-up stat tables
(Harry/Hermione/Ron) from the US baserom into curated, editable JSON
under data/levels/. See docs/memory-map/battle.md.

Mirrors tools/monsters/extract_monsters.py's role for the Folio Bruti
table: data/levels/ is NOT regenerated by `just build` -- it's local,
user-editable source, and it's gitignored, same footing as the baserom,
per hard rule 2 (CLAUDE.md). Every clone needs to run this once (see the
`extract-levels` recipe) before building. Always overwrites existing
files; do not run it against already-hand-edited content.

Content is not yet confirmed identical between US/JP, so this only ever
reads baserom.us.gba for now.

Usage: extract_levels.py   (reads baserom.us.gba, writes data/levels/)
"""
import json
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent))
from level_codec import LEVEL_COUNT, RECORD_SIZE, TABLE_ADDR, unpack_record

ROM_BASE = 0x08000000


def main() -> None:
    with open("baserom.us.gba", "rb") as f:
        rom = f.read()

    out_dir = Path("data/levels")
    out_dir.mkdir(parents=True, exist_ok=True)

    for name, addr in TABLE_ADDR.items():
        base = addr - ROM_BASE
        records = []
        for i in range(LEVEL_COUNT):
            record = {"_level": i + 1}  # row i = displayed "Level i+1" (0-indexed table, see level_codec.py)
            record.update(unpack_record(rom[base + i * RECORD_SIZE: base + (i + 1) * RECORD_SIZE]))
            records.append(record)
        path = out_dir / f"{name.lower()}.json"
        path.write_text(json.dumps(records, indent=1) + "\n")
        print(f"{LEVEL_COUNT} {name} level records -> {path}", file=sys.stderr)


if __name__ == "__main__":
    main()
