const u8 g_abRoom29V1Chain38[] = {
    RS_ArmChainYield(1),
    RS_DespawnRoomRowObjects(12),
    RS_DespawnTileObject(13, 7),
    RS_DespawnTileObject(13, 4),
    RS_DespawnTileObject(13, 0),
    RS_DespawnTileObject(13, 3),
    RS_DespawnTileObject(13, 2),
    RS_DespawnTileObject(13, 1),
    RS_SetQuestState(2, 231),
    RS_SetQuestState(37, 25),
    RS_SetStoryStage(20),
    RS_SetTileObjectAnimStateWithSpeed(0, 255),
    RS_End(),
};
