#!/usr/bin/env python3
"""Pack every image-bank manifest row from its PNG sprites and bank.json.

Each bank has one fixed ROM range. Its index lists the sprites in ROM order
with their offset and compression settings, the bank's bit depth, and the
order of each sprite's palette/tiles/frames components; component addresses
follow from that order and the encoded sizes. See docs/formats/graphics.md
("Image-bank build format"). Encoded components and assembly go under
build/<ver>/images/; the matching C header goes under include/gen/<ver>/.
"""
import json
import re
import sys
from pathlib import Path

from sprite import COMPONENT_KINDS, COMPRESSION_TYPES, build

SYMBOL = re.compile(r"[A-Za-z_][A-Za-z0-9_]*\Z")
BANK_KEYS = {"format", "bpp", "componentOrder", "images"}
IMAGE_KEYS = {"name", "offset", "compression"}


def image_banks(ver: str):
    path = Path(f"regions.{ver}.txt")
    for lineno, raw in enumerate(path.read_text().splitlines(), 1):
        parts = raw.split("#", 1)[0].split()
        if not parts or parts[0] != "image-bank":
            continue
        if len(parts) != 5:
            raise ValueError(f"{path}:{lineno}: expected image-bank <start> <end> <dir> <name>")
        _, start, end, source, name = parts
        if not SYMBOL.fullmatch(name):
            raise ValueError(f"{path}:{lineno}: invalid bank name {name!r}")
        yield int(start, 16), int(end, 16), Path(source), name


def component_symbol(image: str, kind: str) -> str:
    return f"g{image}{kind.capitalize()}"


def load_index(source: Path) -> dict:
    index_path = source / "bank.json"
    index = json.loads(index_path.read_text())
    if set(index) != BANK_KEYS or index["format"] != 2:
        raise ValueError(f"{index_path}: expected format 2 with {', '.join(sorted(BANK_KEYS))}")
    if index["bpp"] not in (4, 8):
        raise ValueError(f"{index_path}: bpp must be 4 or 8")
    if sorted(index["componentOrder"]) != sorted(COMPONENT_KINDS):
        raise ValueError(f"{index_path}: componentOrder must list {', '.join(COMPONENT_KINDS)}")
    images = index["images"]
    if not isinstance(images, list) or not images:
        raise ValueError(f"{index_path}: images must be a nonempty list")
    names = set()
    for i, image in enumerate(images):
        if not isinstance(image, dict) or set(image) != IMAGE_KEYS:
            raise ValueError(f"{index_path}: image {i} needs {', '.join(sorted(IMAGE_KEYS))}")
        name, offset = image["name"], image["offset"]
        if not isinstance(name, str) or not SYMBOL.fullmatch(name) or name in names:
            raise ValueError(f"{index_path}: invalid or duplicate image name {name!r}")
        names.add(name)
        if (not isinstance(offset, list) or len(offset) != 2
                or not all(isinstance(v, int) and not isinstance(v, bool) for v in offset)):
            raise ValueError(f"{index_path}: {name}: offset must be [x, y] integers")
        if image["compression"] not in COMPRESSION_TYPES:
            raise ValueError(f"{index_path}: {name}: compression must be one of "
                             f"{', '.join(COMPRESSION_TYPES)}")
    extras = {p.stem for p in source.glob("*.png")} - names
    if extras:
        raise ValueError(f"{index_path}: unlisted PNG files: {', '.join(sorted(extras))}")
    return index


def pack_bank(ver: str, start: int, end: int, source: Path, name: str) -> int:
    index = load_index(source)
    out = Path(f"build/{ver}/images")
    bin_dir = out / name
    bin_dir.mkdir(parents=True, exist_ok=True)
    asm = []
    header = [
        "/* Code generated by tools/images/pack_images.py; DO NOT EDIT. */",
        "#pragma once",
        "",
        '#include "types.h"',
        "",
    ]
    cursor = start
    for image in index["images"]:
        png = source / f"{image['name']}.png"
        try:
            components = build(png, tuple(image["offset"]), image["compression"], index["bpp"])
        except (OSError, ValueError) as exc:
            raise ValueError(f"{png}: {exc}") from None
        for kind in index["componentOrder"]:
            data = components[kind]
            symbol = component_symbol(image["name"], kind)
            bin_path = bin_dir / f"{image['name']}.{kind}.bin"
            if not bin_path.is_file() or bin_path.read_bytes() != data:
                bin_path.write_bytes(data)
            cursor += len(data)
            if cursor > end:
                raise ValueError(f"{name}: {image['name']} {kind} exceeds {end:#010x}")
            asm += [f"{symbol}:", f'.incbin "{bin_path.as_posix()}"']
            header.append(f"extern const u8 {symbol}[];")
    if cursor != end:
        raise ValueError(f"{name}: packed {cursor - start:#x} bytes; region needs {end - start:#x}")

    header_out = Path(f"include/gen/{ver}")
    header_out.mkdir(parents=True, exist_ok=True)
    (out / f"{name}.s").write_text("\n".join(asm) + "\n")
    (header_out / f"{name}.h").write_text("\n".join(header) + "\n")
    return len(index["images"])


def main() -> None:
    if len(sys.argv) != 2:
        sys.exit(f"usage: {sys.argv[0]} <ver>")
    ver = sys.argv[1]
    try:
        banks = list(image_banks(ver))
        names = [name for _, _, _, name in banks]
        if len(names) != len(set(names)):
            raise ValueError(f"regions.{ver}.txt: duplicate image-bank name")
        for start, end, source, name in banks:
            count = pack_bank(ver, start, end, source, name)
            print(f"{ver}: packed {name}: {count} images, {end - start} bytes")
        if not banks:
            print(f"{ver}: no image-bank regions")
    except (OSError, ValueError, TypeError) as exc:
        sys.exit(str(exc))


if __name__ == "__main__":
    main()
