#!/usr/bin/env python3
"""Pack every image-bank manifest row from its ordered bank.json components.

Each bank has one fixed ROM range. Its index stores only component filenames
and linker symbol names; the ROM address of each component follows from its
position and encoded file size. Assembly goes under build/<ver>/images/;
the matching C header goes under include/gen/<ver>/. No decoder or
image-class rule lives here.
"""
import json
import re
import sys
from pathlib import Path

SYMBOL = re.compile(r"[A-Za-z_][A-Za-z0-9_]*\Z")
FILENAME = re.compile(r"[A-Za-z0-9_.-]+\.bin\Z")


def image_banks(ver: str):
    path = Path(f"regions.{ver}.txt")
    for lineno, raw in enumerate(path.read_text().splitlines(), 1):
        parts = raw.split("#", 1)[0].split()
        if not parts or parts[0] != "image-bank":
            continue
        if len(parts) != 5:
            raise ValueError(f"{path}:{lineno}: expected image-bank <start> <end> <dir> <name>")
        _, start, end, source, name = parts
        if not SYMBOL.fullmatch(name):
            raise ValueError(f"{path}:{lineno}: invalid bank name {name!r}")
        yield int(start, 16), int(end, 16), Path(source), name


def pack_bank(ver: str, start: int, end: int, source: Path, name: str) -> int:
    index_path = source / "bank.json"
    index = json.loads(index_path.read_text())
    if set(index) != {"format", "components"} or index["format"] != 1:
        raise ValueError(f"{index_path}: expected format 1 and components")
    components = index["components"]
    if not isinstance(components, list) or not components:
        raise ValueError(f"{index_path}: components must be a nonempty list")

    asm = []
    header = [
        "/* Code generated by tools/images/pack_images.py; DO NOT EDIT. */",
        "#pragma once",
        "",
        '#include "types.h"',
        "",
    ]
    used_files = set()
    used_symbols = set()
    cursor = start
    for i, component in enumerate(components):
        if not isinstance(component, dict) or set(component) != {"file", "symbol"}:
            raise ValueError(f"{index_path}: component {i} needs file and symbol")
        filename, symbol = component["file"], component["symbol"]
        if not isinstance(filename, str) or not FILENAME.fullmatch(filename):
            raise ValueError(f"{index_path}: invalid component filename {filename!r}")
        if not isinstance(symbol, str) or not SYMBOL.fullmatch(symbol):
            raise ValueError(f"{index_path}: invalid symbol {symbol!r}")
        if filename in used_files or symbol in used_symbols:
            raise ValueError(f"{index_path}: duplicate file or symbol at component {i}")
        used_files.add(filename)
        used_symbols.add(symbol)
        component_path = source / filename
        size = component_path.stat().st_size
        if size == 0:
            raise ValueError(f"{component_path}: empty component")
        cursor += size
        if cursor > end:
            raise ValueError(f"{name}: component {i} exceeds {end:#010x}")
        asm += [f"{symbol}:", f'.incbin "{component_path.as_posix()}"']
        header.append(f"extern const u8 {symbol}[];")

    extras = {p.name for p in source.glob("*.bin")} - used_files
    if extras:
        raise ValueError(f"{index_path}: unlisted .bin files: {', '.join(sorted(extras))}")
    if cursor != end:
        raise ValueError(f"{name}: packed {cursor - start:#x} bytes; region needs {end - start:#x}")

    out = Path(f"build/{ver}/images")
    out.mkdir(parents=True, exist_ok=True)
    header_out = Path(f"include/gen/{ver}")
    header_out.mkdir(parents=True, exist_ok=True)
    (out / f"{name}.s").write_text("\n".join(asm) + "\n")
    (header_out / f"{name}.h").write_text("\n".join(header) + "\n")
    return len(components)


def main() -> None:
    if len(sys.argv) != 2:
        sys.exit(f"usage: {sys.argv[0]} <ver>")
    ver = sys.argv[1]
    try:
        banks = list(image_banks(ver))
        names = [name for _, _, _, name in banks]
        if len(names) != len(set(names)):
            raise ValueError(f"regions.{ver}.txt: duplicate image-bank name")
        for start, end, source, name in banks:
            count = pack_bank(ver, start, end, source, name)
            print(f"{ver}: packed {name}: {count} components, {end - start} bytes")
        if not banks:
            print(f"{ver}: no image-bank regions")
    except (OSError, ValueError, TypeError) as exc:
        sys.exit(str(exc))


if __name__ == "__main__":
    main()
