#include "types.h"
#include "menu/folio_universitas.h"
#include "gen/graphics/menus.h"

#define FOLIO_CARD(n, frame)                                                                      \
    {                                                                                             \
        frame,                                                                                    \
        { (void *)gFamousWizardCard##n##Tiles, (void *)gFamousWizardCard##n##Frames,              \
          (void *)gFamousWizardCard##n##Palette, 0 }                                              \
    }

// Indexed by card number; the names are the card names (text 0x412 + index).
const FolioCardAsset g_aFolioCardAssets[FOLIO_UNIVERSITAS_CARD_COUNT] = {
    FOLIO_CARD(001, FolioCardFrameBlue),  // "Fulbert the Fearful"
    FOLIO_CARD(002, FolioCardFrameBlue),  // "Beatrix Bloxam"
    FOLIO_CARD(003, FolioCardFramePurple),  // "Merwyn the Malicious"
    FOLIO_CARD(004, FolioCardFrameBlue),  // "Hungarian Horntail Dragon"
    FOLIO_CARD(005, FolioCardFrameBlue),  // "Hebridean Black Dragon"
    FOLIO_CARD(006, FolioCardFramePurple),  // "Norwegian Ridgeback Dragon"
    FOLIO_CARD(007, FolioCardFrameBlue),  // "Xavier Rastrick"
    FOLIO_CARD(008, FolioCardFrameBlue),  // "Dymphna Furmage"
    FOLIO_CARD(009, FolioCardFramePurple),  // "Yardley Platt"
    FOLIO_CARD(010, FolioCardFrameRed),  // "Morgan le Fay"
    FOLIO_CARD(011, FolioCardFrameBlue),  // "Wendelin the Weird"
    FOLIO_CARD(012, FolioCardFrameBlue),  // "Honoria Nutcombe"
    FOLIO_CARD(013, FolioCardFramePurple),  // "Jocunda Sykes"
    FOLIO_CARD(014, FolioCardFrameBlue),  // "Justus Pilliwickle"
    FOLIO_CARD(015, FolioCardFrameBlue),  // "Adalbert Waffling"
    FOLIO_CARD(016, FolioCardFramePurple),  // "Edgar Stroulger"
    FOLIO_CARD(017, FolioCardFrameBlue),  // "Malodora Grymm"
    FOLIO_CARD(018, FolioCardFrameBlue),  // "Leticia Somnolens"
    FOLIO_CARD(019, FolioCardFramePurple),  // "Cordelia Misericordia"
    FOLIO_CARD(020, FolioCardFrameRed),  // "Carlotta Pinkstone"
    FOLIO_CARD(021, FolioCardFrameBlue),  // "Unicorn"
    FOLIO_CARD(022, FolioCardFrameBlue),  // "Manticore"
    FOLIO_CARD(023, FolioCardFramePurple),  // "Phoenix"
    FOLIO_CARD(024, FolioCardFrameBlue),  // "Burdock Muldoon"
    FOLIO_CARD(025, FolioCardFrameBlue),  // "Gondoline Oliphant"
    FOLIO_CARD(026, FolioCardFramePurple),  // "Almerick Sawbridge"
    FOLIO_CARD(027, FolioCardFrameBlue),  // "Montague Knightley"
    FOLIO_CARD(028, FolioCardFrameBlue),  // "Glanmore Peakes"
    FOLIO_CARD(029, FolioCardFramePurple),  // "Artemisia Lufkin"
    FOLIO_CARD(030, FolioCardFrameRed),  // "Merlin"
    FOLIO_CARD(031, FolioCardFrameBlue),  // "Sir Herbert Varney"
    FOLIO_CARD(032, FolioCardFrameBlue),  // "Amarillo Lestoat"
    FOLIO_CARD(033, FolioCardFramePurple),  // "Lady Carmilla Sanguina"
    FOLIO_CARD(034, FolioCardFrameBlue),  // "Albus Dumbledore"
    FOLIO_CARD(035, FolioCardFrameBlue),  // "Queen Maeve"
    FOLIO_CARD(036, FolioCardFramePurple),  // "Helga Hufflepuff"
    FOLIO_CARD(037, FolioCardFrameBlue),  // "Bridget Wenlock"
    FOLIO_CARD(038, FolioCardFrameBlue),  // "Miranda Goshawk"
    FOLIO_CARD(039, FolioCardFramePurple),  // "Rowena Ravenclaw"
    FOLIO_CARD(040, FolioCardFrameRed),  // "Godric Gryffindor"
    FOLIO_CARD(041, FolioCardFrameBlue),  // "Roland Kegg"
    FOLIO_CARD(042, FolioCardFrameBlue),  // "Gwenog Jones"
    FOLIO_CARD(043, FolioCardFramePurple),  // "Joscelind Wadcock"
    FOLIO_CARD(044, FolioCardFrameBlue),  // "Dunbar Oglethorpe"
    FOLIO_CARD(045, FolioCardFrameBlue),  // "Devlin Whitehorn"
    FOLIO_CARD(046, FolioCardFramePurple),  // "Cyprian Youdle"
    FOLIO_CARD(047, FolioCardFrameBlue),  // "Leopoldina Smethwyck"
    FOLIO_CARD(048, FolioCardFrameBlue),  // "Felix Sumerbee"
    FOLIO_CARD(049, FolioCardFramePurple),  // "Roderick Plumpton"
    FOLIO_CARD(050, FolioCardFrameRed),  // "Bowman Wright"
    FOLIO_CARD(051, FolioCardFrameRed),  // "Harry Potter"
};
