#include "types.h"
#include "graphics/object.h"
#include "menu/folio_universitas.h"
#include "gen/graphics/overworld.h"

#define FOLIO_THUMBNAIL(name) \
    { (void *)g##name##Tiles, (void *)g##name##Frames, (void *)g##name##Palette, 0 }

// The 51 card portraits, then the face-down card.
const ObjectAssetRecord g_aFolioCardThumbnails[FOLIO_UNIVERSITAS_CARD_COUNT + 1] = {
    FOLIO_THUMBNAIL(FolioCardThumbnail001),  // "Fulbert the Fearful"
    FOLIO_THUMBNAIL(FolioCardThumbnail002),  // "Beatrix Bloxam"
    FOLIO_THUMBNAIL(FolioCardThumbnail003),  // "Merwyn the Malicious"
    FOLIO_THUMBNAIL(FolioCardThumbnail004),  // "Hungarian Horntail Dragon"
    FOLIO_THUMBNAIL(FolioCardThumbnail005),  // "Hebridean Black Dragon"
    FOLIO_THUMBNAIL(FolioCardThumbnail006),  // "Norwegian Ridgeback Dragon"
    FOLIO_THUMBNAIL(FolioCardThumbnail007),  // "Xavier Rastrick"
    FOLIO_THUMBNAIL(FolioCardThumbnail008),  // "Dymphna Furmage"
    FOLIO_THUMBNAIL(FolioCardThumbnail009),  // "Yardley Platt"
    FOLIO_THUMBNAIL(FolioCardThumbnail010),  // "Morgan le Fay"
    FOLIO_THUMBNAIL(FolioCardThumbnail011),  // "Wendelin the Weird"
    FOLIO_THUMBNAIL(FolioCardThumbnail012),  // "Honoria Nutcombe"
    FOLIO_THUMBNAIL(FolioCardThumbnail013),  // "Jocunda Sykes"
    FOLIO_THUMBNAIL(FolioCardThumbnail014),  // "Justus Pilliwickle"
    FOLIO_THUMBNAIL(FolioCardThumbnail015),  // "Adalbert Waffling"
    FOLIO_THUMBNAIL(FolioCardThumbnail016),  // "Edgar Stroulger"
    FOLIO_THUMBNAIL(FolioCardThumbnail017),  // "Malodora Grymm"
    FOLIO_THUMBNAIL(FolioCardThumbnail018),  // "Leticia Somnolens"
    FOLIO_THUMBNAIL(FolioCardThumbnail019),  // "Cordelia Misericordia"
    FOLIO_THUMBNAIL(FolioCardThumbnail020),  // "Carlotta Pinkstone"
    FOLIO_THUMBNAIL(FolioCardThumbnail021),  // "Unicorn"
    FOLIO_THUMBNAIL(FolioCardThumbnail022),  // "Manticore"
    FOLIO_THUMBNAIL(FolioCardThumbnail023),  // "Phoenix"
    FOLIO_THUMBNAIL(FolioCardThumbnail024),  // "Burdock Muldoon"
    FOLIO_THUMBNAIL(FolioCardThumbnail025),  // "Gondoline Oliphant"
    FOLIO_THUMBNAIL(FolioCardThumbnail026),  // "Almerick Sawbridge"
    FOLIO_THUMBNAIL(FolioCardThumbnail027),  // "Montague Knightley"
    FOLIO_THUMBNAIL(FolioCardThumbnail028),  // "Glanmore Peakes"
    FOLIO_THUMBNAIL(FolioCardThumbnail029),  // "Artemisia Lufkin"
    FOLIO_THUMBNAIL(FolioCardThumbnail030),  // "Merlin"
    FOLIO_THUMBNAIL(FolioCardThumbnail031),  // "Sir Herbert Varney"
    FOLIO_THUMBNAIL(FolioCardThumbnail032),  // "Amarillo Lestoat"
    FOLIO_THUMBNAIL(FolioCardThumbnail033),  // "Lady Carmilla Sanguina"
    FOLIO_THUMBNAIL(FolioCardThumbnail034),  // "Albus Dumbledore"
    FOLIO_THUMBNAIL(FolioCardThumbnail035),  // "Queen Maeve"
    FOLIO_THUMBNAIL(FolioCardThumbnail036),  // "Helga Hufflepuff"
    FOLIO_THUMBNAIL(FolioCardThumbnail037),  // "Bridget Wenlock"
    FOLIO_THUMBNAIL(FolioCardThumbnail038),  // "Miranda Goshawk"
    FOLIO_THUMBNAIL(FolioCardThumbnail039),  // "Rowena Ravenclaw"
    FOLIO_THUMBNAIL(FolioCardThumbnail040),  // "Godric Gryffindor"
    FOLIO_THUMBNAIL(FolioCardThumbnail041),  // "Roland Kegg"
    FOLIO_THUMBNAIL(FolioCardThumbnail042),  // "Gwenog Jones"
    FOLIO_THUMBNAIL(FolioCardThumbnail043),  // "Joscelind Wadcock"
    FOLIO_THUMBNAIL(FolioCardThumbnail044),  // "Dunbar Oglethorpe"
    FOLIO_THUMBNAIL(FolioCardThumbnail045),  // "Devlin Whitehorn"
    FOLIO_THUMBNAIL(FolioCardThumbnail046),  // "Cyprian Youdle"
    FOLIO_THUMBNAIL(FolioCardThumbnail047),  // "Leopoldina Smethwyck"
    FOLIO_THUMBNAIL(FolioCardThumbnail048),  // "Felix Sumerbee"
    FOLIO_THUMBNAIL(FolioCardThumbnail049),  // "Roderick Plumpton"
    FOLIO_THUMBNAIL(FolioCardThumbnail050),  // "Bowman Wright"
    FOLIO_THUMBNAIL(FolioCardThumbnail051),  // "Harry Potter"
    FOLIO_THUMBNAIL(FolioCardBackThumbnail),
};
